### ISSUE TITLE
Verbesserungsvorschlag Manueller Umbruch in Text

### ISSUE THREAD

**Issue by raidsec** [SKB-CGN/ioBroker.energiefluss-erweitert#10]
Hallo,

erstmal wieder sehr geile Arbeit. Der neue Adapter ist jetzt schon der Hammer!!

Wäre es wie beim "alten" Energiesfluss-adapter möglich, einen manuellen Umbruch in den Text einzubauen? <br> hat leider nicht funktionert. Eilt aber nicht.

Vielen Dank!

**Comment by SKB-CGN** [comment]
Aktuell könntest Du ja 2 der Textbausteine anlegen. Da diese "Text-zentriert" sind, wirkt es, wie ein Textumbruch.

**Comment by reihd** [comment]
habe den Adapter mal getestet, ja, sehr modern, man kann wirklich sehr viel einstellen, dass macht es etwas Arbeitsreicher, aber ok. Kann man nicht die Konfiguration vom anderen Adapter übernehmen?

**Comment by SKB-CGN** [comment]
Die Adapter basieren auf verschiedenen Einstellungen und Daten. Ein Import ist nicht vorgesehen.

**Comment by SKB-CGN** [comment]
Hallo, dein Fehler wurde in der aktuellen Version berücksichtigt.
Bitte installiere diese Version und prüfe, ob alles erledigt ist.

Falls ja, bitte das Issue schließen.

Vielen Dank!
