### ISSUE TITLE
Probleme in der Responsive-Ansicht

### ISSUE THREAD

**Issue by exaware** [SKB-CGN/ioBroker.energiefluss-erweitert#110]
In meiner Vis stelle ich das Energieflussdiagramm in einem iFrame dar. Nun ist mir aufgefallen dass in Responsive-Ansichten, also z.B. auf dem Handy, unterhalb des iFrames kein weiteres Element angezeigt wird. Es wird vom iFrame überdeckt, siehe 1. Screenshot. Bei größeren Bildschirmen, z.B. auf dem Desktop-PC wird das Element unterhalb richtig dargestellt, siehe 2. Screenshot. Um mein Vis (Jarvis) auszuschließen habe ich das Ganze mit einem anderen iFrame probiert in dem ich ein Video darstelle probiert, dort gab es keine Probleme.

1. Screenshot
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/ff87036b-7d75-4340-830c-a66709717637)

2. Screenshot
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/391d900b-6b53-499a-b80d-8b0d21e53e0d)

**Comment by SKB-CGN** [comment]
Dies liegt nicht am Adapter, wenn die Ansicht problemlos dargestellt wird.

![Screenshot_20231114-193203.png](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/1b041185-fda2-4c25-bd6a-ed535b26add2)

Innerhalb des iFrame reagiert die Anzeige responsive - alles weitere muss in Jarvis erfolgen.

Ich denke, der Bereich ist zu groß gewählt.

**Comment by exaware** [comment]
Das ist gut zu wissen. Könntest du mir deine Einstellung in Jarvis zeigen? Weißt du auch wie den Energiefluss oben ausrichten kann anstatt mittig?

**Comment by SKB-CGN** [comment]
Meine Widgets sind in 3 Spalten nebeneinander angeordnet, damit sie auf einen Monitor passen.
Aufm Handy ist dann alles in einer Spalte untereinander.

Was heißt oben ausrichten?

**Comment by exaware** [comment]
Also bei mir wird alles mit dem Diagramm überdeckt, egal ob ich die anderen Elemente daneben oder darunter platziere.

Mit oben meine ich dass das Diagramm am oberen Rand ausgerichtet wird. Bei mir wird es Mittig ausgerichtet, dadurch habe ich dann oberhalb und unterhalb vom Diagramm Leerräume.

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/6f9171d9-26f5-407f-ab53-38ec2095236f)

**Comment by exaware** [comment]
Wenn ich es wie folgt ziehe, sind die Abstände ok. Aber drunter trotzdem nichts angezeigt. Ich nutze Jarvis 3.1.8 (Keine Beta)
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/3a60a18b-c933-4ab4-9f42-03ab1238ab32)

**Comment by exaware** [comment]
Außerdem passt sich bei dir das Widget der Höhe des iFrames an. Bei mir ist das nicht der Fall. Mein Widget hat auch runde Ecken, daran kann man erkennen, dass die Box unterm Diagramm liegt und sich von der Höhe her nicht angepasst hat.
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/ac982070-d156-4f1c-89ac-cc87d41cf663)

**Comment by Wolfi913** [comment]
Es dürfte vermutlich an diesem Bug in Jarvis v3.1.8 liegen, also nicht beim Energiefluss-erweitert-Adapter
[https://forum.iobroker.net/post/1073280](url)
Geht scheinbar auch mit der v3.1.9-beta.2 noch nicht
[https://forum.iobroker.net/post/1073312](url)

**Comment by exaware** [comment]
@Wolfi913 stimmt, das bringt es auf den Punkt. Vielen Dank für die Info.
