### ISSUE TITLE
Units not shown after update to 0.0.2-alpha.2

### ISSUE THREAD

**Issue by peer69** [SKB-CGN/ioBroker.energiefluss-erweitert#12]
I have updated to 0.0.2-alpha.2 today. After the update no units are displayed. Values are still shown as expected but without their units. Do I need to activate this somewhere? Units are still defined correctly in the "Source"-Configuration of the element.

**Comment by peer69** [comment]
Already done that. After I hit save a timestamp is displayed for all values until the next value is received. Looks funny for a minute but that's fine, however units don't return. 
I have also tried to delete and reinstall the adapter (did a restore via the configuration object). Rolling back to the former version brings back the units but then the icons are gone.

<img width="1422" alt="image" src="https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/28559804/a9766ff8-0395-4989-be65-c0f411acf032">

**Comment by SKB-CGN** [comment]
Please check, if the option for that timestamp is enabled in element options. Set that to none.

**Comment by peer69** [comment]
Already done that. No impact as well. Data object also shows empty values for units: 

`"unit": {
    "2": "",
    "9": "",
    "16": "",
    "18": "",
    "19": "",
    "26": "",
    "34": "",
    "35": "",
    "41": "",
    "42": "",
    "43": "",
    "44": "",
    "57": ""
  },`

I will try to start with some objects from scratch to see if it works.

**Comment by SKB-CGN** [comment]
Data object is feed from configuration object through Adapter interface.

Did you check, if option is set to "none"?

As you told, the timestamp is written - that is a new function and is not enabled by default.

![Screenshot_20230515_181040_Chrome.jpg](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/83489b74-25cc-4431-9dd0-7a9f0ea8bb8b)

**Comment by peer69** [comment]
Yes. I have checked that. Seems like I messed up my config somehow as the sample config after starting from scratch works as it should. I'll just build from scratch, probably faster than debugging my config - this is an Alpha Version anyway.

**Comment by SKB-CGN** [comment]
You can compare your config with the sample one and check.

**Comment by peer69** [comment]
I have no Idea what might have been the issue - didn't seen to be too different. I have rebuilt my dashboard exactly as it was before and everything works as expected now.

**Comment by SKB-CGN** [comment]
Strange. Do you perhaps have the configuration object, which caused the issue?


Might be possible, to have a look into it.

**Comment by peer69** [comment]
Sure. 
[config.json.txt](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/files/11480899/config.json.txt)

**Comment by SKB-CGN** [comment]
Thanks. Will have a look into it and give some feedback later tomorrow.

**Comment by SKB-CGN** [comment]
Hi,
i am sorry, but i was not able, to reproduce this issue on my test-system.

**Comment by peer69** [comment]
No worries. After rebuilding the dashboard everything seems to be working fine now.
