### ISSUE TITLE
Verbesserungsvorschlag: Manuelles verschieben der Linien ermöglichen

### ISSUE THREAD

**Issue by exaware** [SKB-CGN/ioBroker.energiefluss-erweitert#125]
Um Platz zu sparen, würde ich gerne meine Kacheln versetzt platzieren, siehe rechten Strang im Bild. Dann aber habe ich das Problem das sich die Linien überkreuzen. Wenn man die Linien auch von Hand verschieben könnte, könnte ich es wie im linken Strang realisieren.

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/4997b277-8720-4c68-8553-ca1b4d87a7dc)

**Comment by SKB-CGN** [comment]
Die Linien werden automatisch berechnet. Ein manuelles verschieben ist nicht vorgesehen.
