### ISSUE TITLE
Ordner in Objekten als Datenpunkt anstatt Ordner

### ISSUE THREAD

**Issue by Karacho22** [SKB-CGN/ioBroker.energiefluss-erweitert#128]
Wenn ich bei meinem Mercedes einen Datenpunkt „Ladestand“ erstellen will, bleibe ich mitten im Objektbaum hängen, da aus dem Ordner „mit der Fahrgestellnummer“ einen „Datenpunkt“ wird und ich dann nicht weiterkomme.
Bei meinem Mini ist das kein Problem

Ernergiefluss Mercedes
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/154093396/1ce359af-9667-4f9c-8cb2-155f1c5a5c22)

Iobroker mercedes
 ![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/154093396/1c99c153-5d93-4f22-9f40-0b3857290ab5)

Energiefluss MINI
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/154093396/fc3a00f6-d62f-4c9b-9c35-c58d28f2338c)

**Comment by SKB-CGN** [comment]
Von welchem Typ ist denn der 'Ordner' des Mercedes?

Mir scheint, als wenn der zugehörige Adapter für Struktur falsch erstellt.

**Comment by Karacho22** [comment]
Mercedes: Typ State
MIni: Typ Device

**Comment by SKB-CGN** [comment]
Type State ist falsch.
Bitte manuell auf Typ Channel oder Folder ändern.

Wird der andere Adapter falsch angelegt haben.

**Comment by Karacho22** [comment]
Wie kann man den manuell ändern?

**Comment by SKB-CGN** [comment]
Expertenansicht (Kopf), dann auf den Stift bei dem Ordner und dort abändern.

**Comment by Karacho22** [comment]
Funktioniert!
Auf Device abgeändert.
Danke.
