### ISSUE TITLE
Einbindung von HTLM-Seiten

### ISSUE THREAD

**Issue by Elektrofix-OL** [SKB-CGN/ioBroker.energiefluss-erweitert#132]
Ich wollte unter dem Energieflussadapter eine HTML-Seite von Grafana anzeigen lassen, für den Verlauf der letzten 12 Stunden. Leider bekomme ich das nicht hin, eine Seite von Grafana anzuzeigen. Ist diese Funktion überhaupt möglich? in der VIS soll es gehten und der Adapter bassiert doch auf der VIS.

**Comment by SKB-CGN** [comment]
Hallo,
der Adapter basiert nicht auf VIS.

Eine Einbindung von Frames ist nicht vorgesehen. Eine Verlinkung innerhalb von Popups ist allerdings möglich.

**Comment by SKB-CGN** [comment]
Wenn du mitteilst, was du möchtest, kann man dir adäquat helfen.

Grafana kannst du in einem PopupFrame im Energiefluss anzeigen, nach Klick auf ein Element.

Bei Grafana weiss ich nicht, ob dort externe Inhalte funktionieren.

**Comment by Elektrofix-OL** [comment]
Mein Idee ist es ein Dashboard zu haben, die ungefähr so aussieht:
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/723061c2-3f1e-4fa2-bddd-8ad61cbfc450)
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/d0b89f86-30ae-4223-bff9-76dc4dd13767)
Oben habe ich den Energiefluss und unten habe ich die Historie der letzten 12 oder 24 Std. So kann ich alles sehen:
- Garage ist zu (grüner Rand)
- Auto ist nicht angesteckt (Blaue Fläche)
- Steckdosen von 3d-Drucker und SP111 sind aus (weise Fläche)
Es fehlt nur dieser Grafana-Streifen um zu sehen, ob irgend ein Verbraucher Schwierigkeiten macht, oder die Ladung des Akkus und Auto nicht geklappt haben. 

Ich weis das Grafana als Frame eingefügt werden kann, jedoch sind meine HTML-Kenntnisse von 1996.

**Comment by SKB-CGN** [comment]
Dann kannst du ja die Adresse vom Energiefluss bei Grafana einfügen und als frame darstellen.

Grafana in Energiefluss funktioniert nicht, da keine Frames vorgesehen sind.

Nur Popups oder Links werden vom Energiefluss unterstützt.

**Comment by Elektrofix-OL** [comment]
Funktioniert nicht auf dem iPad und in Windows ist das ein Balken bei Zahnrad, was ich nicht weg bekomme
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/88c51b3a-cc73-48b7-bc06-864d1913a3b5)

**Comment by SKB-CGN** [comment]
Die Anzeige im normalen Browser funktioniert doch, oder?

Wo sollte da jetzt der Fehler beim Adapter liegen?

**Comment by Elektrofix-OL** [comment]
Ja, diese Anzeige funktioniert auf Windows, auf iOS ist nicht das Problem des Adapter.
Nur ist unten im Frame links vom Zahnrad beginnend ein weißer Strich nach rechts, der kommt vom Adapter. Kann der mit css abgeschaltete werden?

**Comment by SKB-CGN** [comment]
Wenn die Seite des Adapters im Browser normal gezeigt wird, im Frame aber nicht, liegt es nicht an der Seite des Adapter.

**Comment by Elektrofix-OL** [comment]
ich habe noch einmal in iOS-Safari und Windows-GogelCrome geschaut: beide machen untern einen hellen Rand:
Safari wenn ich nach oben wische kommt er zum vorscheinen: 
![IMG_0657](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/cb0c136e-9cd9-4148-8e27-f961db1544eb)
Bei GoogelCrome ist er sofort da: 
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/a40ca378-e1ac-48e5-b593-56bc29574ffd)
Im CSS vom Adapter habe ich diese Zeilen eingetragen, um den Hintergrund Dunkel zu bekommen:
`#svg_display {
background-color: rgb(20,20,20);
border: none;
}
/* Icons for Battery */`
So wie ich das sehe, ist kommt es von Adapter. Es kann auch sein, das etwas in den CSS Einstellung fehlt.

**Comment by SKB-CGN** [comment]
So, wie ich das sehe, nutzt du CSS falsch.

Du setzt den Hintergrund des Bildes auf schwarz und den Rest lässt du weiss.

Dadurch kommt der weiße Balken zustande.

Statt svg_image - HTML, Body nutzen.

**Comment by Elektrofix-OL** [comment]
Danke, jetzt passt es. Mein Problem ist damit erl.
