### ISSUE TITLE
PV-Wert negativ führt zu Fehlern

### ISSUE THREAD

**Issue by Elektrofix-OL** [SKB-CGN/ioBroker.energiefluss-erweitert#133]
**Describe the bug**  
Wenn die PV keine Sonne mehr bekommt, gibt Sie den Wert -2147483648W aus

**To Reproduce**  
Wert kommt vom IoBroker über Modbus, jeden Tag wenn die Sonne untergeht

**Expected behavior**  
der Adapter sollte werte unter 0 aus der Erzeugung von PV ingnorieren

**Screenshots & Logfiles**  
Alter Energieflussadapter V3.6.0
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/36ce9b41-989a-455f-810f-20d0c0f359b2)
neuer Energeiflussadapter erweitert V0.1.0
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/c1cd45aa-c8b4-4a77-a30f-00f40aff2db0)
alle beide greifen auf den gleich Datenpunkt zu
Die Berechnung der Verbrauches ist dann auch falsch und verbessert sich nicht, wenn die diese Datenpunkt aus der Berechnung herausnehme. Es schein so, das die Berechnung des Verbrauchs unbedingt einen Datenpunkt haben will

**Comment by SKB-CGN** [comment]
Der Adapter stellt alle Werte dar, da auch negative Werte von der PV kommen können.
Dies ist kein Fehler.

Möchtest du nur positive Werte haben, stell den Schwellenwert des Elements auf 0 oder 1. Dann wird alles überhalb 0 oder 1 angezeigt.

**Comment by Elektrofix-OL** [comment]
jo, Schwellenwert ist schon auf 1, keine Äanderung, was übersehe ich?
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39242936/a9a1c553-4a10-478e-acd1-c58cd09cd211)
Wenn ich die Berechnung auf Auto stelle, werde -2GW angezeigt

**Comment by SKB-CGN** [comment]
Gucke ich noch mal rein.

**Comment by SKB-CGN** [comment]
Bei diesem Wert kann ich keine Anpassungen vornehmen, da der Schwellenwert sowohl für positiv als auch für negativ greift.
Heisst also dein Modbus bringt diesen "Fehler" mit dem falschen Wert.
Der Adapter schaut sich den Wert an, wandelt ihn in positiv, damit korrekt gerechnet wird - und somit ist dein -241xxx in positiv 241xxx größer als 1 und wird dementsprechend angezeigt.
Eine Erzeugung kann halt nicht soweit negativ sein. Entweder wird etwas erzeugt (>0W oder eben <0W) oder eben nicht (0W).
Hier müsstest Du dann eigene Anpassungen vornehmen.
