### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by StefanRied** [SKB-CGN/ioBroker.energiefluss-erweitert#14]
Hi, 
vielen Dank für's teilen. Echt klasse Arbeit!
Kein Bug, sondern eine Anregung.
Ich habe die meisten VIS Designs auf Material Design basiert, damit auch die Dark-Mode Umschaltung geht.
Hier könnte man sich vielleicht einige Arbeit in dem EnergieFluss Adapter sparen, indem man einfach auf das Material Design Schema verweist, anstelle Farben neu zu definieren. Dann würde auch die Dark-Mode Umschaltung konsistent funktionieren.
LG
Stefan

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung.

Der Adapter verwendet sein eigenes Design-Schema - wenn ich nun die Material Design Styles hinzunehme, wird dies auch etwas größer und benötigt mehr Ladezeit.
Der Darkmode ist noch nicht ganz fertig - daher sieht er noch so aus, wie er aussieht. Stelle ich aber noch fertig.

**Comment by StefanRied** [comment]
besten Dank.
Der die erweiterte Version ist Mega!
