### ISSUE TITLE
Datenquelle Berechnungen Multiplizieren möglich?

### ISSUE THREAD

**Issue by fletch247** [SKB-CGN/ioBroker.energiefluss-erweitert#141]
Hi,

zunächst erstmal dickes Lob für den Adapter! Wirklich schick!
Einen Featurewunsch hätte ich: 
Ist es möglich bei Berechnungen in den erweiterten Einstellungen einer Datenquelle das Multiplizieren zu ermöglichen?
Hintergrund: der Adapter für den PV Akku liefert nur Spannung und Stromstärke, ich müsste mir die Anzeige in Watt also berechnen.

Vielleicht ist das ja möglich.
Vielen Dank und Grüße!

**Comment by SKB-CGN** [comment]
Verstehe gerade noch nicht, was Du möchtest.

Was möchtest du denn dort multiplizieren?
Und mit was?

**Comment by fletch247** [comment]
Sorry, es hat drei mal den Text abgesendet obwohl ich noch nicht fertig war mit schreiben. Jetzt sollte es Sinn ergeben oben :D

**Comment by SKB-CGN** [comment]
Solche Dinge kann man relativ einfach mit Blockly oder Javascript erstellen.

Wenn Daten-Punkt a oder b geändert, dann multipliziere a mit b und schreibe es in Daten-Punkt c.

Dazu bedarf es keiner Erweiterung des Adapters.

**Comment by fletch247** [comment]
Jo check ich schon, wär nur praktisch weil addieren und subtrahieren kann man da ja schon.

Schade aber trotzdem danke. Auch für die schnelle Antwort.

**Comment by SKB-CGN** [comment]
Subtrahieren und Addieren macht ja auch Sinn, wenn man die Werte passend haben möchte.

Multiplizieren gehört ja mehr zum "Rohwert" des Wertes.

Klar kann der Adapter W zu kW und umgekehrt, aber solche Berechnungen sind ja - wie gesagt - einfach selber per Blockly und Javascript zu meistern.

**Comment by Chris25122** [comment]
> Jo check ich schon, wär nur praktisch weil addieren und subtrahieren kann man da ja schon.
> 
> Schade aber trotzdem danke. Auch für die schnelle Antwort.

Mit einem Override sollte das gehen. 
1.
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/48753907/09fabf0c-c2f5-43c5-97e7-3d75488df853)

2.
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/48753907/722291c8-31a6-40fe-af3a-abe51998b0fa)
Die zweite Klammer gibt hierbei die Nachkommastelle an.

**Comment by SKB-CGN** [comment]
Auch in einem Override kann man keine 2 Datenpunkte multiplizieren, da nur der Wert aus einem Datenpunkt herangezogen wird.

**Comment by Chris25122** [comment]
So wie ich es verstanden habe will er nur aus kW in W umrechnen, somit sollte das klappen :)
