### ISSUE TITLE
Datenquelle wird nicht gelöscht

### ISSUE THREAD

**Issue by HC-Hofer** [SKB-CGN/ioBroker.energiefluss-erweitert#145]
Hallo.

Mir ist aufgefallen das wenn ich eine Datenquelle (die nicht mehr verwendet wird) lösche und dann auf "speichern und schließen" wird sie nicht gelöscht und taucht wieder auf.
Diese ist auch im Log ersichtlich.

  <details>
    <summary><u>Bild: Datenquellen vorher</u> (<i>click to expand</i>)</summary>
    

![Datenquellen_vorher](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/134226058/34bc3d99-a8b0-40b2-90a1-222dcdca1c39)

  </details>

  <details>
    <summary><u>Bild: Datenquellen nach löschen</u> (<i>click to expand</i>)</summary>
    

![Datenquellen](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/134226058/e1f7d26d-d564-473d-b0eb-4a28f76fc265)

  </details>

  <details>
    <summary><u>Bild: Log nach speichern</u> (<i>click to expand</i>)</summary>
    

![Log](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/134226058/ba95d9c6-f056-4152-a44f-996fd5123640)

  </details>

**Comment by SKB-CGN** [comment]
Danke für den Hinweis.

Habe ich bereits auf der Liste. Kommt bei der nächsten Version mit.

Es gibt dann eine Benachrichtigung hier, wenn die Version herauskommt.

**Comment by SKB-CGN** [comment]
Bitte die Version 03.0 von hier einmal installieren und dann das Issue schließen, wenn die gewünschte Funktion läuft!

Danke! :-)

**Comment by gbackus** [comment]
Das Löschen der Datenquellen funktioniert jetzt in v 3.0.0 bei mir. Danke sehr.

**Comment by SKB-CGN** [comment]
> Das Löschen der Datenquellen funktioniert jetzt in v 3.0.0 bei mir. Danke sehr.

Danke für die Rückmeldung!

**Comment by HC-Hofer** [comment]
Funktioniert 

Danke ;-)
