### ISSUE TITLE
Datenpunkte bereitstellen, ob die Batterie via Netz oder Produktion geladen wird

### ISSUE THREAD

**Issue by michiproep** [SKB-CGN/ioBroker.energiefluss-erweitert#148]
(This a question - not a bug)
How does this adapter know (or how should it be configured) if the battery gets charged "by production" or "by grid"?
I have a screenshot of the old adapter but I cannot seem to get this working on the new one.
Thanks...
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/12296115/16d127a5-487a-481d-a651-3dfd36530460)

**Comment by SKB-CGN** [comment]
Hi,
du benötigst einen Daten-Punkt jeweils für die Ladung per Solar und 1 Daten-Punkt für Ladung per Netz. Diese kannst du dann den Linien zuweisen.

Da der Adapter anders aufgebaut ist und es zuviele Eventualitäten gibt, kann ich die automatische Berechnung bzw. die Anzeige nicht mehr automatisieren.

**Comment by michiproep** [comment]
Danke für die schnelle Antwort.
Ja, das wäre eine gute Idee: Wenn man schon unter "Berechnung" die wichtigen Datenpunkte hinterlegt, wäre es gut wenn dann auch alle sinnvollen Datenpunkte rauspurzeln, nicht nur der Verbrauch selbst.
Dabei ist mir noch aufgefallen, dass unter Berechnung die beiden Datenpunkte Netzbezug und Einspeisung verpflichtend sind. Bei mir (und auch im alten Adapter) konnte man dafür einen einzigen Datenpunkt hinterlegen, der ggf. positiv oder negativ ist.

**Comment by michiproep** [comment]
ah, ok. Das war mir nicht klar.
Nur zur Sicherheit: Ich hinterlege also bei beiden den selben Datenpunkt und sag dann jeweils ob er positiv oder negativ ist?

**Comment by SKB-CGN** [comment]
Ganz genau

**Comment by michiproep** [comment]
Alles klar. Danke.
Jetzt nur noch die Frage: Soll ich meine eigenen Datenpunkte jetzt berechnen oder planst du das zu machen. Weil dann wart ich einfach...

**Comment by SKB-CGN** [comment]
Ich habe es auf die Liste gesetzt.
Wann ich dazu komme, kann ich allerdings nicht sagen.
Auch kann's beim Entwickeln passieren, das es nicht realisierbar bzw. sehr aufwendig ist - dann muss ich schauen, wie es konfigurierbar bleibt.

**Comment by SKB-CGN** [comment]
Ich denke, ich bin auf dem Weg, eine Lösung dafür zu haben.

Wenn ich dich richtig verstanden habe, möchtest Du ja wissen, ob die Batterie per Netz oder Solar geladen wird.

Ich schaue, das ich 2 neue Datenpunkte anbiete, die genau diese Werte beinhalten.

Wäre das etwas, was deiner Anfrage entspricht?

**Comment by SKB-CGN** [comment]
> Hallo,
in der neuen Version 0.4.0 wurde dein Problem behoben. Bitte diese Version installieren und testen, ob der Fix erfolgreich ist.

Wenn ja, bitte das Issue schließen. 

Vielen Dank 😉

**Comment by michiproep** [comment]
so ganz funktioniert es noch nicht. Ich bekomm komische Werte, zB "von Netz = 300000W"
Das hier sind meine Einstellungen:
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/12296115/ee7a34b4-cede-4fab-b39a-8f75b426cd24)

**Comment by michiproep** [comment]
Aber ganz ehrlich: Vielleicht sollten wir das lassen. Das stimmt so eh nie 100% und ist eigentlich auch nur ein nettes Feature.
Wenn ein Wechselrichter seine Batterie schon vom Netz lädt, dann sollte er auch einen Datenpunkt mitbringen und das selbst anzeigen.
Von mir aus können wir das schließen.

**Comment by michiproep** [comment]
Hab doch noch ein wenig getestet... Das Problem scheint ein Mix aus W und kW Datenpunkten zu gewesen zu sein.
Ich komm noch nicht ganz dahinter, wie die Faktoren bzw. sich die Switches "Quelle ist kW" verhalten

**Comment by SKB-CGN** [comment]
Stell die Daten-Quellen mal mit den richtigen Faktoren ein und lass die Schalter bei der Berechnung mal auf No stehen.

Denn, wenn du in den Daten-Quellen schon einen kW Faktor hast und dann nochmal kW nimmst, dann wird's ja 1000fach mehr 😉

**Comment by SKB-CGN** [comment]
Wie ist denn hier der aktuelle Stand?

**Comment by SKB-CGN** [comment]
Bei mir werden die Datenpunkte passend gefüllt.
Ist dies bei dir denn auch der Fall?

**Comment by michiproep** [comment]
Ja, wenn man nicht mit unterschiedlichen W und kW Datenpunkten arbeitet scheint es zu klappen

**Comment by SKB-CGN** [comment]
Ich nehme die Schalter noch wieder raus, da der Faktor ja in den Daten-Quellen angegeben wird. Somit passt das dann.

Die Faktoren passen so - kW ist Faktor 1000 und Watt Faktor 1, da die Grundrechnung in Watt erfolgt.

Heißt, wenn du die Ladung via Grid oder Solar in den Daten-Quellen angibst, ist es Faktor 1 und du musst keine Schalter für kW in der Berechnung betätigen.
