### ISSUE TITLE
Verbesserungsvorschlag Animation der Flussrichtung in Abhängigkeit des Wertes Ändern

### ISSUE THREAD

**Issue by L1brTy** [SKB-CGN/ioBroker.energiefluss-erweitert#15]
Erstmal ein Lob an den coolen Adapter !

Man könnte noch übersichtlichere Visualisierungen bauen, wenn die Flussrichtung der Animation  in Abhängigkeit der Variable die Richtung ändern könnte.

zusätzlich wäre ein Grenzwert schick, ab wann die Visualisierung anfängt schön.

Beispiel Batterie:

P > Ogrenz  (Laden) -> Flussrichtung zu Akku
P < -Ugrenz (Entladen) -> Flussrichtung von Akku weg

z.B. -30W < P < 30W -> keine Animation

z.B. die Victron Visualisierung finde ich ganz gelungen. Leider nicht so schon flexibel und in Echtzeit.

![Victron](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/57085514/a902cd3c-56ac-447d-96d9-697990493893)

Viele Grüße!

**Comment by SKB-CGN** [comment]
Hallo,
danke für deinen Kommentar.

Du kannst doch Grenzen für den Start der Animation angeben.

Linie anklicken und dort wie folgt:
![2023-06-14 09_25_52-Window](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/b5316915-6451-4347-816b-420ff565ffda)

Die Linien-Umkehr finde ich nicht sinnvoll, da entweder etwas fließt oder nicht - nur nicht von einem Objekt zum Anderen. Außer, bei dem Akku, wenn man nur eine Linie verwenden möchte.

**Comment by L1brTy** [comment]
Hallo, danke für den Hinweis.  mit dem Treshhold! die Linien baue ich dann mal um :).

Viele Grüße

**Comment by SKB-CGN** [comment]
Ich öffne das Issue nochmal, da es ein Zweites dazu gibt. Ich setze mich dann für die nächste Version dran.

**Comment by SKB-CGN** [comment]
Hallo,
konntet ihr die aktuelle Version testen, um zu verifizieren, ob es nun wunschgemäß eingebaut ist? Wenn ja, würde ich Euch bitten, das Issue zu schließen ;)

**Comment by L1brTy** [comment]
Klappt perfekt 👍
