### ISSUE TITLE
Batteriekapazität und Batterie SoC via Datenpunkt berücksichtigen

### ISSUE THREAD

**Issue by gbackus** [SKB-CGN/ioBroker.energiefluss-erweitert#152]
Hello,
if you want to calculate the charging or discharging time correctly, the minimum SOC setting is used. However, this is not dependent on a data source but is permanently parameterized. If this is intentionally changed, it must be re-entered in the energy flow adapter. Here it would be better to refer to a data source.

**Comment by SKB-CGN** [comment]
Such a SOC is not changing constantly. 

Therefore it is entered in the Adapter and not read from a datasource.

I will have a look, how to deal with that.

**Comment by gbackus** [comment]
You are right that the min SOC is not changed all the time. But during the course of the year, it makes sense to raise it in winter and lower it in summer so that the batteries are not always at the same charge level. 
With regards,
ga_ba

**Comment by SKB-CGN** [comment]
Yes, changing it 2 Times a year would be possible, right? 😉

**Comment by gbackus** [comment]
Na ich schätze 10 mal pro Jahr, um den Akku regelmäßig auf einem höheren oder niedrigeren Level zu halten. Den Kommentaren im storion-Forum entnwhme ich, dass dies auch andere so machen um Akkupflege zu betreiben.
Die automatische Berechnung funktioniert ja auch ohne eine Datenquelle. Man muss bei einer Änderung des Min-SOC-Wertes halt daran denken, dass auch in Deinem Energiefluss-Adapter zu machen, da sonst die Berechnugen falsch laufen.
Beste Grüße

**Comment by SKB-CGN** [comment]
Ich schaue hier noch, ob ich den Datenpunkt des SoC anbieten kann.

Sobald dies der Fall ist, gibt es hier eine Benachrichtigung für die entsprechende Version.

**Comment by SKB-CGN** [comment]
Hallo,
in der neuen Version 0.4.0 wurde dein Problem behoben. Bitte diese Version installieren und testen, ob der Fix erfolgreich ist.

Wenn ja, bitte das Issue schließen. 

Vielen Dank 😉

**Comment by gbackus** [comment]
Hallo,
vielen Dank für die Erweiterung des Adapters, die ich installiert habe.
Funktioniert perfekt.
In den Datenquellen müsste für die Batteriekapazität noch die Eingabeeinheit in Wattstunden (Wh) statt W geändert werden.
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126283404/2b7e2146-0f79-4c06-b619-9c30eb69baab)

Beste Grüße

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung!
