### ISSUE TITLE
Automatic conversion W to kWdies ist kein Fehler

### ISSUE THREAD

**Issue by gbackus** [SKB-CGN/ioBroker.energiefluss-erweitert#153]
Hello,
This is not a bug but a wish.
It would be good if the decimal places for the automatic conversion from W to kW could be set separately for both values to keep the display fields smaller. 
We regularly have to deal with watt values in the hundreds, whereby decimal places are rather uninteresting. If, on the other hand, the kW numbers are rounded without decimal places, the display error is in the10 % to 50 % range.
Thank you in advance.

**Comment by SKB-CGN** [comment]
Hattest du dies nicht schon im Forum gefragt?

Dort hatte ich dir doch bereits mitgeteilt, das ich aktuell dabei bin, dies umzusetzen.

**Comment by gbackus** [comment]
Hm, das hatte der User udog im storion-Forum geantwortet. Solltest Du udog sein, dann sorry.
Dann kam eine neue Version, mit der das noch nicht möglich war.
Da dieses Thema nicht in den issues stand, wusste ich jetzt nicht, wie der Stand der Dinge ist.
Aber trotzdem Danke, dass Du Dich des Themas annimmst. 
Ich nutze den Adapter sehr gerne.
Beste Grüße

**Comment by SKB-CGN** [comment]
Okay, wenn du es nicht als Sputnik im ioBroker Forum warst, dann gibt es mehr Interesse daran.

Ist also auf jeden in Arbeit.

**Comment by SKB-CGN** [comment]
Bitte die Version 03.0 von hier einmal installieren und im Wiki schauen, wie sich die Überschreibungen für die Elemente aktivieren lassen und dann das Issue schließen, wenn die gewünschte Funktion läuft!

Danke! :-)

**Comment by gbackus** [comment]
Das Umrechnen von W zu kW mit jeweils veränderten Nachkommastellen funktioniert.
Besten Dank.

**Comment by SKB-CGN** [comment]
Sehr gut.
Danke für die Rückmeldung!
