### ISSUE TITLE
Dublicate elements doesn't work

### ISSUE THREAD

**Issue by exaware** [SKB-CGN/ioBroker.energiefluss-erweitert#155]
I update to version 0.2.1. 
I recognized that the duplicate elements function doesn't work any more. 
Nothing happen if I click on button.
Getting this error:
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/55593493/0d33a25b-d5b4-443c-926a-97e0c2d906e6)

**Comment by SKB-CGN** [comment]
Please install Version from Github, not from NPM. Has been fixed few days ago.

**Comment by exaware** [comment]
You are right. Thank you.
Another question, do you plan to implement a revert function/button?

**Comment by SKB-CGN** [comment]
Revert function is available while changing element properties inside config bar.

**Comment by exaware** [comment]
I mean while changing element position or duplicate operation. In addion a delete function with "Entf" key would be nice.

**Comment by SKB-CGN** [comment]
I will look into that, after the current release I am working on.
