### ISSUE TITLE
Duplizieren nicht möglich

### ISSUE THREAD

**Issue by teletapi** [SKB-CGN/ioBroker.energiefluss-erweitert#156]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Seid einigen Tagen kann ich keine Elemente mehr dublizieren zumindest ist mir das jetzt erst aufgefallen. ich habe 4 Instanzen erstellt.

**Comment by teletapi** [comment]
Es kommt zwar die Meldung Element erfolgreich dupliziert aber es wird kein Dublikat erstellt

**Comment by SKB-CGN** [comment]
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/issues/155
