### ISSUE TITLE
Zu viele Punkte im Element

### ISSUE THREAD

**Issue by jest01** [SKB-CGN/ioBroker.energiefluss-erweitert#160]
Hallo,

das Element enthält trotz Begrenzung auf max. drei deutlich mehr Punkte auf der Linie.
Ich habe die Leistung bewusst niedrig eingestellt, um die Anzahl er Punkte bei ausgeschalteter Heizung zu reduzieren.

MfG

![Element_value](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/46645663/ff2a0ae9-23df-4bf0-95e1-de01f43d6881)
![Flussdiagramm](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/46645663/0f04f629-bdb0-480b-ab83-58d02bed1107)

**Comment by SKB-CGN** [comment]
Dann musst du die Abstände der Animation anpassen, damit nur 3 Punkte erscheinen.

**Comment by jest01** [comment]
wenn ich die Leistung auf 2500 stelle, sind es drei,

**Comment by SKB-CGN** [comment]
Ja, es wird kalkuliert, wie viel maximal auf der Linie sein soll.

Wenn 2500W das Maximale ist, dann ist das der Max Wert.

Steht auch so in der Hilfe!

**Comment by jest01** [comment]
das funktioniert ja auch,
ich begrenze die maximale Anzahl auf 3 Punkte und  stelle eine Leistung von 300W ein,
dann wird bei 50W nur ein Punkt erscheinen.
Aber was passiert dann, wenn die aktuelle Leistung höher als die 300W ist....dann erscheinen mehr als die 3 Punkte

**Comment by SKB-CGN** [comment]
Habe ich über deinem Kommentar erklärt!

**Comment by SKB-CGN** [comment]
Ich stelle das nochmal nach und melde mich zurück.

**Comment by SKB-CGN** [comment]
War tatsächlich ein Fehler, der sich da eingeschlichen hatte.
Bitte die Version 0.3.0 von hier installieren und ggf. das Issue schließen, wenn der Fehler beseitigt ist.

Danke!

**Comment by SKB-CGN** [comment]
Super!

In der neuen Version gibt es auch eine Menge mehr zu entdecken 😉
