### ISSUE TITLE
Linien ausblenden falls keine Energie fließt

### ISSUE THREAD

**Issue by Chris25122** [SKB-CGN/ioBroker.energiefluss-erweitert#161]
Ist es möglich die Linien wie beim normalen Energiefluss Adapter auszublenden falls keine Energie fließt ?
Beim normalen Adapter kann man das hier einstellen
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/48753907/dcb700e2-7775-46df-92ca-b0fcdff309ee)

Leider habe ich keine Einstellung Möglichkeit gefunden, die dieser entspricht.
Vielen Dank für die Antwort vorab.

**Comment by SKB-CGN** [comment]
Ja, geht mit Überschreibungen der Linie und etwas Kenntnis in CSS.

Einfach im Wiki schauen.

Das passende CSS Attribut ist dann

display: none;

bzw.

display: inline;

**Comment by Chris25122** [comment]
Ich habe hierfür die Klasse angelegt
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/48753907/48ca1fdf-e507-4101-81b2-ec4b8e961b61)
und im Element testweise allgemein zugewiesen wodurch es immer ausgeblendet werden sollte, das funktioniert leider nicht. Was mache ich falsch ?
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/48753907/378e394a-ea01-44f6-a5b2-868c67ee4b13)

**Comment by SKB-CGN** [comment]
Allgemein ist die Klasse, die immer angewandt wird.

Du möchtest sicher, wenn sie unter Schwelle ist.

Also Schwelle auf 1(ist dann wohl 1 Watt) setzen und die Klasse bei positiv unter Schwelle.

Einfacher geht's halt mit den Überschreibungen.

**Comment by Chris25122** [comment]
Genau das ich teste ob es überhaupt funktioniert hatte ich es erstmal in allgemein gepackt wodurch es immer ausgeblendet werden sollte ( was leider nicht funktioniert ). Im nächsten Schritt wenn allgemein funktioniert hätte ich es ausgeblendet wenn der Wert = 0 ist und somit kein Strom fließt.
Irgendwas stimmt aber noch nicht, da es gar nicht ausgeblendet wird.
Wo trage ich die Überschreibungen ein ? Habe dazu nichts gefunden.

**Comment by SKB-CGN** [comment]
Vielleicht hilft ein ! important hinten dran.

Ansonsten siehst du die Überschreibung in deinem Screenshot 😉

Und die Hilfe dazu im Wiki!

**Comment by Chris25122** [comment]
Important hatte ich schon versucht, leider auch ohne Erfolg.
Die Hilfe zu CSS hatte ich natürlich auch angeschaut, leider ebenfalls ohne Erfolg...

**Comment by SKB-CGN** [comment]
Im Wiki sind genügend Beispiele für Überschreibungen. Wieso sollte es denn bei Anderen klappen?

**Comment by Chris25122** [comment]
Super damit hat es geklappt danke dir !

**Comment by SKB-CGN** [comment]
Wie hast du es nun gelöst?

Vielleicht kann ich das noch mit ins Wiki aufnehmen.

**Comment by Chris25122** [comment]
In der Linie in beiden Überschreibungen das rein geschrieben

{
    "<0": {
        "display": "none"
    }
}

**Comment by SKB-CGN** [comment]
Sollte eigentlich bei der Linie reichen, denn die Animation geht automatisch weg, wenn die Linie nicht dargestellt wird.

Kannst du das noch testen, bitte?

**Comment by Chris25122** [comment]
Ich muss vermutlich beides anpassen da ansonsten sowas raus kommt.
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/48753907/d278216c-0a6a-4b47-819c-10aebe997cd3)
Ich bin gerade noch am testen

**Comment by Chris25122** [comment]
Das Problem taucht anscheinend unabhängig davon ob der Überschreibung an beiden Stellen steht oder nur bei der Linie. Nach einem Refresh wird es richtig angezeigt. Sieht nach einem Bug aus ?

**Comment by Chris25122** [comment]
Damit funktioniert es jetzt wenn man das nur in der Überschreibung für die Linie einträgt:

{
    "<0": {
        "display": "none"
    },
    ">0": {
        "display": "inline"
    }
}

**Comment by SKB-CGN** [comment]
Genau, die Linie muss ja wieder eingeblendet werden, wenn Energie fließt.
