### ISSUE TITLE
Werte von eigenen Datenpunkten werden nicht aktualisiert

### ISSUE THREAD

**Issue by ron2875** [SKB-CGN/ioBroker.energiefluss-erweitert#163]
Hi,
ich nutzte schon länger den Adapter ohne Probleme.

Nach dem Update auf 0.2.1 und nun auch mit 0.3.0 werden meine eigenen Datenpunkte nicht mehr aktualisiert, nur nach dem Speichern genau einmal, dann nicht mehr.

Komischerweise werden Datenpunkte von myenergi aktualisiert.

Liegt es an mir oder ist es ein Bug?

Danke für die tolle Arbeit!

Gruß,
Ron

**Comment by ron2875** [comment]
Genau das passiert eben nicht.
Die Werte der Live Ansicht werden nach dem Speichern einmal aktualisiert und dann nicht mehr, es wird immer der gleiche Wert angezeigt.
Auch Neuinstallation hat nicht geholfen.

**Comment by ron2875** [comment]
zb. hier:
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/142818854/205d2b21-9cde-44c2-93b2-b9c00525998e)

**Comment by SKB-CGN** [comment]
Das sind Datenpunkte, die nicht im Benutzerbereich liegen und ein ACK Flag benötigen.

Eigene Daten-Punkte gehören unterhalb userdata und nicht "irgendwohin".

**Comment by ron2875** [comment]
Ist das der Fehler?
Kann der Adapter diese Punkte dann nicht verwerten?

**Comment by SKB-CGN** [comment]
Natürlich ist das der Fehler.

Im Hauptverzeichnis sind nur Daten-Punkte anderer Adapter, die ihre Werte dort aktualisieren und mit einem ACK belegen.

Daten-Punkte der Benutzer haben unter 0_userdata oder javascript zu liegen - dort werden sie auch ohne ACK verarbeitet.

**Comment by ron2875** [comment]
Danke für die Aufklärung.
Aber ich habe den Adapter zu 100% vorher so genutzt und es hat auch funktioniert.
Nun ja, werde die Punkte verändern und noch mal schauen.
Wie gesagt, vielen Dank für die Aufklärung und die tolle Arbeit.

**Comment by ron2875** [comment]
Genau,
ich berechne und schreibe mit JavaScript.
Habe mich sber ehrlicherweise mit den Stati nie beschäftigt, ein Fehler, wie ich jetzt merke.
Probiere es aus 👍🏻

**Comment by SKB-CGN** [comment]
Am Besten legst du deine Datenpunkte auch unterhalb userdata, denn da gehören sie auch hin.
