### ISSUE TITLE
Probleme beim Einfügen/Ändern von Icons

### ISSUE THREAD

**Issue by sheba-vdf** [SKB-CGN/ioBroker.energiefluss-erweitert#17]
Vielen Dank für die Info, dass es einen neuen Adapter gibt, dies ging an mir vorbei. Ich habe mich gleich ans Werk gemacht und mir die neue VIS gebaut. Dabei viel mir aber ein Problem auf.

Fügt man ein Icon vom Typ "icon-park:solar-energy" ein und möchte dieses anschließend wieder auswählen, wird es nicht dunkel hinterlegt. Wenn man nun einen neuen Typ hinterlegen will oder es löschen, zerschießt es die komplette Ansicht.

<img width="523" alt="Solar-Icon01" src="https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/136894333/aabfb520-24f7-41c0-9eab-59af38e7202b">

<img width="510" alt="Solar-Icon02" src="https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/136894333/f5c77adc-a777-42f9-972f-ee48d45b2e06">

<img width="1469" alt="Gesamtansicht" src="https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/136894333/a16253e9-31a4-401d-93bc-1583c9d1444a">

**Comment by SKB-CGN** [comment]
Verstehe nicht, wie es dort die Ansicht 'zerschießen' sollte.
Das Icon wird über die Liste ausgewählt. Wort eingeben und aus der Liste auswählen. Nur Copy und Paste löst keine Änderung aus.
Werde den Fehler einmal reproduzieren.

Also: Wort eingeben und das Icon aus der Liste wählen.

**Comment by SKB-CGN** [comment]
Hallo,
ich konnte den Fehler inzwischen nachstellen und auch beheben.

In der Version 0.0.2-alpha.8 wurde dieser bereits behoben.
