### ISSUE TITLE
Fehlerhafte Darstellung des Füllrahmen, wenn das Rechteck nicht symmetrisch ist

### ISSUE THREAD

**Issue by booking100** [SKB-CGN/ioBroker.energiefluss-erweitert#172]
Ich habe mein Widget soweit eingerichtet. Leider scheint es einen Darstellungsfehler zu geben. 

Ich möchte gerne, dass abhängig vom Wert, der Umriss entsprechend gefüllt wird. Dies habe ich soweit eingerichtet. Leider wird der Umriss bei mir versetzt zum eigentlichen Umriss angezeigt. Auch scheint dieser eine andere Größe und Breite zu haben. Auch das einfügen eines neuen Rechtecks hat nicht geholfen.

![Screenshot 2024-04-02 163318](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39865973/a870b530-a57c-463f-b160-a1bdb21fac2d)

**Comment by SKB-CGN** [comment]
Wie sind denn die Einstellungen dazu?

**Comment by booking100** [comment]
Ich habe es mit Mozilla Firefox und Microsoft Edge probiert. Bei beiden taucht der gleiche Fehler auf. 
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39865973/88acbe0c-4a0f-49b3-8fd0-9a01f474a80c)
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39865973/e4e90cb7-f391-4d30-b681-02679461c2ed)
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/39865973/b6766796-87e0-4eaa-a42f-e1781ccafc23)

**Comment by SKB-CGN** [comment]
Ah, ich verstehe da Problem.

Das Rechteck ist unterschiedlich in Breite und Höhe, daher ist es falsch ausgerichtet.

Aktuell ist es so, dass das gespiegelte Element, was die Linie steuert, einfach gedreht wird, wenn der Startpunkt anders ist. Dann passt es mit Höhe und Breite natürlich nicht mehr 😉

Stelle ich nach und behebe es natürlich!

**Comment by SKB-CGN** [comment]
Hallo,
in der neuen Version 0.4.0 wurde dein Problem behoben. Bitte diese Version installieren und testen, ob der Fix erfolgreich ist.

Wenn ja, bitte das Issue schließen. 

Vielen Dank 😉

**Comment by SKB-CGN** [comment]
Wie ist denn hier der aktuelle Status?
Wurde der Fehler durch die neue Version behoben?
