### ISSUE TITLE
Gesamte Produktion in Datenpunkt zur Verfügung stellen

### ISSUE THREAD

**Issue by OnkelFD** [SKB-CGN/ioBroker.energiefluss-erweitert#173]
Hallo wäre es möglich die einzelnen Berechnungen auch in den Objekten abzulegen?
Eine Gesamtberechnung von Erzeugern zum Beispiel.

Oder dass sich die Farbe ändert wenn der Wert das Vorzeichen ändert zum Beispiel bei einer Akku Ladung/Entladung.

danke für die Tolle Arbeit

Gruß Frank

**Comment by SKB-CGN** [comment]
> Hallo wäre es möglich die einzelnen Berechnungen auch in den Objekten abzulegen? Eine Gesamtberechnung von Erzeugern zum Beispiel.

Welche Berechnungen? Die Werte liegen ja bereits vor und werden nur addiert. Dies kann man sicherlich selbst berechnen, oder? :)
> 
> Oder dass sich die Farbe ändert wenn der Wert das Vorzeichen ändert zum Beispiel bei einer Akku Ladung/Entladung.
> 
Die Farben und das komplette Layout lässt sich je Wert anpassen - dazu bitte die Overrides (Überschreibungen) nutzen, wie im Wiki erklärt.

**Comment by OnkelFD** [comment]
Die Berechnung kann man auch anders lösen stimmt schon nur für die Animation der einzelnen Verbindungslinien ist das nicht möglich weshalb eine extra Berechnung gemacht werden muss welche ich so oder so schon in der Oberfläche mache.
zB. die Linie Gesamt PV zu Hausverbrauch (ich verbinde nicht die einzelnen Erzeuger mit dem Hausverbrauch sondern einen Großen)

**Comment by SKB-CGN** [comment]
> Die Berechnung kann man auch anders lösen stimmt schon

Welche? Was wird nun gewünscht?

> nur für die Animation der einzelnen Verbindungslinien ist das nicht möglich weshalb eine extra Berechnung gemacht werden muss

Hier wird ein Datenpunkt angegeben, welcher den Wert zur Animation bereithält. Je nachdem welcher Schwellwert eingestellt ist, wird die Linie animiert oder nicht.

 > welche ich so oder so schon in der Oberfläche mache. zB. die Linie Gesamt PV zu Hausverbrauch (ich verbinde nicht die einzelnen Erzeuger mit dem Hausverbrauch sondern einen Großen)

Und, was is nun der Wunsch für weitere Funktionen?

**Comment by OnkelFD** [comment]
Der Wunsch wäre entweder die Gesamte Produktion welche man in dem Register "Berechnung -> Verbrauch -> Produktion" angibt entweder als Objekt ablegt, oder eine Berechnungsmöglichkeit für die Verbindungslinien.

Gruß Frank

**Comment by SKB-CGN** [comment]
Hallo,
in der neuen Version 0.4.0 wurde dein Problem behoben. Bitte diese Version installieren und testen, ob der Fix erfolgreich ist.

Wenn ja, bitte das Issue schließen. 

Vielen Dank 😉

**Comment by OnkelFD** [comment]
Vielen Dank das Passt soweit 🤗

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung!
