### ISSUE TITLE
Adapter läuft nicht (leuchtet rot)

### ISSUE THREAD

**Issue by Fagott01** [SKB-CGN/ioBroker.energiefluss-erweitert#177]
Servus! Ich bin kein Fachmann, deshalb in einfachen Worten. Bei mir läuft der Adapter nicht. In ioBroker leuchtet es rot. Ich habe auf Empfehlung den alten Adapter (Energiefluss 3.6.0) erneut installiert, es löste das Problem nicht. 

aktuelle Node-Version 18.20.01
NPM 10.5.0

Für eine Hilfe wäre ich deshalb sehr dankbar. 

**Additional context**  
![IMG_3167](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/166388347/8b784307-37c2-4b3a-ab1b-29a926a01945)

**Comment by SKB-CGN** [comment]
Einfach nochmal installieren.
Da gab es wohl ein ioBroker Problem.

**Comment by Fagott01** [comment]
Habe schon mehrfach versucht. Trotzdem läuft er nicht. Gesendet mit der GMX iPad AppAm 08.04.24 um 12:39 schrieb SKB-CGN
                
            
            
                
                    Von: "SKB-CGN" ***@***.***>Datum: 8. April 2024An: "SKB-CGN/ioBroker.energiefluss-erweitert" ***@***.***>Cc: "Fagott01" ***@***.***>,"Author" ***@***.***>Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Adapter läuft nicht (leuchtet rot) (Issue #177)
                
                
Einfach nochmal installieren.
Da gab es wohl ein ioBroker Problem.

**Comment by Fagott01** [comment]
Besten Dank! Ich konnte das Problem beheben. Gesendet mit der GMX iPad AppAm 08.04.24 um 13:01 schrieb SKB-CGN
                
            
            
                
                    Von: "SKB-CGN" ***@***.***>Datum: 8. April 2024An: "SKB-CGN/ioBroker.energiefluss-erweitert" ***@***.***>Cc: "Fagott01" ***@***.***>,"Author" ***@***.***>Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Adapter läuft nicht (leuchtet rot) (Issue #177)
                
                
Adapter löschen, ioBroker stoppen, starten und dann erneut installieren.

**Comment by SKB-CGN** [comment]
Wäre doch prima, wenn du beschreibst, wie.

**Comment by Fagott01** [comment]
So wie es empfohlen wurde: Adapter gelöscht, ioBroker neugestartet, Adapter neu installiert… Nochmals besten Dank!Gesendet mit der GMX iPad AppAm 08.04.24 um 15:06 schrieb SKB-CGN
                
            
            
                
                    Von: "SKB-CGN" ***@***.***>Datum: 8. April 2024An: "SKB-CGN/ioBroker.energiefluss-erweitert" ***@***.***>Cc: "Author" ***@***.***>,"Fagott01" ***@***.***>Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Adapter läuft nicht (leuchtet rot) (Issue #177)
                
                
Wäre doch prima, wenn du beschreibst, wie.
