### ISSUE TITLE
Adapter stürzt ab, wenn Datenpunkt gelöscht wird, der zur Berechnung von Batterie oder Verbrauch genutzt wird

### ISSUE THREAD

**Issue by Fagott01** [SKB-CGN/ioBroker.energiefluss-erweitert#178]
Irgendwie ist die Instanz in ioBroker permanent instabil und deutet auf einen Fehler im Code hin. Ich muss den Host immer wieder neu starten, damit die Instanz läuft. Hat jemand gleiche Probleme? Hat jemand gleiche Probleme, oder evtl. eine Lösung?

**Comment by SKB-CGN** [comment]
Dann müssten ja Fehler im Log zu sehen sein.

So pauschal läuft die Instanz bei über 7000 Installationen tadellos.

**Comment by Fagott01** [comment]
Leider bekomme ich im Log nichts aussagekräftiges, womit ich etwas anfangen könnte… Bereits bei der Erstinstallation hatte ich Problem mit der Instanz. Jetzt läuft sie zwar aber mehr schlecht als recht. Ist ein Update in der nächsten Zeit geplant?

Vg

Am 13.04.2024 um 13:51 schrieb SKB-CGN ***@***.***>:


Dann müssten ja Fehler im Log zu sehen sein.

So pauschal läuft die Instanz bei über 7000 Installationen tadellos.

**Comment by SKB-CGN** [comment]
Im Log steht aber, wo der Fehler ist.

Demnach kann ich ohne Log und Fehlermeldung nichts anfangen.

**Comment by SKB-CGN** [comment]
Wenn du die Instanz startest, dann erscheint direkt eine rote Schrift im Log.

Den Text drum herum brauche ich.

Oder oben links im Log den Filter auf 'energiefluss-erweitert' stellen, dann erscheinen die Meldungen vom aktuellen Tag.

Sind keine Meldungen da, lag kein Fehler vor.

**Comment by Fagott01** [comment]
Das habe ich jetzt. Das scheint in Ordnung zu sein. Irgendwann ist es wieder instabil…Gesendet mit der GMX iPad AppAm 13.04.24 um 14:41 schrieb SKB-CGN
                
            
            
                
                    Von: "SKB-CGN" ***@***.***>Datum: 13. April 2024An: "SKB-CGN/ioBroker.energiefluss-erweitert" ***@***.***>Cc: "Author" ***@***.***>,"Fagott01" ***@***.***>Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Instabile Instanz (Issue #178)
                
                
Wenn du die Instanz startest, dann erscheint direkt eine rote Schrift im Log.
Den Text drum herum brauche ich.
Oder oben links im Log den Filter auf 'energiefluss-erweitert' stellen, dann erscheinen die Meldungen vom aktuellen Tag.
Sind keine Meldungen da, lag kein Fehler vor.

**Comment by SKB-CGN** [comment]
Wenn dann irgendwann der Fehler auftritt, wirst Du ja Einträge bekommen.

Ohne die kann ich nichts machen.

**Comment by Fagott01** [comment]
Servus,

hier kommen die Infos.

￼

Am 13.04.2024 um 15:19 schrieb SKB-CGN ***@***.***>:


Wenn dann irgendwann der Fehler auftritt, wirst Du ja Einträge bekommen.

Ohne die kann ich nichts machen.

**Comment by SKB-CGN** [comment]
Und, wo sind die Infos?

Es wäre echt prima, wenn du deine Antworten nicht per Email, sondern in GitHub einträgst.

**Comment by Fagott01** [comment]
Eigentlich habe ich diese als Bild angehängt. In der Anlage sende ich das Bild nochmals. VgGesendet mit der GMX iPad AppAm 14.04.24 um 10:38 schrieb SKB-CGN
                
            
            
                
                    Von: "SKB-CGN" ***@***.***>Datum: 14. April 2024An: "SKB-CGN/ioBroker.energiefluss-erweitert" ***@***.***>Cc: "Fagott01" ***@***.***>,"Author" ***@***.***>Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Instabile Instanz (Issue #178)
                
                
Und, wo sind die Infos?
Es wäre echt prima, wenn du deine Antworten nicht per Email, sondern in GitHub einträgst.

**Comment by SKB-CGN** [comment]
Anhänge werden bei GitHub nicht dargestellt.

Nur eingebettete Bilder.

Daher erneut die Bitte, die Beiträge direkt auf GitHub zu erstellen und nicht per Email.

Der Thread sieht aus wie ein Schlachtfeld 😉

**Comment by Fagott01** [comment]
![IMG_3177](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/166388347/2eb3bcae-91f4-4cd8-b126-4209a6a5e571)
Hier ist der Log.

**Comment by SKB-CGN** [comment]
Sieht so aus, als wäre der Datenpunkt für den Prozentsatz der Batterie ungültig.

Diesen bitte kontrollieren. Den Fehler werde ich dann in der nächsten Version abfangen.

**Comment by Fagott01** [comment]
Der Punkt wird ja von der Instanz generiert. Ich habe es gelöscht.- Mal sehen, ob die Instanz jetzt stabil läuft. Sonst melde ich mich nochmals und lade den Log hoch.

**Comment by SKB-CGN** [comment]
Bitte was wird von der Instanz generiert?

Der Prozentsatz des Akkus ist der, den dein Akku zur Verfügung stellt!

**Comment by Fagott01** [comment]
![IMG_3180](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/166388347/217bfc9f-1b5e-412f-a7d4-a1e6c699aff1)

Bei Berechnungen hat man die Möglichkeit einen Datenpunkt zu generieren. Genau das habe ich genutzt. Jetzt habe ich den Datenpunkt gelöscht. Die Instanz ist trotzdem instabil. Anbei log.

**Comment by SKB-CGN** [comment]
Schau dir doch die Fehler einmal an.

Da steht doch schon beschrieben, wo die Fehler liegen.

Anscheinend hast du die Einstellungen für die Batterie nicht richtig ausgefüllt.

**Comment by SKB-CGN** [comment]
Hallo,
in der neuen Version 0.4.0 wurde dein Problem behoben. Bitte diese Version installieren und testen, ob der Fix erfolgreich ist.

Wenn ja, bitte das Issue schließen. 

Vielen Dank 😉

**Comment by Fagott01** [comment]
Servus!

Vielen Dank für die Info. Ich habe den Adapter aktualisiert und lasse es ein paar Tage so laufen. Wenn die Instanz stabil läuft, gebe ich Bescheid.

Noch eine Anregung meinerseits. In der Registerkarte „Berechnung“ habe ich für Batterieladequelle leider nur eine Möglichkeit. Bei mir werden die Batterien gleichzeitig mit zwei Ladegeräten geladen. Es wäre daher sehr willkommen, wenn man auch mehrere Quellen als nur eine angeben kann.

Vg

Alex.

Am 15.04.2024 um 18:15 schrieb SKB-CGN ***@***.***>:


Hallo,
in der neuen Version 0.4.0 wurde dein Problem behoben. Bitte diese Version installieren und testen, ob der Fix erfolgreich ist.

Wenn ja, bitte das Issue schließen.

Vielen Dank 😉

**Comment by SKB-CGN** [comment]
Wie ist denn hier der aktuelle Status?

**Comment by Fagott01** [comment]
Servus!Es läuft mit der neuen Version stabil. Ich wollte mein Ticket schliessen, finde den Antrag jedoch nicht mehr. Hast du schon selbst geschlossen?Wie stehst du zu meiner Anregung wegen zwei Datenpunkte für die Ladung der Batterie vom Stromnetz? Wann könnte man damit rechnen?VgAlex. Gesendet mit der GMX iPad AppAm 21.04.24 um 15:54 schrieb SKB-CGN
                
            
            
                
                    Von: "SKB-CGN" ***@***.***>Datum: 21. April 2024An: "SKB-CGN/ioBroker.energiefluss-erweitert" ***@***.***>Cc: "Author" ***@***.***>,"Fagott01" ***@***.***>Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Adapter stürzt ab, wenn Datenpunkt gelöscht wird, der zur Berechnung von Batterie oder Verbrauch genutzt wird (Issue #178)
                
                
Wie ist denn hier der aktuelle Status?

**Comment by SKB-CGN** [comment]
Deinen Vorschlag stelle ich mal nach hinten, da ich dazu bisher noch keine Anfragen bekommen habe und es somit noch kein anderweitiges Interesse da ist.
