### ISSUE TITLE
Verbesserungsvorschlag: Animation der Flussrichtung in Abhängigkeit des Wertes Ändern

### ISSUE THREAD

**Issue by incase** [SKB-CGN/ioBroker.energiefluss-erweitert#18]
Ja, ich weiss, dass es den Request schon gab. (#15)

(Kurzfassung: Ich fände das ein sinnvolles Feature.)

Du hast da geschrieben, dass Du das nicht sinnvoll findest, außer bei der Batterie, weil sonst ja nur ein Strom fließen oder eben nicht fließen würde. Das stimmt allerdings nur bedingt. Ich habe hier:

PV-Hybridwechselrichter (zwei PV-Stränge, eigene Batterie). Den kriege ich T-förmig sinnvoll abgebildet:

```
PV -> Wechselrichter -> Haus <=> Netz
        |    ^
        v    |
       Batterie
```

Wobei `<=>` für zwei animierte Linien steht für die beiden Richtungen.

Das Problem ist:  Ich habe noch zwei weitere PV-Stränge an einem MPPT, der hängt an einem 48V Strang, an dem auch Batterie (die zweite) und ein Wechselrichter (eigentlich je einer pro Phase) hängt. Und der Wechselrichter wiederum kann sowohl ins Haus einspeisen als auch Strom von dort entnehmen (zum Laden der zweiten Batterie), falls der Hybridwechselrichter mehr Strom erzeugt (und nicht in die bereits volle Batterie einspeisen kann) als das Haus verbraucht. Nur diesen Anlagenteil würde ich dann also wohl so abbilden:

```
PV -> 48V <=> Batterie
      | ^
      v |
  Wechselrichter  <=> Haus <=> Netz
```

Klar kann ich das über jeweils parallele Linien abbilden. Das wird aber relativ unübersichtlich meiner Meinung nach und wäre mit einzelnen Linien, die jeweils in beide Richtungen animiert wären, irgendwie eleganter.

Um ehrlich zu sein, hatte ich schon geschaut, ob ich nicht einen Pull-Request hin bekomme, um das zu implementieren, aber ehrlich gesagt verstehe ich nicht, wie Du die Animationen erzeugst (und diverse andere Anteile des Codes - JavaScript/TypeScript ist eindeutig nicht meine Stärke).

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. Solche Geräte waren mir bisher nicht bekannt.
Sobald ich alle aktuellen Dinge eingebaut habe, die aktuell auf der Liste stehen, kann ich mir um die rückwärts laufenden Animationen kümmern.

Jetzt sind es ja schon 2 Anfragen.

**Comment by erwini** [comment]
Seit version v0.0.2-alpha.8 und aktiviertem Switch "bei neg. Wert rückwärts animieren",  läuft beim 0 Wert eine Animation in rückwärtiger Richtung. Bei mehreren Links probiert.

**Comment by SKB-CGN** [comment]
Habe ich eben getestet. Das tritt bei mir nicht auf.

Sind die Thresholds richtig eingestellt?

**Comment by erwini** [comment]
Thresholds stehen alle auf 0. Aber davon abgesehen habe ich den Zweck der Thresholds noch nicht erfasst. "Unterdrücken von Werten, die 0 anzeigen, aber unter der Haube ev. 0,1 ergeben, was diesen Effekt auslösst?

**Comment by erwini** [comment]
Es ist überall noch "Animation depency" gesetzt. Thresholds auf 0.9 gesetzt. Jetzt scheint es zu tun.

**Comment by SKB-CGN** [comment]
Das sollte der Datenpunkt ja anzeigen, ob der Wert 0 oder 0.9 (0.x) ist.

Die Thresholds sind genau für diesen Zweck da. Ein Standby Verbraucher von 3Watt möchte man ab und an nicht als "Verbraucher" sehen. Dann kann man dies auf 4 Watt stellen.

**Comment by SKB-CGN** [comment]
Hallo,
konntet ihr die aktuelle Version testen, um zu verifizieren, ob es nun wunschgemäß eingebaut ist? Wenn ja, würde ich Euch bitten, das Issue zu schließen ;)

**Comment by incase** [comment]
Sieht für mich korrekt aus. Herzlichen Dank.
