### ISSUE TITLE
Batteriekapazität Datenpunkt nicht auswählbar

### ISSUE THREAD

**Issue by markus397** [SKB-CGN/ioBroker.energiefluss-erweitert#181]
**To Reproduce**  
1. Go to 'config'
2. Click on 'Berechnung'
3. Scroll down to 'Batteriekapazität'
4. Datenpunkt nicht auswählbar, wenn ich die Liste der Datenpunkte öffnen will kommt nur eine leere Zeile wo ich nichts wählen kann. Das gleiche passiert bei entladen bis. Alle anderen Datenpunkte kann ich normal auswählen.

**Versions:**  
 - Adapter version: <0.4.1>
 - JS-Controller version: <5.0.19>
 - Node version: <18.19.0>

**Comment by SKB-CGN** [comment]
Datenquelle unterhalb Datenquelle eingetragen?

**Comment by markus397** [comment]
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126004836/1944723f-f7ba-459c-8bc2-2db09a20413e)

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126004836/e0bf7cfb-4404-48c7-bf14-8d8582dc5704)

**Comment by SKB-CGN** [comment]
Welche Version ist installiert?

**Comment by markus397** [comment]
0.4.1 Problem entstanden mit der Umstellung in 0.4.0

**Comment by SKB-CGN** [comment]
In der Version hat sich dazu nichts geändert.
Wie ist es, wenn du die Datenquelle einträgst, speicherst, die Konfiguration neu aufrufst?

Erscheint es dann?

**Comment by markus397** [comment]
Added: Datasources for the battery calculation now need to be provided via the datasources tab and selected in the calculation tab (!!! Important: !!! This is a major change)
bei 0.4.0 hat das Problem ausgelöst. vorher war der Wert ja manuell einzutragen. Habe dann einen Datenpunkt eingetragen und versucht den zu wählen. Aber es öffnet sich halt keine Liste wie bei allen anderen Punkten. Speichern, Browser wechseln und Adapter Neustart bringen keine Änderung.

**Comment by SKB-CGN** [comment]
Wie ich eben sagte.
Datenquelle eintragen, speichern. Dann die Konfiguration neu aufrufen und Auswählen.

**Comment by markus397** [comment]
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126004836/dcf2c321-9d24-4a9f-bfa8-f654c5fad161

**Comment by SKB-CGN** [comment]
Nochmal, Datenquelle unterhalb Daten-Quellen eintragen. Abspeichern. Seite neu laden und dann?
