### ISSUE TITLE
Eine gelöschte Verbindung lasst sich nicht erneut herstellen

### ISSUE THREAD

**Issue by nobbiman** [SKB-CGN/ioBroker.energiefluss-erweitert#182]
Ich verwende den Adapter "energiefluss-erweitert" 0.4.1 und hatte u.a. eine Verbindung zwischen 2 Elementen hergestellt.
Nachdem ich die Verbindung gelöscht hatte (Verbindung erscheint nicht mehr), wollte ich sie mit einer neuen Konfiguration zwischen den gleichen Elementen wiederherstellen (über den Menüpunkt "Element verbinden").
Daraufhin erhalte ich den folgenden Hinweis: "Diese Verbindung besteht bereits"!
Da die Verbindung nicht sichtbar ist, kann ich die Einstellungen auch nicht verändern - auch mittels Markierung des Urspungsbereiches der Verbindung gelingt das nicht.

Ich habe den Adapter, sowie den Host neu gestartet, das Ergebnis ist das gleiche.

Ich benutze den Adapter seit gestern und habe noch keine explizite Erfahrung, komme aber intuitiv recht gut zurecht, die ersten Werte und Animationen erscheinen bereits. Leider habe ich aber keine Erfahrung in der Scriptprogrammierung, möglicherweise kann man ja den Fehler auf diesem Weg beseitigen, dies ist mir aber nicht möglich.

Wer kann helfen?

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 5.0.19
 - Node version: 18.20.0
 - Operating system: <Windows 10>

**Comment by SKB-CGN** [comment]
Wenn die Linie gelöscht wurde, kann man sie über Verbinden neu erstellen.

Wiederherstellen der Linie geht nur, wenn die Maske noch geöffnet ist, während die Linie gelöscht wurde.

**Comment by nobbiman** [comment]
Danke für den Tipp, mittlerweile habe ich beide Elemente komplett gelöscht und neu erstellt, so konnte ich wieder eine neue Verbindung herstellen.
So klappt es jetzt und meine Darstellung der Energieflüsse läuft sehr anschaulich, tolles Tool!

**Comment by SKB-CGN** [comment]
Prima, wenn dein Problem behoben wurde, dann bitte das Issue schließen.
Danke!

**Comment by nobbiman** [comment]
gelöst

**Comment by Dirk-Ma** [comment]
Hallo,

ich sehe das nicht als gelöst (-:
Ich habe eine Verbindung in der "falschen" Flussrichtung erstellt. Lösche ich diese kann ich auch keine neue erstellen ohne mein Flussdiagramm mehr oder weniger neu zu erstellen.

**Comment by SKB-CGN** [comment]
Was passiert denn, wenn du die Linie löschst, speicherst und diese dann neu erstellst?

**Comment by SKB-CGN** [comment]
Okay, dann scheint es sich verschluckt zu haben.

Ist aber nicht so ein riesen Problem. Für die nächste Version sollte ich diesen Fehler behoben haben.

Aktuell müsste man diese Verbindung manuell entfernen. Das kannst Du entweder selbst erledigen oder ich mache es für dich, wenn du den Inhalt den Datenpunktes hier einstellst oder mir per Mail schickst.

Dazu benötige ich dann die ID der Elemente, zwischen welchen die Verbindung bestand.

**Comment by Dirk-Ma** [comment]
Alles klar, erst mal vielen Dank (-:
Ich versuche es erst mal selbst. Wenn ich nicht klar komme, melde ich mich,

**Comment by SKB-CGN** [comment]
Gut, dann öffne bitte den Text aus dem Datenpunkt ```configuration``` in einem Editor, der nicht direkt Notepad ist, da sonst Formatierungsprobleme auftreten könnten.

Dort schaust du in den Bereichen ```defs```, ```lines``` und ```animations``` nach Bereichen, die jeweils die ID von dem Start und Endelement mit drin haben. Diese Blöcke dann entfernen und den kompletten Text wieder in den Datenpunkt ```configuration``` zurück.

Am Besten vorher diesen Text noch Abspeichern, falls ein Fehler auftritt.

**Comment by Dirk-Ma** [comment]
Habe ich gemacht. Die Verbindung ist anschließend auch nicht mehr zu sehen.
Allerdings besteht auch hier das Problem:

...Nachdem ich die Verbindung gelöscht hatte (Verbindung erscheint nicht mehr), wollte ich sie mit einer neuen Konfiguration zwischen den gleichen Elementen wiederherstellen (über den Menüpunkt "Element verbinden").
Daraufhin erhalte ich den folgenden Hinweis: "Diese Verbindung besteht bereits"!
Da die Verbindung nicht sichtbar ist, kann ich die Einstellungen auch nicht verändern - auch mittels Markierung des Urspungsbereiches der Verbindung gelingt das nicht.
,,,

**Comment by Dirk-Ma** [comment]
Der "Fehler" tritt auch nur auf, wenn ich eine Verbindung von links nach rechts erstellen möchte, von rechts nach links geht.

**Comment by SKB-CGN** [comment]
Also entweder sind die Bereiche nicht korrekt gelöscht worden oder es besteht ein Anderes Problem.

Du könntest die aktuelle Alpha Version darüber installieren. Hier sollte der Fehler behoben sein.

**Comment by Dirk-Ma** [comment]
Hi,

ich habe die "0.5.1-alpha.3" installiert. Ich habe dir mal die Konfiguration angehangen. Es geht um die Verbindung "line_path_7_5" zwischen der Objekt ID 5 und 7

[Energiefluss.txt](https://github.com/user-attachments/files/16371944/Energiefluss.txt)

**Comment by SKB-CGN** [comment]
Also, Du bist aktuell auf einer Alpha Version und der Fehler tritt dennoch auf?

**Comment by Dirk-Ma** [comment]
Ja genau

**Comment by SKB-CGN** [comment]
Wie vermutet sind nicht alle Bereiche gelöscht worden. In Zeile 959 deiner Datei befindet sich noch ein Bereich mit 5 und 7.

**Comment by Dirk-Ma** [comment]
Sorry, was ich angehangen habe, war nicht die von mir geänderte Konfiguration.

Das ist meine geänderte:

[Energiefluss geändert.txt](https://github.com/user-attachments/files/16372207/Energiefluss.geandert.txt)

**Comment by SKB-CGN** [comment]
Dort ist der path in Zeile 959 noch immer vorhanden.

**Comment by Dirk-Ma** [comment]
Ah jetzt ja (-:

Jetzt habe auch ich das verstanden. Jetzt reicht es, wenn ich diesen Teil lösche und ich kann die passende Verbindung erstellen. Danke für die Geduld und schnellen Support.

**Comment by SKB-CGN** [comment]
Kannst Du vielleicht noch Rückschlüsse ziehen, wie dies zustande kam? Dann könnte ich nochmal schauen, ob man hier etwas verbessern kann.

**Comment by Dirk-Ma** [comment]
Hi,

ich habe ja nicht von Anfang an die "0.5.1-alpha.3" installiert. Ich könnte mir vorstellen, dass ich bei einer Vorversion diese Verbindung schon einmal erstellt, dann aber gelöscht habe. Evtl. ist dieser Codeschnipsel damals beim löschen bestehen geblieben.

**Comment by SKB-CGN** [comment]
Ja, in den 0.4er Versionen gab es ein Problem mit dem Löschen. Dadurch wurden Bereiche nicht entfernt. Diese hast Du wahrscheinlich "mitgeschleppt" und nun kam der Fehler auf.

Kannst Du denn jetzt nochmal ein wenig Probieren, wenn Du Verbindungen erstellst und diese löschst, ob es einwandfrei klappt?

**Comment by Dirk-Ma** [comment]
Hi,

werde ich machen. Melde mich im Laufe des Tages (-:

**Comment by Dirk-Ma** [comment]
Vielleicht noch ein Tipp bzw. vielleicht mache ich auch was falsch. Nutze ich einen negativen Wert zu Animation und nutze die Funktion "Wenn der Wert das Vorzeichen geändert hat, animieren Sie ihn in die andere Richtung (umgekehrt)" wird der Wert 0 als positive Zahl interpretiert. D.h. die Animation läuft entweder nach links oder nach rechts, einen "Stillstand" gibt es nicht.

**Comment by SKB-CGN** [comment]
Dann stellst Du hier die Schwelle auf 1 und sie bleibt bei 0 stehen - bei -1 und über +1 läuft die Animation dann.

**Comment by Dirk-Ma** [comment]
(-: so geht das natürlich auch. Danke für den Tipp.

**Comment by Dirk-Ma** [comment]
So, habe jetzt noch mehrfach Verbindungen gelöscht und wieder hergestellt. Bei mir sind keine weiteren Probleme aufgetreten.

Nochmals vielen Dank für den Support (-:

**Comment by SKB-CGN** [comment]
Prima, danke für die Rückmeldung und weiterhin viel Spaß mit dem Adapter ;)
