### ISSUE TITLE
Datenpunkte für Batteriekapazität und Prozent sind ab Version 0.4.0 anzugeben

### ISSUE THREAD

**Issue by SKB-CGN** [SKB-CGN/ioBroker.energiefluss-erweitert#186]
Hallo,
kurzes Feedback zum letzten Release. 
Nach dem Update fehlen in der Berechnung die Kapazität und die Entladung bis %. Hier sind keine Eingaben mehr möglich. 

Grüße Marco

_Originally posted by @bikerbiker12 in https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/issues/185#issuecomment-2074331610_

**Comment by SKB-CGN** [comment]
@bikerbiker12 Wenn deine Batterie die Datenpunkte nicht im ioBroker bereitstellt, erstellt du dir diese selbst und gibst die entsprechenden Werte ein. Dann erstellst du die 2 neuen Datenpunkte im Adapter. Fertig 😉

**Comment by bikerbiker12** [comment]
Das ist soweit verstanden und hatte ich schon gemacht. Allerdings kann ich in der Registerkarte "Berechnung" die Datenquelle nicht auswählen und zuweisen. Es kommt die Meldung "keine Option" bei Klick in "Batteriekapazität" und "Entladung bis %"
Die Datenquelle ist geprüft und ist OK

Mit freundlichen Grüßen

Marco Matterne
________________________________
Von: SKB-CGN ***@***.***>
Gesendet: Mittwoch, 24. April 2024 11:10
An: SKB-CGN/ioBroker.energiefluss-erweitert ***@***.***>
Cc: Marco Matterne ***@***.***>; Mention ***@***.***>
Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Datenpunkte für Batteriekapazität und Prozent sind ab Version 0.4.0 anzugeben (Issue #186)


@bikerbiker12<https://github.com/bikerbiker12> Wenn deine Batterie die Datenpunkte nicht im ioBroker bereitstellt, erstellt du dir diese selbst und gibst die entsprechenden Werte ein. Dann erstellst du die 2 neuen Datenpunkte im Adapter. Fertig 😉

**Comment by SKB-CGN** [comment]
Was heißt "Keine Option"?

Bitte einen Screenshot zeigen.

**Comment by SKB-CGN** [comment]
Screenshots bitte bei GitHub einstellen.
Per Email Antwort geht das nicht!

**Comment by bikerbiker12** [comment]
![IMG_0009](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126656972/0a8c7b85-0b5a-4868-a88a-13671bed6781)

**Comment by SKB-CGN** [comment]
Bitter hier mal einen Upload des Adapters durchführen. Dort sind eigentlich Select Boxen.

**Comment by bikerbiker12** [comment]
Wenn ich eine neue Instanz installiere, dasselbe Problem!

**Comment by SKB-CGN** [comment]
https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de#Uploadvon_Adapterdateien

**Comment by bikerbiker12** [comment]
Erledigt

**Comment by SKB-CGN** [comment]
Wenn's erledigt ist, bitte das Issue schließen.

**Comment by SKB-CGN** [comment]
Rufst du die Konfig neu auf und klickst dann auf Berechnung? Der Klick auf Berechnung muss zwingend erfolgen.

Erst dann werden die Boxen gefüllt.

**Comment by bikerbiker12** [comment]
Ja genau so! Hab auch die Instanz mal neugestartet und bin dann wieder rein. In allen anderen Feldern könnte ich die beiden Datenpunkte auswählen, sowie auch alle anderen!



Von: SKB-CGN ***@***.***>
Gesendet: Mittwoch, 24. April 2024 20:26
An: SKB-CGN/ioBroker.energiefluss-erweitert ***@***.***>
Cc: Marco Matterne ***@***.***>; Mention ***@***.***>
Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Datenpunkte für Batteriekapazität und Prozent sind ab Version 0.4.0 anzugeben (Issue #186)


Rufst du die Konfig neu auf und klickst dann auf Berechnung? Der Klick auf Berechnung muss zwingend erfolgen.

Erst dann werden die Boxen gefüllt.

**Comment by SKB-CGN** [comment]
Irgendwo liegt da ein Fehler in deiner Installation vor.

Vielleicht mal ein "iob fix" auf der Konsole ausführen.

Und danach ein "iob Upload energiefluss-erweitert"

**Comment by bikerbiker12** [comment]
Kam eigentlich erst mit dem Update auf das aktuelle Release. Vorher lief der Adapter einwandfrei.
Das iob fix führe mal nicht aus, da alles andere sauber läuft. Ist mir das Risiko zu hoch!



Von: SKB-CGN ***@***.***>
Gesendet: Mittwoch, 24. April 2024 21:07
An: SKB-CGN/ioBroker.energiefluss-erweitert ***@***.***>
Cc: Marco Matterne ***@***.***>; Mention ***@***.***>
Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Datenpunkte für Batteriekapazität und Prozent sind ab Version 0.4.0 anzugeben (Issue #186)


Irgendwo liegt da ein Fehler in deiner Installation vor.

Vielleicht mal ein "iob fix" auf der Konsole ausführen.

Und danach ein "iob Upload energiefluss-erweitert"

**Comment by SKB-CGN** [comment]
Hast du über GitHub nochmal installiert?

Aktuell weiss ich leider keine andere Lösung!

**Comment by bikerbiker12** [comment]
Naja ich bin noch nicht ganz so fit mit dem ganzen. Hab eine neue Instanz über den Iobroker installiert, bei der dann das gleiche Problem auftritt. Bekomme ich eine Datensicherung aus dem Adapter? Dann würde ich diesen deinstallieren und neu installieren?

Bin grad mal auf die 0.4.0 zurück, ohne Erfolg



Von: SKB-CGN ***@***.***>
Gesendet: Mittwoch, 24. April 2024 22:15
An: SKB-CGN/ioBroker.energiefluss-erweitert ***@***.***>
Cc: Marco Matterne ***@***.***>; Mention ***@***.***>
Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Datenpunkte für Batteriekapazität und Prozent sind ab Version 0.4.0 anzugeben (Issue #186)


Hast du über GitHub nochmal installiert?

Aktuell weiss ich leider keine andere Lösung!

**Comment by SKB-CGN** [comment]
Du kannst soviele Instanzen erstellen, wie du möchtest - das Grundproblem der Installation bleibt.

Du kannst den Inhalt aus dem Datenpunkt "configuration" sichern. Da ist die Konfiguration drin.

**Comment by bikerbiker12** [comment]
Ich habe die Config gesichert, den Adapter deinstalliert und wieder neu installiert. Im Register „Speichern“ unter „Sicherung“ waren noch die alten Sicherungen vorhanden. Habe die letzte vor der Deinstallation genommen und wiederhergestellt.

Nun kann ich unter „Berechnung“ die Datenquellen wählen und die Berechnung findet statt. Der Rest ist alles wie bisher.

Danke dir für deine Unterstützung! PayPal kommt!

Gruß Marco

Von: SKB-CGN ***@***.***>
Gesendet: Mittwoch, 24. April 2024 22:43
An: SKB-CGN/ioBroker.energiefluss-erweitert ***@***.***>
Cc: Marco Matterne ***@***.***>; Mention ***@***.***>
Betreff: Re: [SKB-CGN/ioBroker.energiefluss-erweitert] Datenpunkte für Batteriekapazität und Prozent sind ab Version 0.4.0 anzugeben (Issue #186)


Du kannst soviele Instanzen erstellen, wie du möchtest - das Grundproblem der Installation bleibt.

Du kannst den Inhalt aus dem Datenpunkt "configuration" sichern. Da ist die Konfiguration drin.

**Comment by SKB-CGN** [comment]
Das klingt doch prima.
Ja, normal sollten die Sicherungen noch vorhanden sein, aber bei einer fehlerhaften Installation lieber noch den Datenpunkt "configuration" sichern.

Man weiss ja nie 😉 Vielen Dank für den großen Kaffee!

**Comment by bikerbiker12** [comment]
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126656972/05f1a7ee-be53-47ee-86c5-19a4eca8ff61)

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/126656972/05c367bf-751c-4cfc-a6f0-4c3349ceeb10)

**Comment by SKB-CGN** [comment]
Das liegt an der fehlenden Unterstützung in iOS Systemen. Auf Windows und Android kann der gedrehte Text angezeigt werden.
