### ISSUE TITLE
Enhancement: Undo Funktion

### ISSUE THREAD

**Issue by Horgul123** [SKB-CGN/ioBroker.energiefluss-erweitert#198]
Ich hoffe, ich habe das nicht einfach übersehen:
Eine Undo Funktion wäre klasse, falls man mal wieder zu blöd war ;)

**Comment by SKB-CGN** [comment]
Es gibt in der Bearbeitung des Elements eine Wiederherstellen Funktion, die dies ermöglicht.

**Comment by Horgul123** [comment]
@SKB-CGN Wo denn da? Ist das "Wiederherstellen"? Wenn ja: Unter dem Wording habe ich das noch nie gesehen :) Eher "Rückgängig"

**Comment by SKB-CGN** [comment]
In der Bearbeitung eines Elements gibt es 2 Buttons. Löschen und Wiederherstellen.

Löschen löscht und wiederherstellen stellt das Element wieder her, wenn's gelöscht wurde oder macht die aktuelle Bearbeitung wieder rückgängig.

**Comment by Horgul123** [comment]
Ah OK....   Finde ich wie geschrieben vom Wording her nicht intuitiv. Aber jetzt weiß ich es . Danke

**Comment by SKB-CGN** [comment]
Wie interpretierst du denn 'Wiederherstellen'?

Rückgängig ist eben ein Schritt. Wiederherstellen eben etwas, was gelöscht ist oder gesamt in den Ursprung zurückgesetzt wird.

**Comment by Horgul123** [comment]
Mir geht es ja um das Rückgängigmachen des letzten Schrittes. Das klassische Undo :)

Wiederherstellen in dem Kontext wusste ich nicht, wie das gemeint sein könnte. Ist mir in der IT nur im Kontext Backup/Restore bekannt.

**Comment by SKB-CGN** [comment]
Ein globales Rückgängig machen ist aktuell nicht vorgesehen. Wieso auch? Man sieht ja, was man klickt oder welches Element aktiv ist.

Wiederherstellen hat eben auch die Bedeutung, etwas wiederherzustellen, was verändert wurde.

Wird bald klarer, wenn der Button ausgegraut ist, solange nichts passiert ist. Dieser wird dann aktiv, wenn etwas verändert wurde.

**Comment by SKB-CGN** [comment]
Element anklicken, Stand aktuell wird zwischengespeichert.

Änderungen durchführen - solange die Configbar geöffnet ist, lassen sich alle Einstellungen wiederherstellen, die zum Zeitpunkt des Öffnen gesetzt waren.

Wird die Bar geschlossen, gelten die Einstellungen als gesetzt.

**Comment by Horgul123** [comment]
Hmmm..

Ok. Funktion verstanden.



Vermutlich werden aber viele das so nicht auf Anhieb verstehen, da es "unüblich" gelöst ist.
(nur als Hinweis, ich weiß jetzt, wie es funktioniert)

**Comment by SKB-CGN** [comment]
Die Funktion gibt es seit Anfang an und ist bis jetzt jedem klar geworden 😉

**Comment by Horgul123** [comment]
Na dann ;)

**Comment by SKB-CGN** [comment]
Ist ja jetzt auch nicht so schwer, die Funktion zu verstehen.
Zur Not klickt man drauf und weiss dann, was passiert 😉

**Comment by Horgul123** [comment]
Das schon.... Aber wie gesagt: Ist in der Art extrem ungewöhnlich....... Ich würde deswegen nie draufklicken, weil ich nicht wüsste, was es ist..... ;)

**Comment by SKB-CGN** [comment]
Der Begriff Wiederherstellen ist keines Wegs unüblich, wenn es darum geht, etwas wiederherzustellen, was verändert wurde.

**Comment by Horgul123** [comment]
Das nicht, Wie gesagt: Kenne das im Kontext Backup/Restore.

Nur in dem Kontext vom bearbeiten kenne ich undo/Rückgängig.  So heißt es in eigentlich allen Apps.
Das meine ich.

**Comment by SKB-CGN** [comment]
... Was es ja hier auch ist.
Sicherung des Elements vor der Bearbeitung und Wiederherstellung des kompletten Elements.

**Comment by Horgul123** [comment]
Hab schon Deine Idee dahinter verstanden. Ist halt nur ungewöhnlich. Sonst hast Du ein Undo, was den letzten Schritt rückgängig macht,

Du hast einfach nen anderen Ansatz gewählt und ein anderes Wording

**Comment by SKB-CGN** [comment]
Es ist aber nicht der letzte Schritt, der hier zurückgespielt wird, sondern das ganze Element seit Bearbeitungsbeginn.

**Comment by Horgul123** [comment]
Wie gesagt: Das habe ich verstanden, dass Du da nen anderen Ansatz hast.

Ist halt nur ungewöhnlich, da man sonst ein "mach die letzte Änderung rückgängig" hat :)

**Comment by SKB-CGN** [comment]
Gut, dann solltest Du auch verstehen, das hier nicht der letzte Schritt gemeint ist, sondern das komplette Element seit Start des Bearbeitungsmodus.

**Comment by Horgul123** [comment]
Hab ich doch schon mehrfach gesagt, dass ich das verstanden habe.
Es ist halt nur anders, als es bei anderen Apps gelöst ist.

Mehr sag ich dich gar nicht....
