### ISSUE TITLE
Animation Geschwindigeit Unterschied zu gering

### ISSUE THREAD

**Issue by Bernd9000** [SKB-CGN/ioBroker.energiefluss-erweitert#20]
0.0.2-alpha.7

Einstellungen in jeder Linie:
Duration
Min Duration on the Line = 1000
Max Power on the Line = 1000
Quelle ist bei allen Linien vorhanden.

Die Animation läuft bei allen Linien dann zwischen 1 und 2 Sekunden.
Das heißt bei 1W sind es 2 Sekunden und bei 1000W 1 Sekunde.

Stelle ich Min Duration on the Line = 10000 ein erhalte ich folgende Animationsgeschwindigkeit:
1W       = 11 Sekunden
1000W = 10 Sekunden

Man kann bei der Animation fast kein Unterschied erkennen.
War das so beabsichtigt ?
Oder mache ich was falsch?

Ausschnitt Datenpunkt Data im  iob bei Min Duration on the Line = 10000 :

"animationProperties": {
    "anim_path_14_7": {
      "type": "duration",
      "duration": 10135
    },
      "anim_path_7_40": {
      "type": "duration",
      "duration": 10999
    }

**Comment by SKB-CGN** [comment]
Ich hatte jetzt nicht gedacht, das jemand Animationen >10 Sekunden nutzt :)
Daher sind die Animationen <10 Sekunden "besser" geeignet.

**Comment by SKB-CGN** [comment]
Ich habe es mir nochmal angeschaut.

Hier liegt wohl ein Gedankenfehler vor.

Die Min. Duration gibt die Geschwindigkeit an, die deine maximale Leistung dann hat. Alles darunter wird entsprechend langsamer.

Sprich:
Max Power: 21000
Min. Duration: 1000

Dann läuft die 21.000 Leistung mit 1000ms auf der Linie. Alles, was weniger hat, läuft entsprechend langsamer.

Versuch' dies mal einzustellen.

**Comment by Bernd9000** [comment]
Doch, ich glaube schon, hab das IOB Forum durch :-)
Ich werde den gesamten Bereich wohl nicht vernüpftig abbilden können.
Bleiben wir mal bei bis 1000W und 1000ms.
Bei 1000W soll die Animation 1 Sekunde laufen
Bei 1W soll die Animation 10 Sekunden laufen.
Könntest Du mir dazu die Parameter nennen ?

**Comment by Bernd9000** [comment]
Wenn ich auf 1000/1000 stelle sehe ich kaum Unterschied.
Bei 1W will ich sehen wie die Punkte kriechen....
Bei 1000W sollen Sie rennen.....


![Animation1](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/77005685/347b62ec-4b92-4eb0-9667-e9a061a64280)

**Comment by SKB-CGN** [comment]
Gut, dann stell es etwas höher. Zwar wird die Endgeschwindigkeit langsamer, aber der Unterschied wird größer.
1000ms und 3500W z.B.

**Comment by Bernd9000** [comment]
Hier das Resultat mit 1000ms/3500W
Kein Unterschied zwischen den verschiedenen Leistungen.

![Animation2](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/77005685/eb333361-1e45-4a81-9762-3f0efed60c60)

**Comment by SKB-CGN** [comment]
Dies musst du ja pro Leitung einstellen

**Comment by Bernd9000** [comment]
Hab ich ja... jede einzelne Leitung

**Comment by SKB-CGN** [comment]
Es hat auch damit zu tun, wie lang die Linie ist.
Demnach musst du bei dem Server z.B. auch weniger als bei der Spül nehmen.

**Comment by Bernd9000** [comment]
Im IOB Forum stand etwas anderes:

[iob Forum](https://forum.iobroker.net/topic/64734/test-adapter-energiefluss-erweitert-v0-0-x-github-latest/341?_=1687552560357)

Ich wüßte jetzt auch nicht wie es da ein Unterschied geben sollte.
Wenn die Leitung länger ist gibt es nur mehr Punkte.

**Comment by SKB-CGN** [comment]
Die Punkte sind nicht von der Duration abhängig.
Im Forum hatte ich mich wohl verschrieben, denke ich.

Ich kann es leider nicht genau sagen, wie die Duration ist - man liest viel, aber nicht alles.
Wenn Du etwas beitragen kannst - gerne.

**Comment by Bernd9000** [comment]
Ach so, Du hast es nicht selbst programmiert ?
Fertiges Modul ?

**Comment by SKB-CGN** [comment]
Natürlich programmiere ich den Adapter.
Dieser ist aber von den Browsern abhängig.
Dort steht leider zu der Duration nichts genaues - also wie lang dies nun ist.
Wenn du dort etwas findest, sag gerne Bescheid.

**Comment by Bernd9000** [comment]
Ich würde in der `Main.js` eingreifen bei der Funktion `calculateDuration`

Aktuell teste ich mit folgender veränderter Funktion:
Aber für Heute ist erstmal Feierabend :-)


`Code:`
calculateDuration(maxDuration, maxPower, currentPower)
{
		// Max Duration
		let dur = Number(maxDuration);
		let cwp = Number(currentPower);
		let mwp = Number(maxPower);
		let pwr = dur + ((mwp - cwp) * ((5000 - dur) / mwp));
		return pwr > 0 ? pwr : dur;

//Math.round((((currentPower / maxPower) * 100) * maxDuration) / 100);
}

**Comment by Bernd9000** [comment]
Hab es jetzt mal anders gemacht.
Das Problem an der Sache wird sein, das jeder sein Schwerpunkt bei der Animation wo anders hat.
Ich hab das für mich jetzt als "Tabelle" gelöst.
Die Funktion gilt dann für alle Linien.
Das heißt z.B. ist der aktuelle Leistungswert zwischen 0W und 10W dann Duration = 20000ms (max)
Werte kleiner 250ms machen für mich kein Sinn da man den Unterschied nicht mehr erkennen kann.
Der Vorteil der Bereiche ist dann noch, das die Animation nicht so oft "hackt" weil seltener die Duration umgeschaltet wird.


Code:

calculateDuration(maxDuration, maxPower, currentPower) {
		let cwp = Number(currentPower);
		let pwr = 20000;
		
		if (cwp >= 10 && cwp < 100)
		{
			pwr = 5000;
		}
		if (cwp >= 100 && cwp < 500)
		{
			pwr = 3000;
		}
		if (cwp >= 500 && cwp < 1000)
		{
			pwr = 1000;
		}
		if (cwp >= 1000 && cwp < 4000)
		{
			pwr = 500;
		}
		if (cwp >= 4000)
		{
			pwr = 250;
		}
		return pwr;
	}

![Animation](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/77005685/7efa1846-95e9-447f-aefc-578e3d37867d)

**Comment by SKB-CGN** [comment]
Das sind ja dann "hardcoded"-Werte, die der Benutzer nicht gut anpassen kann.

Ich werde dort nochmal schauen.

Bei mir z.B. funktioniert die Animation gut, bei der Klimaanlage, die 20W Standby hat und sich die Linie dann wenig bewegt und dann eben schneller bei den 1000W Verbrauch, wenn sie in Betrieb ist.

**Comment by Bernd9000** [comment]
Die Tabelle entspricht ungefähr folgender Potenzregression:

`Code:`
duration = Math.round((200 * (aktuelle_leistung ** -0.5)) * 100 );

Ich werde das mal testen

**Comment by Bernd9000** [comment]
Jo, funktioniert.
Arbeitet dann eben nur mit der aktuellen Leistung.
Für mich ist die Animation so jedenfalls besser.
Kannst ja mal testen.

Issue kann dann dicht.

**Comment by SKB-CGN** [comment]
Ich hatte mir gerade mal folgende Formel überlegt:

Minimale Dauer		2000
	
Maximale Leistung	1000
	
Aktuelle Leistung	20

`Formel: Maximale-Leistung / Aktuelle-Leistung * Minimale-Dauer`

```
Watt		Dauer
1               20000000
10		2000000
100		200000
1000		20000
10000		2000
```

**Comment by Bernd9000** [comment]
Nein, nur mit der aktuellen Leistung.

Bei deiner Angabe verstehe ich die "Aktuelle Dauer 100000" nicht. Wofür ist die ?
Bei der Formel ist jetzt das Problem das bei kleiner aktueller Leistung die Dauer zu lang ist.
Bei deiner Tabelle würde es ja bei 1W aktueller Leistung eine Animationsdauer von über 5 Stunden bedeuten.

Es ist schwierig dafür eine Funktion zu finden.

**Comment by SKB-CGN** [comment]
Stimmt. Die aktuelle Dauer wäre die berechnete Dauer.

Ich Stelle Dir Morgen eine Datei auf meinen Space - da kannst du dann einmal herumprobieren.

**Comment by Bernd9000** [comment]
Hab ein neuen Weg gefunden mit nur einem zusätzlichen Parameter `max_dauer`

Variablen:
aktuelle_leistung = aktuelle Leistung in Watt
max_leistung      = Aus den Einstellungen "Max Power on the Line"
min_dauer          = Aus den Einstellungen "Min Duration on the Line" = minimale Dauer bei maximaler Leistung
max_dauer         = maximale Dauer bei 1 Watt. Müßte noch in den Einstellungen rein, fester Wert hier hier 20000


Mit der Variablen `exponent` wird im voraus der Exponent für das Potenzieren  berechnet.
Dadurch kann man die Grenzen für die Dauer bei kleinster und größter Leistung vorgeben.




````
calculateDuration(maxDuration, maxPower, currentPower) {
		let aktuelle_leistung = Number(currentPower);
		let max_leistung = Number(maxPower);
		let min_dauer = Number(maxDuration);
		let max_dauer = 20000;  // noch nicht in den Einstellungen
		
		if (aktuelle_leistung == 0 ) {aktuelle_leistung = 1}	//keine 0
		var exponent = Math.log10(min_dauer / max_dauer) / Math.log10(max_leistung);
		var dauer = Math.round((aktuelle_leistung ** exponent) * max_dauer);
		return dauer;
	}
````

**Comment by SKB-CGN** [comment]
Man könnte auch einfach sagen, das die maximale Dauer einer Animation 1 Minute - 60.000ms nicht übersteigt.

Dann müssen nicht soviele Felder ausgefüllt werden 😉

**Comment by Bernd9000** [comment]
Für mich ist das Thema erledigt, ich mach mal dicht.

**Comment by SKB-CGN** [comment]
Behältst Du deine Funktion bei oder passt dir die von mir implementierte auch? 😉

**Comment by Bernd9000** [comment]
Im Moment hab ich noch meine Funktion

**Comment by SKB-CGN** [comment]
Auch gut
