### ISSUE TITLE
Beim öffnen: Fehler: Verbindung fehlgeschlagen

### ISSUE THREAD

**Issue by Duffy987** [SKB-CGN/ioBroker.energiefluss-erweitert#201]
**Nach der Installation von Version 0.4 oder 0.4.1 wird die Konfigurationsseite sowohl in Safari als auch Firefox nicht geöffnet **  
Nach der Installation von Version 0.4 oder 0.4.1 wird die Konfigurationsseite sowohl in Safari als auch Firefox nicht geöffnet es kommt der Fehler:

Fehler: Verbindung fehlgeschlagen

Firefox kann keine Verbindung zu dem Server unter 192.xxx.xxx.41:8082 aufbauen.

    Die Website könnte vorübergehend nicht erreichbar sein, versuchen Sie es bitte später nochmals.
    Wenn Sie auch keine andere Website aufrufen können, überprüfen Sie bitte die Netzwerk-/Internetverbindung.
    Wenn Ihr Computer oder Netzwerk von einer Firewall oder einem Proxy geschützt wird, stellen Sie bitte sicher, dass Firefox auf das Internet zugreifen darf.

![1](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/120317770/9304c034-2f26-4edc-b45b-303cf6c90743)
![2](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/120317770/450c48a7-e0fa-47ac-9089-1a518deafc13)
![3](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/120317770/c0f170d5-0379-4e16-be11-bb08f8537c92)

**To Reproduce**  
1. Instanzen oder übersicht
2. Klick auf Energiefluss erweitert
3. Nichts passiert
4. der Seitenladefehler wird angezeigt

**Expected behavior**  
Das ich auf die Konfigrationsoberfläche komme
**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 5.0.19
 - Node version: 20.14
 - Operating system: <Raspberry pi 4 Bookworm

**Additional context**  

Protokoll nach dem Start des Adapters:

energiefluss-erweitert.0 | 2024-06-09 17:21:54.175 | info | Requesting the following states: energiefluss-erweitert.0.configuration
-- | -- | -- | --
energiefluss-erweitert.0 | 2024-06-09 17:21:54.174 | info | Configuration loaded!
energiefluss-erweitert.0 | 2024-06-09 17:21:54.076 | info | Adapter started. Loading config!
energiefluss-erweitert.0 | 2024-06-09 17:21:54.026 | info | starting. Version 0.4.1 in /opt/iobroker/node_modules/iobroker.energiefluss-erweitert, node: v20.14.0, js-controller: 5.0.19
host.raspberrypi | 2024-06-09 17:21:52.392 | info | instance system.adapter.energiefluss-erweitert.0 started with pid 78136
host.raspberrypi | 2024-06-09 17:21:52.241 | info | "system.adapter.energiefluss-erweitert.0" enabled

**Comment by SKB-CGN** [comment]
WebAdapter installiert und konfigurier?

WebAdapter auf integriert stellen und keine Checkbox angehakt?

**Comment by Duffy987** [comment]
Entschuldigung vielmals ich verstehe nicht.
WebAdapter installiert und konfiguriert? Was für ein Web Adapter ich habe den Energiefluss Ad.apter installiert.
WebAdapter auf integriert stellen und keine Checkbox angehakt? Wo macht man das? 
Ist web.0 gemeint?

**Comment by SKB-CGN** [comment]
Der Adapter benötigt den WebAdapter um dargestellt werden zu können.

Ja, web.0 ist die erste Instanz des Web-Adapters. Ist dieser so eingestellt, wie oberhalb beschrieben?

**Comment by Duffy987** [comment]
Es lag am Web.0 Adapter. Jetzt geht es. Danke schön.
Der Fall kann bitte geschlossen werden.

**Comment by SKB-CGN** [comment]
Was genau war denn das Problem?

**Comment by Duffy987** [comment]
Jetzt wird es für mich peinlich.

Web.0 war bei mir nicht angeschaltet.

(Duck und weg.)

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. Ich werde dafür eine Prüfung einbauen 👍
