### ISSUE TITLE
Im Objektbrowser werden keine Ordner geöffnet

### ISSUE THREAD

**Issue by MaddogMccree** [SKB-CGN/ioBroker.energiefluss-erweitert#214]
Hallo zusammen

habe den Adapter ( 0.5.1 Alpha ) Installiert und komme auch auf die Konfigurationseite.
Doch sobald ich auf Datenquelle gehe kommt folgendes Bild

![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/76697599/0b4ad1c9-de3b-409e-98e8-a5cbd0929c85)

dabei lässt sich aber kein einziger Ordner der Datenquelle öffnen.( Oben steht dann Objektbrowser wird geladen was auch nicht weg geht)
woran könnte das liegen?

**Comment by SKB-CGN** [comment]
Update oder Neuinstallation?
Upload des Adapters durchgeführt?

**Comment by MaddogMccree** [comment]
Hatte zuerst die 0.4.1 aus dem stable installiert war das selbe Problem dann die alpha installiert.
Was meinst du mit" upload des Adapters durchgeführt "?

**Comment by SKB-CGN** [comment]
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert?tab=readme-ov-file#050-alpha0-2024-06-24

**Comment by MaddogMccree** [comment]
Hatte ich noch nicht gemacht. Habe es aber gerade gemacht doch das problem besteht immer noch

**Comment by SKB-CGN** [comment]
Hast du jetzt einen Upload des Adapters durchgeführt?

Die Seite im Browser mit Steg+F5 neugeladen?

Welches Betriebssystem? Welcher Browser?

**Comment by MaddogMccree** [comment]
Ja habe ich gemacht.
Ja habe sogar den Browser ( Firrefox ) neu gestartet.
Mein Betriebsystem ist windows 11 und wie gesagt mein Browser ist Firefox wobei ich Microsoft Edge und Chrome ebenfalls probiert habe überall das gleiche Problem

**Comment by SKB-CGN** [comment]
Sieht so aus, als wenn alte Dateien in Verwendung sind. Bitte mal den Cache des Browsers löschen.

Erscheinen in der Konsole (F12) des Browsers Fehler?

**Comment by MaddogMccree** [comment]
Ja es kommt folgender fehler in der Konsole:

Uncaught (in promise) TypeError: e[p].common is undefined
    generateStateTree http://192.168.0.118:8082/energiefluss-erweitert/js/functions.min.js?v=0.5.1:1
    openStateTree http://192.168.0.118:8082/energiefluss-erweitert/js/functions.min.js?v=0.5.1:1
functions.min.js:1:18174

**Comment by SKB-CGN** [comment]
Dann ist einer Deiner Datenpunkte fehlerhaft, weil das Objekt "Common" fehlt.
Müsste ich eine Prüfung für einbauen.
Erscheint der Fehler direkt nach dem Öffnen des Browsers oder beim Klicken auf einen Ordner?

**Comment by MaddogMccree** [comment]
der fehler kommt direkt beim öffnen des browsers

**Comment by SKB-CGN** [comment]
Habe mal einen "Fix ins Blaue" erstellt.

Bitte einmal drüber installieren und schauen, ob der Fehler weg ist bzw. sich die Objekte nun öffnen lassen.

**Comment by MaddogMccree** [comment]
welche soll ich installieren ? 0.4.1 oder die alpha?

**Comment by SKB-CGN** [comment]
Natürlich direkt die von GitHub mit der GitHub Adresse.

**Comment by MaddogMccree** [comment]
Habe ich gemacht derselbe fehler immer noch ( https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert.git richtige adresse ? )

**Comment by SKB-CGN** [comment]
Nein, ohne Git am Ende.

https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/

Auch musst Du danach wieder einen Upload des Adapters durchführen und die Seite mit Steg+F5 neu laden.

Als Tipp: Grundlagen für ioBroker helfen auch ungemein, um zu wissen, wie man Alpha oder Beta Adapter installiert.

**Comment by MaddogMccree** [comment]
Danke für den Tip werde ich nachholen hatte bisher noch nie alpha oder beta installiert.
Habe ich so installiert --> adapter upload gemacht --> Cache gelöscht --> Firefox neugestartet 
Problem besteht immer noch 
Auch die fehler meldung vom Browser besteht noch:

Uncaught (in promise) TypeError: n[p].common is undefined
    generateStateTree http://192.168.0.118:8082/energiefluss-erweitert/js/functions.min.js?v=0.5.1:1
    openStateTree http://192.168.0.118:8082/energiefluss-erweitert/js/functions.min.js?v=0.5.1:1
    async* http://192.168.0.118:8082/energiefluss-erweitert/js/functions.min.js?v=0.5.1:1
    jQuery 2
        dispatch
        handle
functions.min.js:1:18895

**Comment by SKB-CGN** [comment]
Heisst? Du hast über die Github-Katze installiert, danach einen Upload gemacht und dann nochmal den Cache gelöscht?

Dann dies nochmal wiederholen. Ich habe noch etwas angepasst.

Via https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/ mit der Git-Katze installieren, dann upload des Adapters, dann die Seite im Browser mit Strg+F5 neuladen.

**Comment by MaddogMccree** [comment]
Habe es nach deiner anleitung gemacht leider immer noch das Problem vorhanden

**Comment by MaddogMccree** [comment]
Hallo habe in meinen Datenpunkten einwenig aufgeräumt jetzt Funktioniert es
Vielen lieben Dank für die unterstützung

**Comment by SKB-CGN** [comment]
Wäre jetzt natürlich gut zu wissen, was mit den Datenpunkten war.
Erstmal gut, wenn es funktioniert - dann bitte das Issue schließen.

**Comment by MaddogMccree** [comment]
Das weiß ich jetzt auch nicht genau habe einfach alte datenpunkte gelöscht sie ich nicht mehr brauche und auf einmal ging es

**Comment by SKB-CGN** [comment]
Ok, dann wird dort wohl ein Fehler drin gewesen sein. Schade nur, das man den jetzt nicht mehr findet, damit ich diesen abfangen könnte.

**Comment by MaddogMccree** [comment]
Ja schade aber danke dir trotzdem für deine Zeit und wünsche noch einen schönen Rest Sonntag

**Comment by SKB-CGN** [comment]
Gerne.
Danke - viel Spaß mit dem Adapter!
