### ISSUE TITLE
Batterielaufzeit anziegen

### ISSUE THREAD

**Issue by baca89** [SKB-CGN/ioBroker.energiefluss-erweitert#222]
**Describe the bug**  
Der Adapter berechnet die verbleibende Batterielaufzeit korrekt. Diese wird im Format 'hh:mm' angegeben als Objekt im iobroker. soweit auch alles gut. Wenn ich Versuche diesen Datenpunkt im Adapter darstellen zu lassen erhalte ich eine Ausgabe in der Form:

Wert im iobroker-Objekt: "10:58h"
Anzeige im Adapter: "1058"h

wie ist hier denn die korrekte Vorgehensweise für Zeitformate? Im "einfachen" energiefluss-adapter wird dies ja korrekt angezeigt

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.4.1
 - JS-Controller version: 5.0.19
 - Node version: 18.20.2
 - Operating system: debian

**Additional context**

**Comment by SKB-CGN** [comment]
Dazu ist die Darstellungsform "Quelle anzeigen als" -> Text notwendig, da es ein Text ist und kein Wert.

**Comment by SKB-CGN** [comment]
Hat sich dieses Problem erledigt?
Wenn ja, bitte das Issue schließen.

**Comment by baca89** [comment]
Ok Vielen Dank für diesen Hinweis.
