### ISSUE TITLE
0.5.1-alpha.3: Batterienrestzeit Anzeige springt immer auf "--:--" zurück

### ISSUE THREAD

**Issue by RoberWi** [SKB-CGN/ioBroker.energiefluss-erweitert#223]
Moin,

in der aktuelle Alpha.3 gibt es folgendes Phänomen:

![Screenshot 2024-07-27 155152](https://github.com/user-attachments/assets/af4ff292-e297-43f0-9fd1-0144e4e030c5)

Wie man sehen kann, springt die Anzeige für die Restzeit sofort wieder auf "--:--" zurück. Das liegt daran, dass beim zweiten Aufruf "energy = 0" ist. Das ist vom Code her richtig, wenn "energie = 0", dann wird nichts berechnet.

Die Frage ist aber: Warum wird der Code zweimal direkt hintereinander aufgerufen? Ich habe das Debug-Log eine Weile mitlaufen lassen, es spielt keine Rolle, ob die Batterien geladen oder entladen wird.

Ich habe die Anzeige auch entfernt, die Berechnung wird trotzdem zweimal aufgerufen.

Brauchst Du noch mehr Infos?

**Comment by SKB-CGN** [comment]
Ist ja logisch, das die Anweisung 2 Mal aufgerufen wird.

Es ändert sich ```charge``` und ```discharge``` im Wechsel.

Somit hat ```discharge``` Energy und kann berechnet werden - ```charge``` hingehen nicht. Daher kommt auch keine Zeit zustande.

**Comment by RoberWi** [comment]
Ich habe jetzt die beiden Objekte verfolgt.

Der Trigger für die Berechnung scheint auf dem Timestamp zu liegen und nicht auf Last Change. Last Change ändert sich nicht, aber der Timestamp leider jedesmal, weil der Zendure-Adpater wohl immer beide Werte schreibt.

Wäre es sinnvoll, den Trigger zu ändern oder eine Option für den zu stellen?

**Comment by SKB-CGN** [comment]
Der Adapter bearbeitet immer alle Änderungen nach deren auftreten. Wenn also Ladung vorher geschrieben wird und Entladung danach, gilt die Entladung.

**Comment by RoberWi** [comment]
Es gibt aber keine Änderungen, nur ein Aktualisierung.

Ich habe das mit einem Mini-Script mir zwei Triggern ausprobiert:

```
on({ id: 'zendure-solarflow.0.xxx.yyy.packInputPower' /* Entladeleistung aus Batterie */, change: 'ne' }, async (obj) => {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  console.info('Entlade');
  console.log('Neuer Wert: ' + value);
  console.log('Alter Wert: ' + oldValue);
});
on({ id: 'zendure-solarflow.0.xxx.yyy.outputPackPower' /* Ladeleistung zur Batterie */, change: 'ne' }, async (obj) => {
  let value = obj.state.val;
  let oldValue = obj.oldState.val;
  console.info('Lade');
  console.log('Neuer Wert: ' + value);
  console.log('Alter Wert: ' + oldValue);
});
```

Stelle ich die Trigger auf "change: 'ne'", dann bekomme ich einen Auslöser nur bei einer Änderung der Zahl. Und nur von dem einen Object, was geändert wurde.
Stelle ich den auf "change: 'any'", dann bekomme ich die Auslösung von beiden Object. "value" und "OldValue" werden aber korrekt gesetzt. Darüber wäre es möglich zu erkennen, ob sich 

Ich habe jetzt zwei Dummy-Objecte angelegt, die mit den Originalen verknüpft und in den Datenquellen auf die Dummy geändert:

```
on({ id: 'zendure-solarflow.0.xxx.yyy.outputPackPower', change: 'ne' }, (obj) => {
  setState('0_userdata.0.eigene.charge', obj.state.val);
});
on({ id: 'zendure-solarflow.0.xxx.yyy.packInputPower', change: 'ne' }, (obj) => {
  setState('0_userdata.0.eigene.discharge', obj.state.val);
});
```

So funktioniert es und auch im Log gibt es nur noch einen Eintrag.

**Comment by SKB-CGN** [comment]
Was man hier natürlich einmal ausprobieren könnte:

Den Adapter prüfen zu lassen, ob sich der neue Wert vom Alten unterscheidet und somit keine Aktualisierung durchführen zu lassen.

**Comment by RoberWi** [comment]
Ehrlich gesagt, habe ich auch schon danach gesucht. :)

Es scheint aber im Adapter keinen eingebauten Weg zu geben. onStateChange // stateChange liefert den alten Wert nicht mit. Insofern unterscheidet sich das tatsächlich vom Scripting via JS.

Was man findet ist, dass man die alten Werte selbst innerhalb des Adapters speichern muss.

Und da kann ich nicht beurteilen, wie oft dieses Problem vorkommt. Im Prinzip ist der Zendure-Adpater unglücklich programmiert, weil er die Werte immer schreibt, egal ob geändert oder nicht. Der Programmierer dort könnte das eventuell lösen.

**Comment by SKB-CGN** [comment]
Ich schaue mir das mal an. So gesehen speichere ich die RAW Values aus den zugehörigen Datenpunkten bereits, da ich sie weiter verwende (Berechnung von Subtraktionen oder Additonen).

Somit könnte man damit vielleicht auch arbeiten und auch hier weniger Durchführungen stattfinden lassen, da nicht immer alles durchlaufen werden muss. 

Zu dem Zendure Adapter - ich denke, hier werden die Werte einfach abgeholt und in einer Schleife weg geschrieben. Ohne zu prüfen, ob ein Vorgang notwendig ist.

**Comment by SKB-CGN** [comment]
Hallo,
habe in der aktuellen Alpha Version einmal etwas angepasst, das die Werte nicht neu berechnet werden, wenn sie gleich geblieben sind.
Du könntest dies vielleicht einmal ausprobieren, ob nun die Werte für die Ladung der Batterie passen?

**Comment by RoberWi** [comment]
Habe die letzte Version installiert. Das Flackern ist weg.

Aber nun stimmt die Berechnung nicht mehr. Mein 1920 Wh Akku wäre in wenigen Minuten gefüllt. Ich habe mal ein wenig gesucht, und denke, dass der Wert in "energiefluss-erweitert.0.calculation.battery.remaining_energy" falsch übernommen wird.

Gebe ich in meinem Attribut 1920 ein (die Einheit ist ja Wh) dann wird darasus 19,2 im o.g. Objekt. Gebe ich 192000 ein, dann steht im o.g. Objekt auch 1920 drin.

Allerdings NUR beim Laden. Beim Entladen wird der richtige Wert (1920) übernommen.

Die ausgerechneten Zeiten sind aber in beiden Richtungen total verkehrt.

**Comment by SKB-CGN** [comment]
Das sind ja 2 verschiedene Dinge, von denen wir nun sprechen.

Der Datenpunkt ```remaining_energy``` ist neu - somit kann dieser fehlerhaft sein :)

Was heisst, "ist falsch"? Welche Zeiten? Welche Werte?

**Comment by SKB-CGN** [comment]
Ah, okay :)
Wollte schon sagen ...

**Comment by RoberWi** [comment]
Ich habe das jetzt einige Tage beobachtet. Sieht auch im letzten Update gut aus.

**CLOSED**

**Comment by SKB-CGN** [comment]
Prima, dann läufts ja 👍
