### ISSUE TITLE
Schwellwert der Verbindungen lässt sich nicht anpassen.

### ISSUE THREAD

**Issue by BenAhrdt** [SKB-CGN/ioBroker.energiefluss-erweitert#229]
Ich benutze die Version 0.4.1 des Adapters.

Die Schwellwerteinstellungen der Verbindungslinien lassen sich nicht einstellen.
Stellt man dort einen Wert ein, so ist dieser später (bspw. wenn man auf ein anderes Objekt und zurück auf das Ursprügliche klickt wieder auf dem vorherigen Wert:

![image](https://github.com/user-attachments/assets/c8d7fd96-a757-4328-aa5d-c12ae38dce45)

**Comment by SKB-CGN** [comment]
Den Fehler kann ich aktuell nicht nachvollziehen.
Bitte einmal die Browser-Konsole öffnen und das Feld "Debug" anzeigen lassen. Hier sollte bei Änderung des Schwellenwerts ein Hinweis ausgegeben werden.
Passiert dies?

**Comment by BenAhrdt** [comment]
@SKB-CGN Also, wenn ich hier etwas ändere (im schwellwert).
dann passiert in der konsole genau nichts:
![image](https://github.com/user-attachments/assets/5c328d5f-04d4-4815-a01e-89fe7c0ec353)

**Comment by SKB-CGN** [comment]
Steht die Ausgabe denn auf Debug?

**Comment by BenAhrdt** [comment]
Auch so tut sich nichts:
![image](https://github.com/user-attachments/assets/bd8e32c4-94d1-4659-ac32-cc14bd146aa8)

**Comment by SKB-CGN** [comment]
Was erscheint beim Ändern anderer Felder?
Auch nichts?

**Comment by BenAhrdt** [comment]
nein nicht wirklich.... klickt man eine datenquelle an, dann erscheint das hier, aber bei änderungen passiert nichts
![image](https://github.com/user-attachments/assets/b11de6e8-0017-4934-b76f-be8f7d29fbb0)

**Comment by SKB-CGN** [comment]
Vielleicht zum Testen mal die aktuelle Alpha installieren (kann sein, das die Debug Ausgabe in der 0.4.1 noch nicht enthalten ist).

**Comment by BenAhrdt** [comment]
er scheint immer nur die erste änderung zu übernehmen, wenn ich auf den schaltflächen auf und ab scrolle. direkte eingaben übernimmt er gar nicht.
Also habe jetzt mal nach oben geklickt und direkt gespeichert.... da nimmt er nur den 1. step
![image](https://github.com/user-attachments/assets/55c5367f-a66b-4746-8f2c-6c15893c07ad)

**Comment by BenAhrdt** [comment]
> Vielleicht zum Testen mal die aktuelle Alpha installieren (kann sein, das die Debug Ausgabe in der 0.4.1 noch nicht enthalten ist).

direkt aus github installieren?
Ps. meine restlichen einstellungen sind dann noch da? ;-)

**Comment by SKB-CGN** [comment]
Ja, mit dem Link zu der Alpha via GitHub Katze installieren.

Alle Daten bleiben erhalten.

**Comment by BenAhrdt** [comment]
Damit logt er es und es wird auch gespeichert

**Comment by SKB-CGN** [comment]
Dann scheint dies ein Fehler in der 0.4.x zu sein, den noch keiner bemerkt hat 🤠

**Comment by BenAhrdt** [comment]
Coole verbesserung wäre, wenn man ein objekt angewählt hat und bspw auf erweitert ist, dann ein anderes Objekt auswählt, dass auch das den erweitert reiter anzeigt und man nicht wieder bei basic ist ;-)

**Comment by SKB-CGN** [comment]
Ich habe es so eingerichtet, das die Elemente immer in der Grundfunktion starten bzw. konfiguriert werden.

Somit ist man immer bei Start.

**Comment by BenAhrdt** [comment]
Kann man auch "Multiselect" durchführen?
Bspw. bei alle Verbindungen den Schwellwert auf 10 setzen?

**Comment by BenAhrdt** [comment]
OK.
Noch etwas Offtopic:
Kann man hier einen Zeilenumbruch rein bekommen? :-)
![image](https://github.com/user-attachments/assets/0676bedf-d85a-4cf0-8c71-a5b5599ee4f0)

**Comment by SKB-CGN** [comment]
Ist das die Option Uhrzeit?

Ja, 2 Datenquellen untereinander - jeweils mit Datum und dann Uhrzeit.

**Comment by BenAhrdt** [comment]
Das ist die Restdauer für den Akku, bzw. unten das der Zeitpunkt. Ist ein Datenpunkt.

**Comment by SKB-CGN** [comment]
Achso, der Zieldatanpunkt des Akkus?

Anzeigen als Text und dann ist darunter die Möglichkeit "Zeilenumbruch nach x Zeichen".

**Comment by BenAhrdt** [comment]
Danke. Da gibts aber noch nen Bug, wenn man das macht, lässt sich das Objekt in X Richtung nicht mehr verschieben.... auch nicht direkt über eingabe einer koordinate

**Comment by SKB-CGN** [comment]
Du meinst beim Zeilenumbruch?

Ja, der kommt mit der nächsten Version mit.
Den kenne ich bereits 😉

**Comment by BenAhrdt** [comment]
jetz hat er mir nur durch den Zeilenumbruch das Objekt zerstört
![image](https://github.com/user-attachments/assets/9b0f61e4-19d9-4131-a2df-0da4b6fcc16e)

**Comment by BenAhrdt** [comment]
Jetzt macht er nichts mehr... hatten nur auf das Zahnrad zur Bearbeitung geklickt:
![image](https://github.com/user-attachments/assets/beaf2db7-31b3-442c-8c8f-ee41033dd3c3)

**Comment by SKB-CGN** [comment]
Sieht nach einem Absturz aus?

**Comment by BenAhrdt** [comment]
wieso ist der 2 mal drin?
Alspha?
![image](https://github.com/user-attachments/assets/5fe43450-2247-40c1-84ee-28365f8496ac)

Ps. neustart bringt nichts. gleiches Bild

**Comment by BenAhrdt** [comment]
in der browserzeile nochmal enter... .läuft wieder...sehr komisch

**Comment by SKB-CGN** [comment]
Pro WebInstanz ist ein Adapter Link.

**Comment by BenAhrdt** [comment]
ja, ich wundere mich nur gerade, dass ich zwei kacheln auf der Übersicht habe, denn ich habe ja nur eine instanz

**Comment by BenAhrdt** [comment]
Hast Du das noch auf dem Schirm, was wir mal bei Deiner ersten Version hatten, dass die Linien sich langsamer bewegen, wenn die Leistung nur einen kleinen Teil vom Verbrauch ausmachen?
Könnte man das nicht auch noch in die Linien rein bringen, dass die Animation bzw. die Max geschwindigkeit auf einen Datenpunkt bezieht und wenn der ausgewählte datenpunkt für die annimation nur 50% davon ist, dann bewegt sich die Animation nur hab so schnell.

**Comment by SKB-CGN** [comment]
> ja, ich wundere mich nur gerade, dass ich zwei kacheln auf der Übersicht habe, denn ich habe ja nur eine instanz

Anscheinend aber 2 WebAdapter Instanzen.

**Comment by SKB-CGN** [comment]
> Hast Du das noch auf dem Schirm, was wir mal bei Deiner ersten Version hatten, dass die Linien sich langsamer bewegen, wenn die Leistung nur einen kleinen Teil vom Verbrauch ausmachen?
> Könnte man das nicht auch noch in die Linien rein bringen, dass die Animation bzw. die Max geschwindigkeit auf einen Datenpunkt bezieht und wenn der ausgewählte datenpunkt für die annimation nur 50% davon ist, dann bewegt sich die Animation nur hab so schnell.

Lässt sich einstellen. Tab 'erweitert' der Linie.

Geschwindigkeit/Punkte usw.

**Comment by BenAhrdt** [comment]
Das hier?
![image](https://github.com/user-attachments/assets/2e6c5ea3-c62b-4c51-8b78-d99e923034f5)
Leider nicht... denn da kann ich ja nur einen festen wert eintragen.

UND
![image](https://github.com/user-attachments/assets/350951b3-51b8-45c3-8647-db124684a3b5)

NUR eine Web instanz
![image](https://github.com/user-attachments/assets/3553daa5-e069-4546-ba28-78494b73987a)

**Comment by SKB-CGN** [comment]
Dann ist die Installation offensichtlich nicht erfolgreich gelaufen oder es wurde kein Upload gemacht, wie es bei Github Version von nöten ist.

Genau, so ähnlich ist es bei der vorherigen Version auch. Maximale Leistung auf der Linie angeben und es wird berechnet, wie schnell oder langsam die Animation laufen soll.
Was genau soll denn nicht klappen, wenn dort ein maximaler Wert der Leistung auf der Linie angegeben wird?

**Comment by BenAhrdt** [comment]
ich dachte man legt dort den wert vom Verbrauch drauf.... aber ok.
Aber hier ist ein Bug.... wenn ich auf Dauer stehen habe, dann speichere udn wieder auf die linie und erweitert gehen, werden die felder dauere und max leistung nicht mehr angezeigt. erst deaktivieren und wieder auf dauer stellen... dann gehts wieder.
![image](https://github.com/user-attachments/assets/88bcb990-a7f8-46e6-a7fc-0159f92dec28)

Ps. die installation schloss mit erfolgreich ab.
und was für ein upload?

**Comment by SKB-CGN** [comment]
Nein, man legt dort die maximale Leistung fest, anhand dessen die Geschwindigkeit berechnet wird.

Ja, den Adapter kann man deinstallieren und dann den Datenpunkt ```configuration``` wieder einspielen.

**Comment by BenAhrdt** [comment]
OK. neu installiert... aber es sind wieder 2 Kacheln da

**Comment by SKB-CGN** [comment]
Dann wirst Du ein anderes Problem mit deiner ioBroker Installation haben.

**Comment by BenAhrdt** [comment]
keine ahnung, bis auf den adapter hier, ist das bei keinem... aber wie gesagt, erst seit die alpha drauf ist.
aber er muss ja die andere kachel udn den link irgendwo her bekommen.
Habe gerade den adapter runter geschmissen und sie ist weg... alpha drauf => 2 kachgeln

Ps. mit der bewegungsgeschwindigkeit war in dem anderen nicth ganz so, denn bei einer mindestduer auf der linie,holt man sich ja die linienlänge als variable mit rein. das war vorher nicht so.

**Comment by SKB-CGN** [comment]
Nutzt Du iobroker cloud? Dann ist die Kachel für diesen.

Mit der Geschwindigkeit wird keine Länge der Linie berücksichtigt, sondern eine Dauer angegeben, die die Animation benötigt. Ist aber in dem kleinen Fragezeichen auch erklärt, wie genau das funktioniert. Bei der anderen Version wurde auch keine Linienlänge berücksichtigt.

**Comment by BenAhrdt** [comment]
Ja, aber ich würde es so verstehen.
Min Dauer 1000
Max Wert 1000
=> 1000W = 1s
Richtig?

Wenn ich nun 2 Linien so eingestellt habe und die eine doppelt so lange wie die andere ist, dann läuft doch da die Animation doppelt so schnell durch, weil sie auch in 1s fertig sein muss.

**Comment by SKB-CGN** [comment]
Nein, es ist die Geschwindigkeit, wie sich die Punkte bewegen.

Ein Auto mit 50km/h fährt auf einer Straße mit 100km auch so schnell, wie auf einer Straße, die 100m lang ist.

**Comment by BenAhrdt** [comment]
OK, dann ist es ok, aber dann verstehe ich die Beschreibung beim Fragezeichen nicht.
Worauf bezieht sich denn die Dauer? Die Muss sich ja dann auf eine gewisse Strecke beziehen.
Also ind der eingestellten dauer legt die animation einen definierten weg zurück, bei wert = max. richtig?
aber den definierten weg, der ist fert in deinem code. richtig?

**Comment by SKB-CGN** [comment]
Nicht immer so kompliziert denken.
Es ist eine Zeit-Angabe, die diese Animation in Anspruch nimmt und die läuft immer gleich lang oder kurz.

**Comment by BenAhrdt** [comment]
OK, aber die ist immer gleichlang berechnet... ok. versteh... hat nichts mit kompliziert zu tun, aber bei einer zeit angebe bezieht sich immer etwas auf eine längt, sonst wäre es davon abhängig... in deinem beispiel beziehst du ja 50km/h also umgerechnet auf deine zeiteinheit 0,02h/km ..... wenn es da keinen bezug zu einer läge gäbe ist es keine geschwindigkeit, denn
geschwindigkeit = weg/zeit

aber ok ;-)

**Comment by SKB-CGN** [comment]
Es besteht auch kein Bezug zu einer Länge. Es kann auch einfach eine Zeit sein, die eine gewisse Dauer hat.

Du kannst Dich gerne mit den Dingen auseinandersetzen, wenn es dich so brennend interessiert und dann einen Bezug herstellen.

https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration

**Comment by BenAhrdt** [comment]
Ja, ich weiß, was Du meinst.... die Dauer der Animation... aber die ist eben auf dem Bildschirm ne bestimmte stecke lang.
bei gleicher höhe, passt dass. alles gut.

**Comment by SKB-CGN** [comment]
Habe gerade extra für dich 2 unterschiedlich lange Linien mit exakt der gleichen Angabe für die Dauer erstellt - beide Animationen laufen genau synchron, obwohl die Linien mehr als 100% Unterschied aufweisen!

**Comment by BenAhrdt** [comment]
Danke ich habe es auch versuch. Habe verstanden wie Due es meinst.
Die Animation ist ja irgendie definiert. Ich hatte aus dem Text heraus interpretiert, dass die dauer die zeit ist von anfang bis ende der linie. dem ist ja nicht so.

**Comment by SKB-CGN** [comment]
> Ich hatte aus dem Text heraus interpretiert, dass die dauer die zeit ist von anfang bis ende der linie. dem ist ja nicht so.

Genau! Es gibt keinen Anfang und Ende. Es ist nur eine Dauer.

**Comment by BenAhrdt** [comment]
Ja ok. Diese ist ja dann erst mal immer gleich (also was animiert wird) Danke

**Comment by SKB-CGN** [comment]
So ist es.

Gibt es noch Dinge, die unklar sind oder nicht funktionieren?

**Comment by BenAhrdt** [comment]
Habe nichts weiter getestet,
Da es oft mit "loading" hängen bleibt, wenn man in Bearbeitung oder live geht.
Die Animation anhand der Dauer habe ich nicht aktiviert, da
1. nicht anhand eines datenpunkts, sondern nur eine Constante geht.
2. die Animation bei der Aktivierung "Dauer" sehr ruckelt.

**Comment by SKB-CGN** [comment]
Was würde denn der Datenpunkt für die Dauer ändern?

Wenn die Animationen nicht flüssig laufen, ist dein Darstellungsequipment wohl etwas schwach auf der Brust.

Es gibt in den Einstellungen einen 'Energiesparmodus' für schwächere Geräte.

Wenn etwas bei Loading hängen bleibt, stimmt wohl etwas mit der Konfiguration nicht oder sonstige Probleme.

**Comment by BenAhrdt** [comment]
Also ich habe 16% ram last und 20% CPU... und nach einem Neustart der Instanz gehts wieder.

Der datenpunkt soll nicht zur dauer, sondern ich hätte gerne einen datenpunkt für den maxwert.
Da könnte ich den Verbrauch drauf legen

**Comment by SKB-CGN** [comment]
Auslastung ist ok, aber ist sehr seltsam.
Auch ein Neustart der Instanz ist nicht notwendig - diese hängt nicht, sondern liefert nur Daten.

Wenn der Verbrauch per Datenpunkt variable wäre, dann würde dies ja nicht viel bringen.

Maximale Leistung ist eben der Wert für die maximale angenommene Leistung. Diese per Datenpunkt zu steuern würde denn Sinn verfehlen.

**Comment by BenAhrdt** [comment]
Meiner Meinung nach nicht.
Wenn die Mindestdauer immer bei dem Wert des Verbrauchs ansteht, so würde die Dauer der Animation gut verteilt. Aber ok, wenn Du es anders siehst, dann leider nicht. ;-)

**Comment by SKB-CGN** [comment]
Aktuell ist mir tatsächlich nicht klar, was Du erreichen möchtest.

**Comment by BenAhrdt** [comment]
Habe ich so schlecht erklärt 😂.
Ich habe doch die Variable des Verbrauchs des Hauses.
Diese möchte ich als maxwert hibterlegen, sodass die gesxhwi sogleich der letzte Born von ihr abhängt

**Comment by SKB-CGN** [comment]
Ist ja so nicht gegeben.
Wenn der Max-Verbrauch variabel wäre, würde sich die Geschwindigkeit nicht passend verändern, wie es gedacht ist.

Denn: Verbrauch -> Max. 2000W -> Dauer 2000 (Linie läuft eben maximal 2000ms schnell). Bei 200W läuft die Linie eben 20.000ms. Bei 20W -> 200.000ms.

Deine Idee:
Verbrauch variabel -> (Max 600W -> aktueller Verbrauch) -> Dauer 2000 -> Linie läuft bei 600W maximal 2000ms. Bei 60W -> 20.000ms.
Verbrauch variabel -> (Max 400W -> aktueller Verbrauch) -> Dauer 2000 -> Linie läuft bei 400W maximal 2000ms Bei 40W ->
20.000ms.

So ist keine Anpassung der Geschwindigkeit gegeben, da sich die Geschwindigkeit nicht passend verändert.

**Comment by BenAhrdt** [comment]
@SKB-CGN 
NEIN. So meinte ich es nicht.... nur weil der Gesamtverbrauch sich ändert, ändern sich ja nicht verbraucher wie bspw. Fernseher, oder Kühlschrank.

Meine Idee:
Verbrauch variabel -> (Max 1000W -> aktueller Verbrauch) -> Dauer 2000 -> Linie läuft bei 1000W maximal 2000ms. Bei 100W -> 20.000ms.
Verbrauch variabel -> (Max 2000W -> aktueller Verbrauch) -> Dauer 2000 -> Linie läuft bei 2000W maximal 2000ms Bei 100W ->
40.000ms.

**Comment by SKB-CGN** [comment]
Weiss jetzt nicht, was der Gesamtverbrauch damit zu tun hat - die maximale Leistung wird **pro** Linie eingestellt.,

**Comment by BenAhrdt** [comment]
Ich würde die einfach dann alle von Gesamtverbrauch abhängig machen. Dann haben alle den gleichen Bezug. Das ist der Sinn.

**Comment by SKB-CGN** [comment]
Und, wo ist das Problem, überall den gleichen Wert einzutragen? Ob man nun einen Datenpunkt einträgt oder eben eine Zahl.

**Comment by BenAhrdt** [comment]
Der Verbrauch ändert sich ja (bei mir alle 2s).
Er liegt in einem DP.

**Comment by SKB-CGN** [comment]
Und, wo ist jetzt das Thema, der Linie einen fixen Wert zuzuweisen?

**Comment by BenAhrdt** [comment]
Nirgends, aber ich dachte mir, dann wäre es die eine "schnelle" Geschwindigkeit für den Gesamtverbrauch... das wäre immer ein gleicher Anblick...
Aber ich kann es nicht anders erklären. Aber ist ja ok.

**Comment by SKB-CGN** [comment]
Ich habe mir dies nochmal durchgelesen und denke, ich habe nun (fast) verstanden, was Du erreichen möchtest.

Kann es sein, das die Geschwindigkeit der Linien in Abhängigkeit des gesamten Verbrauchs gebracht werden sollen, damit diese Millisekunden genau aufeinander abgestimmt sind und somit ein Versatz von ein paar Sekunden vermieden wird?

**Comment by BenAhrdt** [comment]
Ich möchte einfach nur, dass die mir Mindestdauer der Animationen immer vom Verbrauch des Hauses erreicht wird.
Wenn es eine Linie bspw. Eine Linie gibt, die 1/3 des Hausverbrauchs ausmacht, dann soll die IMMER (unabhängig wieviel der Verbrauch ist) 3 mal die Mindestdauer für ihre Animation brauchen.
Das würde man erreichen, wenn man für den Maxwert einen Datenpunkt nehmen könnte.

**Comment by SKB-CGN** [comment]
Von mir aus soll's via Datenpunkt machbar sein.

Wann ich dazu komme, weiss ich allerdings nicht.

**Comment by SKB-CGN** [comment]
Wenn dem von deiner Seite nichts mehr hinzuzufügen ist, kannst Du das Issue gerne schließen.

**Comment by BenAhrdt** [comment]
> Von mir aus soll's via Datenpunkt machbar sein.
> 
> Wann ich dazu komme, weiss ich allerdings nicht.

Hi. Hattest Du hierzu schon was gemacht?

**Comment by SKB-CGN** [comment]
Inzwischen sind dazu keine weiteren Anfragen reingekommen - daher habe ich das Thema nicht weiter verfolgt.

**Comment by BenAhrdt** [comment]
> Inzwischen sind dazu keine weiteren Anfragen reingekommen - daher habe ich das Thema nicht weiter verfolgt.

schade
