### ISSUE TITLE
0.5.1-alpha.4 - Eigenschaften-Fenster öffnet nicht nach Verschieben

### ISSUE THREAD

**Issue by RoberWi** [SKB-CGN/ioBroker.energiefluss-erweitert#232]
**Describe the bug**  
Nur ein ganz kleiner Bug in der Bedienung.

Nach dem manuellen Verschieben mit den Cursor-Tasten öffnet das Eigenschaften-Fenster mit Single-Click nicht mehr. Ein Doppel-Click ist aber die Lösung, danach geht auch der Single-Click wieder.

**To Reproduce**  
1. Ein Element einfach anklicken -> Eigenschaftenfenster öffnet
2. Das angeklickte Element mit den Cursor-Tasten verschieben -> Eigenschaftenfenster schließt sich, Element wird verschoben.
3. Irgendein anderes Element einfach anklicken -> Kein Eigenschaften-Fenster.

Lösung:
Das neue Elemente doppelt anklicken, danach funktioniert auch der einfache Klick wieder.

**Versions:**  
 - Adapter version: 0.5.1-alpha.4

**Comment by SKB-CGN** [comment]
Schaue ich mir an. Danke!

**Comment by SKB-CGN** [comment]
Hi,
kannst Du die aktuelle Version nochmals installieren und schauen, ob der Fehler weg ist?

**Comment by RoberWi** [comment]
Mache ich morgen, melde mich wieder.

**Comment by RoberWi** [comment]
Ich finde hier nur .4 v on letzter Woche. Meinst Du, ich soll die ein zweites Mal installieren? Oder gibt es noch eine neue .5?

**Comment by SKB-CGN** [comment]
Einfach nochmals die gleiche Version drüber installieren.
Ich bringe nicht für jeden Punkt eine Version, sondern sammele sie. Dann, wenn die User sich positiv zurückmelden, erscheint eine neue Version.

**Comment by RoberWi** [comment]
OK, ich bin es aus beruflichen Gründen gewohnt, solche DInger herunterzuladen und reinzuschauen. Die Installation via URL hat funktioniert und der Fehler ist weg.

**CLOSED**
