### ISSUE TITLE
Another web-instance

### ISSUE THREAD

**Issue by HackyPaddy** [SKB-CGN/ioBroker.energiefluss-erweitert#254]
Hey,

I would like to use a specific web-instance for the energiefluss-erweitert adaper.
I created a new instance, but how do I set it up in the adapter?

The adapter use port 8082, but the new instance are using port 8083.

Thx for help!

**Comment by SKB-CGN** [comment]
Hi,
please comment, if the issue is still occuring or close it, if the problem is solved!

Thank you!
