### ISSUE TITLE
wrong calculation of two values (W and kW)

### ISSUE THREAD

**Issue by x-Rainer-x** [SKB-CGN/ioBroker.energiefluss-erweitert#258]
**Describe the bug**  
The result of the calculation of two values (value1=1000W - value2=1kW) is 1001W

**To Reproduce**  
1. create in iobroker datapoint (example 0_userdata.0.W1) with the value 1000 with unit W
2. create in iobroker datapoint (example 0_userdata.0.W2) with the value 1 with unit kW
3. in the energiefluss adapter add a datapoint example 0_userdata.0.W1 and summerize on extension tab the 2nd value W2
4. the result is 1001W but it should be 2000W

**Versions:**  
 - Adapter version: 0.5.1-alpha9
 - JS-Controller version: 6.0.11
 - Node version: v18.20.4
 - Operating system: Debian GNU/Linux 10 (buster)

**Comment by SKB-CGN** [comment]
Hello, please close the issue if solved otherwise let me know, if the issue persists.

**Comment by SKB-CGN** [comment]
No feedback. Issue closed!
