### ISSUE TITLE
Feature request: Ausblenden des Animationspfades bei Inaktivität

### ISSUE THREAD

**Issue by danickel** [SKB-CGN/ioBroker.energiefluss-erweitert#263]
Super Adapter mit nahezu endlosen Konfigurationsmöglichkeiten.

Einen Wunsch hätte ich jedoch bzw. falls es schon irgendwie geht eine Frage:
Wäre es möglich wieder eine Option einzubauen die Linie nur bei laufender Animation anzuzeigen?

![image](https://github.com/user-attachments/assets/0f3a43d8-0b32-4847-8384-497876ac0283)

Danke!

**Comment by SKB-CGN** [comment]
Ja, geht mit CSS.

Wie das geht, steht im Wiki oder im Forum von ioBroker.

**Comment by SKB-CGN** [comment]
Ich werde hierzu noch eine Erweiterung hinzufügen, damit man es ohne CSS Wissen anwenden kann.

**Comment by SKB-CGN** [comment]
Hallo,
dein Feature-Request wurde in der aktuellen Version berücksichtigt.

Bitte diese Version installieren und zurückmelden, ob das Feature so funktioniert.

Vielen Dank!
