### ISSUE TITLE
Schattenfarbe wird nicht übernommen

### ISSUE THREAD

**Issue by danickel** [SKB-CGN/ioBroker.energiefluss-erweitert#264]
Wenn man die Schattenfarbe einer Linie einstellt:
![image](https://github.com/user-attachments/assets/f069bec6-93e3-4b2d-b4ec-847654b8cd42)

Verschwindet diese wenn der Dialog geschlossen und wieder geöffnet wird:
![image](https://github.com/user-attachments/assets/961eb1c2-c703-42bb-a1cb-a76d4feb45a7)

Die Schattenfarbe in der Vorschau bleibt jedoch bestehen.
Wenn man dann in den Liveview schaltet, wird die Schattenfarbe nicht angezeigt:
![image](https://github.com/user-attachments/assets/d83e9dba-9ad8-423a-bd9a-256494ad4b66)

Verwendet wird die 0.5.1 alpha.9

**Comment by SKB-CGN** [comment]
Danke, ist bereits bekannt.

**Comment by Bullet586** [comment]
Ich hab das gleiche Problem! Aber nur auf Apple Geräten! Am PC wird der Schatten sauber angezeigt!
PC:
![image](https://github.com/user-attachments/assets/58552ed8-b7a1-457b-af5e-eadc3d8d5e4c)

iPad:
![image](https://github.com/user-attachments/assets/1c40c675-d7fa-4ae3-9c45-097f097761b5)

**Comment by SKB-CGN** [comment]
@Bullet586 dies sind 2 verschiedene Dehler!

Bei @danickel wird die Farbe nicht gespeichert - bei dir erscheint die Schattenfarbe azf Apple Geräten nicht

**Comment by Bullet586** [comment]
Ja stimmt wer lesen kann ist klar im Vorteil. Ich mach ein neues Ticket auf

**Comment by SKB-CGN** [comment]
Würde schon reichen, wenn Du die aktuelle Version installierst - da erst kam die Unterstützung für Schatten auf Apple.

**Comment by SKB-CGN** [comment]
Hallo,
dein Issue wurde in der aktuellen Version berücksichtigt.

Bitte diese Version installieren und zurückmelden, ob der Fehler behoben wurde.

Vielen Dank!
