### ISSUE TITLE
Schatten wird nicht auf Apple Geräten dargestellt!!

### ISSUE THREAD

**Issue by Bullet586** [SKB-CGN/ioBroker.energiefluss-erweitert#266]
Hi, ich bekomm die Schatten Funktion nicht auf Apple Geräten angezeigt, via Web mit dem PC wird es sauber dargestellt von Apple Geräten aus nicht. Vielleicht hat jemand ne Idee woran das liegen könnte.

Pc:
![image](https://github.com/user-attachments/assets/5478e448-f309-4d29-98ef-9919b03ec5ec)

iPad:
![image](https://github.com/user-attachments/assets/eade2833-a967-4339-a201-ab4444ef1df0)

Installierte Adapter Version 0.4.1

**Comment by SKB-CGN** [comment]
Für die Schatten bei Apple benötigst du die Alpha9 Version - zu installieren via GitHub.

**Comment by Bullet586** [comment]
Gerade auf Alpha9 Update gemacht! Funktioniert jetzt einwandfrei.

Vielen Dank für super schnelle Support!

**Comment by SKB-CGN** [comment]
Wenn der Fehler weg ist, bitte das Issue schließen.

Du kannst allerdings mit der Version aktuell keine Schatten ändern - das ist in der kommenden Version behoben.

**Comment by Bullet586** [comment]
Kann ich erstmal damit leben. Aber warum werden die Updates nicht im IOB angeboten?
