### ISSUE TITLE
Energiefluss-erweitert lässt sich nicht mehr aufrufen

### ISSUE THREAD

**Issue by Meintre** [SKB-CGN/ioBroker.energiefluss-erweitert#271]
Hallo,

ich habe leider einen Fehler begangen!
Wollte Vis.0 löschen, da ich nur noch Vis-2 benutze. Konnte aber nicht löschen, da vis-colorpicker.0 benutzt wird. Also vis-colorpicker.0 gelöscht. Wurden immer mehr, darum vis-colorpicker.0 wieder installiert und Vis.0 deaktiviert.
Alles funktioniert noch außer der Energiefluss-erweitert Adapter. 
Habe ihn schon gelöscht und wieder neu installiert, ohne Erfolg. Habe eine zweite Instanz von Energiefluss-erweitert.1 installiert, funktioniert auch nicht.

Kann mir jemand helfen?
Iobroker läuft auf eine MacBook.
<img width="1503" alt="Bildschirmfoto 2024-10-27 um 09 41 34" src="https://github.com/user-attachments/assets/39a3e49b-0397-4d63-8017-94ac98023c4f">
<img width="1153" alt="Bildschirmfoto 2024-10-27 um 09 43 09" src="https://github.com/user-attachments/assets/f24b1851-45b4-49ff-9637-15ab733a9a25">
<img width="1144" alt="Bildschirmfoto 2024-10-27 um 09 43 26" src="https://github.com/user-attachments/assets/a9650031-c8e4-45ba-908c-f7b7c96fcacb">
<img width="519" alt="Bildschirmfoto 2024-10-27 um 10 25 16" src="https://github.com/user-attachments/assets/3afc4f13-bb09-42e9-99db-e352a8704acf">

**Comment by SKB-CGN** [comment]
Hallo,
das sind Fehler aus dem socket.io bzw. Web Adapter und hat mit dem EF Adapter leider nichts zu tun.

**Comment by Meintre** [comment]
Was kann ich tun?  Die beiden Web Adapter Laufen und ich kann auch Vis-2 und Flot aufrufen!

**Comment by SKB-CGN** [comment]
Was sagt denn die Browserkonsole?

**Comment by Meintre** [comment]
Die sagt folgendes: 
<img width="1096" alt="Bildschirmfoto 2024-10-27 um 13 57 59" src="https://github.com/user-attachments/assets/14896e94-7cfb-4a25-9e5e-8773fb47c8c1">

**Comment by SKB-CGN** [comment]
Wie ist der Web-Adapter konfiguriert?

**Comment by Meintre** [comment]
WEB und WS Adapter
<img width="1102" alt="Bildschirmfoto 2024-10-27 um 14 08 16" src="https://github.com/user-attachments/assets/4abf4a98-fc0d-4e62-9ea6-6949bb26da91">
<img width="1107" alt="Bildschirmfoto 2024-10-27 um 14 08 33" src="https://github.com/user-attachments/assets/8aad5bd9-b794-45da-9cf4-f5f695682bcb">
<img width="1398" alt="Bildschirmfoto 2024-10-27 um 14 08 53" src="https://github.com/user-attachments/assets/d236f73e-af81-45ce-a4ab-327c825f5cfe">

**Comment by SKB-CGN** [comment]
Den Web-Adapter musst du für den EF Adapter auf "integriert" und nicht ws stellen.

**Comment by Meintre** [comment]
Habe den Fehler gefunden Haken bei "Reine Web-Sockets (iobroker.ws) verwenden" vergessen!
Nun doch noch eine Frage: Kann ich ein Backup einspielen und wie? Habe jetzt den leeren Energiefluss erweitert Adapter!

**Comment by Meintre** [comment]
Habe es schon wieder hinbekommen. Danke für die Hilfe!!!!!!!!

**Comment by SKB-CGN** [comment]
Prima, wenn alles wieder läuft, kannst Du das Issue schließen!
