### ISSUE TITLE
Data not updated in LiveView

### ISSUE THREAD

**Issue by emeins** [SKB-CGN/ioBroker.energiefluss-erweitert#274]
### Describe the bug

My data are not updated in the LiveView.

### Steps to reproduce

I defined several data sources without any calculation. When I add or edit these entries in the configuration interface the values are shown correctly. When I save and leave the configuration interface the values are also looking fine in the LiveView. Unfortunately they are not updated anymore and stay as they are.

### Expected behavior

I expected that the data are updated as soon as the source value changes in iobroker object.

### Additional Information

I tested already the following:
- Chrome, Safari on MacOS, Safari on IOS
- Refresh the web page
- socket.io in iobroker enabled & disabled
- no log entries or other errors are popping up

iobroker is running in a Docker container incl. bridge and macvlan network connection.

### Version

0.5.1-alpha.10

**Comment by emeins** [comment]
Just realized that I updated my scripted aliases in the wrong way. When I catch the values directly from the source it works well.

**Comment by SKB-CGN** [comment]
The adapter works with alias as well - was it not working for you like this?

**Comment by emeins** [comment]
Sorry, was not about a "real" alias.

The problem was that only acknowledged (ack = true) values are updated in the LiveView. At the same time I'm run a mqtt adapter for the same values. But in the default configuration it needs them as _**not**_ acknowledged (ack = false) values.

Now I changed the mqtt configuration and my scripts so all values I am using are acknowledged now und the update in LiveView looks also good.
