### ISSUE TITLE
Second Battery in calculations

### ISSUE THREAD

**Issue by Kaschi68** [SKB-CGN/ioBroker.energiefluss-erweitert#277]
### Describe, what you want to be added!

I would like to be able to use a second battery in the calculations. Example with my Goodwe ET29.9. Thank you

### Describe the solution you'd like

Nothing

### Describe alternatives you've considered

Nothing

### Additional Information

Nothing

**Comment by SKB-CGN** [comment]
Do you mean a second battery to be calculated, how long the runtime for it is?

**Comment by Kaschi68** [comment]
Yes, calculate runtime AND consumption.

**Comment by SKB-CGN** [comment]
Understand - but i think, this is a very special request, as nearly all users have one battery.

**Comment by jonnycastaway** [comment]
I think this is nothing really special.
I have the same question. Using 2 Hame B2500 and would like to use both in calculation.
The prices for small usage Batterys dropping and the probability to use more than one Battery gets higher and higher.
I'm thinking about a third one.

So, the possibility to use N Battery Systems for calculation would really helpful.
