### ISSUE TITLE
[Feature Request]: Animationen auch bei Wert = True/False

### ISSUE THREAD

**Issue by Senfruecken** [SKB-CGN/ioBroker.energiefluss-erweitert#278]
### Describe, what you want to be added!

Hallo, 
es wäre vielleicht hilfreich, wenn die Animationen auch bei einem Wert: True stattfinden könnten. Aktuell ist nur "Anitmation wenn Quelle: Positiv/Negativ" möglich.
Ich nutze Geräte die keine Verbrauchwerte zurückmelden z.b. HomeConnet oder normale Tasmota/Shelly. Um die Darstellung zu erweitern welche Geräte gerade am Energiefluss beteiligt sind und welche nicht, wäre das eine gute Ergänzung. 

zB: Unsere Darstellung: Spülmaschine siehe Add.Infos

### Describe the solution you'd like

Anitmation wenn Quelle: Positiv/Negativ + True/False

### Describe alternatives you've considered

Ich habe versucht es über andere Werte zu lösen, z.b. einen eigenen Alias mit Skript.
D.h. wenn Wert= True > Alias=1 | Wert=False > Alias=-1

Aber das ist viel workaround

### Additional Information

Hier mal die Ansicht der Spülmaschine:

![Screenshot_20241106_121625_Chrome](https://github.com/user-attachments/assets/5a5f2bb4-7d05-4b9f-9a9c-5576b717187a)

**Comment by SKB-CGN** [comment]
Hallo,
das wird bereits berücksichtigt. Einen Bool Wert zuweisen, "Animieren, wenn Quelle" positiv. Schwellenwert auf 0.
Dann bekommt dieser automatisch eine "1" (bei Bool true) und schon wird animiert. Bei "0" (Bool false) wird die Animation gestoppt.

**Comment by Senfruecken** [comment]
OK, danke für die schnelle Rückmeldung.
Ich hatte den Schwellwert, als mindestens Wert genutzt.


Evtl. in den docs erweitern als Info 😉
Animation:

 -Anpassbar (Farbe der Punkte, Farbe der Linie)
 - positiver oder negativer Datenpunkt Wert (Bool über Schwellwert=1)
 - Schwellenwert moeglich

**Comment by SKB-CGN** [comment]
Was genau hättest Du gerne in den Docs erweitert?
