### ISSUE TITLE
[Bug]: Zeitstempel statt Zeitpunkt letzte Änderung

### ISSUE THREAD

**Issue by wdill** [SKB-CGN/ioBroker.energiefluss-erweitert#279]
### Describe the bug

In der Element-Konfiguration kann man ja unter "Optionen für Datenquelle" den "Zeitstempel der letzten Änderung" anzeigen lassen (z.B. mit "bezogen auf jetzt").
Das Ergebnis ist aber nicht der Zeitpunkt der letzten **Änderung/Last Changed**, sondern der letzten **Aktualisierung/Time Stamp**.
Entweder ist also die Überschrift irreführend bis falsch, oder der gelieferte Wert :-)

Vorschlag: Beide Werte zur Auswahl anbieten.

P.S.: Super Adapter! 

### Steps to reproduce

2. Click on '...'

### Expected behavior

1.
2.
3.
...

### Additional Information

![Screenshot_20241109_141118](https://github.com/user-attachments/assets/70fcddc1-be0d-4c11-9063-f586ce5cb998)

### Version

v0.5.1-alpha.10

**Comment by SKB-CGN** [comment]
Danke für den Hinweis!
Schaue ich mir an!

**Comment by SKB-CGN** [comment]
Hallo,
dein Issue wurde in der aktuellen Version behandelt.
Bitte schaue einmal rein, ob das Problem behoben wurde und schließe das Issue in diesem Falle.

Vielen Dank im Voraus!

**Comment by wdill** [comment]
Auch Hallo,

habe es gerade getestet - grundsätzlich scheint es auch zu funktionieren.
Allerdings habe ich den Eindruck, dass bei Auswahl der Darstellungsform "Bezogen auf jetzt" immer noch auf Grundlage des letzten Aktualisierungsdatums berechnet wird - auch für den Wert "Letztes Änderungsdatum".
Bei Darstellung in einem fixen Zeitformat (also z.B. "Zeitstempel DE") wird das letzte Änderungsdatum aber richtig angezeigt.

**Comment by SKB-CGN** [comment]
Ich denke, ich weiss, was Du meinst - kann es sein, das Dich ggf. die Textform z.B. 1 Stunde irritiert, wenn die Änderung vor 1.5h war? Hier wollte ich noch einige Texte mehr einbauen, damit es besser wird.

**Comment by SKB-CGN** [comment]
Du hast natürlich vollkommen Recht (allerdings bedingt 😉).

Es wurde für Datenpunkte, die sich lange nicht geändert haben, immer noch der ts Wert genutzt. 

Du kannst gerne nochmals drüber installieren - dann sollten die Werte stimmen!

**Comment by SKB-CGN** [comment]
So, Fehler gefunden und behoben. Du kannst jetzt gerne nochmals direkt von Github von "https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/" installieren. Dann sollten die Werte passen!

**Comment by wdill** [comment]
Sieht gut aus.
Ich schaue morgen nochmal genauer drauf, aber ich denke es passt so.

Herzlichen Dank!

**Comment by SKB-CGN** [comment]
Sehr gut!

Ich danke Dir - melde dich gerne zurück, falls etwas nicht funktionieren sollte!

**Comment by wdill** [comment]
Alles so wie erwartet - ich bin glücklich :-) 
Nochmal Danke für die schnelle Reaktion!

Mache den issue dann jetzt zu
