### ISSUE TITLE
Problem: Keine Datenanzeige

### ISSUE THREAD

**Issue by incase** [SKB-CGN/ioBroker.energiefluss-erweitert#32]
(Version gestern abend aktualisiert, iobroker zeigt version 0.0.2-alpha.10

Keine Ahnung, was genau schief läuft. Für Hinweise zum Debugging wäre ich dankbar. Irgendwie ist für mich "functions.min.js:1" nicht sonderlich hilfreich. Ein Javascript beautifier macht aus der einen Zeile mal eben 2492 Zeilen.

Hmm, ich habe es scheinbar bis in diesen Teiler einer anonymem function zurückverfolgt:
```
            if (null != t[objID[1]]) try {                                       
                console.log("Loading initial Data."), refreshData(JSON.parse(t[objID[1]].val))
            } catch (o) {                                                        
                console.log(o)                                                   
            }                    
```
(Im CallBack für `e.emit("getStates", objID, function(...){...}`)

Das Javascript-Console-log in Chrome zeigt:

```
Using Instance: energiefluss-erweitert.0
about:blank:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
functions.min.js:1 Loading config for instance: 0
functions.min.js:1 Loading User Config ...
functions.min.js:1 [Socket] subscribed to: energiefluss-erweitert.0.configuration,energiefluss-erweitert.0.data,system.adapter.energiefluss-erweitert.0.alive,energiefluss-erweitert.0.backup at 7/13/2023, 11:40:36 AM
functions.min.js:1 Loading initial Data.
functions.min.js:1 TypeError: Cannot read properties of undefined (reading '0')
    at functions.min.js:1:6669
    at Array.forEach (<anonymous>)
    at refreshData (functions.min.js:1:6627)
    at r.<anonymous> (functions.min.js:1:9814)
    at r.onack (index.js:83:1)
    at r.onpacket (index.js:83:1)
    at r.<anonymous> (index.js:83:1)
    at r.emit (index.js:83:1)
    at r.ondecoded (index.js:83:1)
    at a.<anonymous> (index.js:83:1)
37functions.min.js:1 Error while parsing Values in JSON-Object!
```

Hier ist der Output wenn ich speichere, was ich aktuell konfiguriert habe (extra reduziert):
```
{
    "basic": {
        "enable_grid": true,
        "enable_animation": true,
        "enable_area_catch": true,
        "enable_config_icon": true,
        "enable_last_id": false,
        "height": 720,
        "width": 1280,
        "styles": "",
        "font": {
            "family": "\"Arial\", sans-serif",
            "size": "20",
            "color": "",
            "fill": "",
            "align": "end"
        },
        "rect": {
            "height": 100,
            "width": 100,
            "corners": 10
        },
        "circle": {
            "radius": 50
        },
        "elm": {
            "stroke_width": 5,
            "color": "",
            "fill": "",
            "pos_x": null,
            "pos_y": null
        },
        "icon": {
            "height": 24,
            "width": 24,
            "color": ""
        }
    },
    "calculation": {
        "battery": {
            "dod": 0,
            "capacity": 0,
            "percent": null,
            "charge": null,
            "charge_prop": false,
            "charge_kw": false,
            "discharge": null,
            "discharge_prop": false,
            "discharge_kw": false
        }
    },
    "animation": {
        "stroke": "#ffce4a",
        "stroke_dasharray": "10 17 10 17 10  72",
        "stroke_width": "6",
        "animation_duration": "2000",
        "stroke_linecap": "round",
        "animation_timing_function": "linear"
    },
    "animation_configuration": {
        "dots": "3",
        "distance": "17",
        "length": "10"
    },
    "line": {
        "stroke_width": "8",
        "stroke": "#000000"
    },
    "elements": {
        "0": {
            "type": "text",
            "subType": "datasource",
            "id": 0,
            "pos_x": 109,
            "pos_y": 89,
            "color": "none",
            "fill": "rgb(53, 44, 26)",
            "font_family": "Arial, sans-serif",
            "font_size": 20,
            "degree": 0,
            "align": "start",
            "text": "ID 0",
            "unit": "kW",
            "append": "",
            "prepend": "",
            "source": 11,
            "source_option": "timestamp_de_short_wo_year",
            "source_display": "value",
            "shadow": "",
            "threshold": 0,
            "calculate_kw": false,
            "convert": false,
            "decimal_places": 0,
            "subtract": [
                -1
            ],
            "css_general": "",
            "css_active_positive": "",
            "css_inactive_positive": "",
            "css_active_negative": "",
            "css_inactive_negative": ""
        },
        "1": {
            "type": "text",
            "id": 1,
            "pos_x": 89,
            "pos_y": 59,
            "color": "none",
            "fill": "rgb(94, 6, 211)",
            "font_family": "Arial, sans-serif",
            "font_size": 20,
            "degree": 0,
            "align": "start",
            "text": "BYD consumption",
            "shadow": "",
            "css_general": ""
        }
    },
    "defs": {},
    "lines": {},
    "animations": {},
    "datasources": {
        "11": {
            "source": "loxone.2.1a12582e-02a7-e3a1-ffff112233445566.actual",
            "alias": "BYD_LVL_Consumption"
        }
    }
}
```

**Comment by SKB-CGN** [comment]
Schau mal in den Datenpunkt
`energiefluss-erweitert.<Instance>.data`

Steht dort etwas drin?
Wenn nicht, hat der Adapter noch keine Ausgabe generiert, die gelesen werden kann/konnte.

**Comment by incase** [comment]
The error message changed slightly (0 -> 34):
```
TypeError: Cannot read properties of undefined (reading '34')
    at functions.min.js:1:6669
    at Array.forEach (<anonymous>)
    at refreshData (functions.min.js:1:6627)
    at r.<anonymous> (functions.min.js:1:9814)
    at r.onack (index.js:83:1)
    at r.onpacket (index.js:83:1)
    at r.<anonymous> (index.js:83:1)
    at r.emit (index.js:83:1)
    at r.ondecoded (index.js:83:1)
    at a.<anonymous> (index.js:83:1)
```

Der Inhalt von  `value` des energiefluss-erweitert.0.data Objekts in iobroker selbst: Siehe angehängte Datei.

[value.txt](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/files/12041472/value.txt)

**Comment by incase** [comment]
Sorry, sollte nicht geschlossen werden.

**Comment by incase** [comment]
Oh, natürlich ist die Fehlermeldung jetzt anders, ich habe wieder auf meine vorherige (größere) Config zurück geschaltet (Danke übrigens, für die Backup/Restore Möglichkeit)

**Comment by SKB-CGN** [comment]
Anscheinend kann das Element 34 nicht gelesen werden.
Schaue ich mir Morgen am Rechner an.

**Comment by incase** [comment]
Interestingly: I can't seem to reproduce this with a second instance of the adapter.-

**Comment by incase** [comment]
Oh, mein, Gott. Ich habe rausgefunden was los ist. Oder zumindestens eine Brotkrume, die in die richtige Richtung weist:

Ich habe *zwei* ioBroker Instanzen (eine auf einem Raspberry Pi, primär für Zigbee, eine in einem Docker-Container, primär für diverse Scripte, alles was Modbus TCP ist, ...). Und ich habe auf das Web-Interface über den Pi benutzt. Die Instanz mit dem Fehler lief aber auf dem Docker-Container (keine Ahnung, wieso ich trotzdem problemlos auf das Web-Interface zugreifen und die Config anpassen konnte und alles außer dynamischen Daten im eigentlichen Energiefluss-Diagramm sehen konnte). Die Instanz ohne den Fehler hatte ioBroker automatisch auf dem Pi gestartet.

Schiebe ich die Instanz ohne Fehler auf den Docker-Container, habe ich plötzlich den Fehler. Schiebe ich die ursprünglich fehlerhafte Instanz auf den Pi, geht der Fehler weg. (Mehr kann ich aktuell nicht gut testen, weil der Container Port 8082 nicht exportiert, müsste ich erst ändern, was leider bei unserem Setup nicht so trivial ist, wie es klingt).

Ich kann jetzt nicht ohne weiteres auf die alte Version zurück gehen, aber ich bin mir relativ sicher, dass das Problem damit nicht so auftrat. Kann es sein, dass irgendwas am Zugriff auf die relevanten Daten anders geworden ist und nun unbedingt auf dem gleichen Host geschehen muss? Also dass die relevante Instanz von Web auf dem gleichen Host liegen muss wie die Instanz von energiefluss-erweitert?

**Comment by SKB-CGN** [comment]
So, wie ich es aktuell lese, könnte das mit dem Web-Adapter zu tun haben, der auf Websockets (socket.io) läuft und nicht auf integriert.

Kannst Du dies verifizieren?

Mit socket.io klappt es nämlich nicht.

**Comment by incase** [comment]
Hi. Beide web.x Adapter stehen auf "itegrated" (sic!), nicht auf socket.io oder Websockets. Bin gerade im Büro und komm nicht an meinen Screenshot. Sag Bescheid, falls der helfen würde.

**Comment by SKB-CGN** [comment]
Und was sagt die Browserkonsole?
Screenshots helfen immer.
Ist die Checkbox für Websockets aktiv?

**Comment by incase** [comment]
ioBroker zeigt zwar "itegrated" statt "integrated", aber beide Webserver sind gleich eingestellt:

![Screenshot from 2023-07-18 10-18-23](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/953468/b4eea17e-aa31-4486-862d-9fbd8ff8e169)

Die Checkbox by "pure websockets"? Nein, nicht aktiv.

Browserkonsole: Nach was soll ich schauen? Das hier ist der vollständige Output, den ich auf der Javascript-Console in Chrome sehe, wenn ich die (absichtlich "auf dem falschen iobroker" - also der Docker Instanz - laufende) energiefluss-erweitert.1 Instanz über die auf dem Raspberry-Pi laufende web.0 Instanz anspreche. Randnotiz: Wie schon erwähnt, ist die auf dem Doker-Container (ioBroker-docker) laufende web.1 Instanz *nicht* von meinem Browser aus zu erreichen.

```
Using Instance: energiefluss-erweitert.1
about:blank:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
functions.min.js:1 Loading config for instance: 1
functions.min.js:1 Loading User Config ...
functions.min.js:1 [Socket] subscribed to: energiefluss-erweitert.1.configuration,energiefluss-erweitert.1.data,system.adapter.energiefluss-erweitert.1.alive,energiefluss-erweitert.1.backup at 7/21/2023, 1:42:51 PM
functions.min.js:1 Loading initial Data.
functions.min.js:1 TypeError: Cannot read properties of undefined (reading '1')
    at functions.min.js:1:6669
    at Array.forEach (<anonymous>)
    at refreshData (functions.min.js:1:6627)
    at r.<anonymous> (functions.min.js:1:9814)
    at r.onack (index.js:83:1)
    at r.onpacket (index.js:83:1)
    at r.<anonymous> (index.js:83:1)
    at r.emit (index.js:83:1)
    at r.ondecoded (index.js:83:1)
    at a.<anonymous> (index.js:83:1)
5functions.min.js:1 Error while parsing Values in JSON-Object!
```

**Comment by SKB-CGN** [comment]
Hast Du denn einmal die neue Version von hier installiert und einen upload gemacht?

`/opt/iobroker`
`upload energiefluss-erweitert`

**Comment by SKB-CGN** [comment]
Kleine Anpassungen im Code sind einfach verfügbar - die dokumentiere ich nicht.
Dies passe ich mit Hilfe der Rückmeldungen an, die ich bekomme.

Erklären könnte dies, ich habe einen Datenpunkt umgestellt und bei diesem fehlte ein Standard-Wert. Ohne diesen Wert kann das Array nicht gelesen werden.

**Comment by incase** [comment]
Klingt irgendwie nach dem Fehler (couldn't read value of undefined). Danke!
