### ISSUE TITLE
Startprobleme bei Neuinstallation

### ISSUE THREAD

**Issue by Ezak2** [SKB-CGN/ioBroker.energiefluss-erweitert#35]
Hallo SKB,
habe mit der letzten Version auch 2 Tage umhergespielt ohne Erfolg. Seit dem Update in der "12" heute Mittag funktioniert es auch in Termux auf einem Android Tablet. Ich habe auch mehrmals gelöscht und drüberinstalliert hat nicht funktioniert. 
Das muss komplett aus den "Adaptern" gelöscht werden inclusive der Objekte zum Adapter. Danach per Katze über den Link neu installieren und dann den "neuen" Adapter aktivieren (install) . Danach ist alles ok. Habe im iob Forum mitgelesen habe da aber keinen Account daher hier die Info.

**Comment by SKB-CGN** [comment]
Hallo,
es reicht eine erneute Installation über GitHub und ein Upload vollkommen aus.
