### ISSUE TITLE
Undo (Ausrichtung) in falscher Reihenfolge

### ISSUE THREAD

**Issue by incase** [SKB-CGN/ioBroker.energiefluss-erweitert#37]
Ich habe gerade drei Elemente nacheinander an dem gleichen Referenzobjekt ausgerichtet. Ich wollte beim letzten wieder zur ursprünglichen Positionierung zurück, habe also auf Undo geklickt. Zu meiner Überraschung wurde das erste ausgerichtete Objekt wieder zurück auf die Ausgangsposition gesetzt, dann das zweite und als letztes das auch ursprünglich zuletzt ausgerichtete Objekt. Ablauf war also:

- Click auf horizontale Zentrierung
- Click auf Referenzobjekt
- Click auf Objekt A
- Click auf Objekt B
- Click auf Objekt C
- Click auf Undo -> A wieder auf Ausgangsposition
- Click auf Undo -> B wieder zurück
- Click auf Undo -> C wieder zurück

Erwartet hätte ich Undo in der Reihenfolge C, B, A.

**Comment by SKB-CGN** [comment]
Da hast Du natürlich vollkommen Recht. Danke für den Hinweis!

Habe ich für die nächste Version notiert.
