### ISSUE TITLE
Cpu use extremly high ( solved )  

### ISSUE THREAD

**Issue by TJHooker** [SKB-CGN/ioBroker.energiefluss-erweitert#43]
Since adding calculation usage extreme high cpu use on rpi 4 with Debian 12 Upgrade will try downgrade off OS and report

it happens with the v0.0.2-alpha.14 

**Versions:**  
 Plattform
linux
Betriebssystem
linux
Architektur
arm64
CPUs
4
Geschwindigkeit
1800 MHz
Modell
Cortex-A72
RAM
7.63 GB
System-Betriebszeit
08:46:20
Node.js
v18.13.0 (Es gibt eine neuere Version: v18.17.0)
time
1691556230127
timeOffset
-120
Anzahl der Adapter
488
NPM
9.2.0
Datenträgergröße
219.77 GB
freier Festplattenspeicher
133.71 GB
Betriebszeit
08:49:08
Aktive Instanzen
18
Weg
/opt/iobroker/
Hostname
pihole

here the app without Calculation  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/7ec3e8ae-3a3f-49cf-8461-e516adadcae2)
here the app with Calculation

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/9a6296f3-ffc3-4f4e-8ef0-952ba44b4a4e)

it goes so high that  the  Iobroker   in not able to deliver infos to all other  apps

**Comment by SKB-CGN** [comment]
Which CPU is high?

That one of the Pi or the client, who displays the animations?

**Comment by TJHooker** [comment]
The device where you instance off iobroker is working

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SKB-CGN** [comment]
So, the device, where you show the animations is having high cpu load?
Means?
What exactly is high?

**Comment by TJHooker** [comment]
On both on the host iobroker and end Client if i disabled the calculation it goes down

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SKB-CGN** [comment]
This is not the problem of the adapter, as it is only reacting on delivered states.
If you update the calculations to often, this might cause this error.

**Comment by TJHooker** [comment]
This didn't happen with you old adapter and usage calculation but with the battery there is the same

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SKB-CGN** [comment]
Ich kann leider sehr schlecht verstehen, was Du meinst.
Verfasse deine Sätze doch einfach auf deutsch ;)

**Comment by TJHooker** [comment]
Seit du die Berechnung im "Energiefluss erweitert" um Verbrauch Berechnung erweitert hast Alfa 14. ist auf dem Raspi (iobroker und Dein Adapter)   die Arm cpu mit der lst so hoch das im broker zu timeouts.

Und der Aufruf der iobroker Seite bzw die Anzeige deines "Energiefluss erweitert" verursacht durch die vielen Änderungen sogar im Edge eine warn Meldung.

Sobald ich die Berechnung wieder abschalten geht alles wieder runter.

Ps die Verbrauchs Berechnung im alten "Energiefluss" hatte das nicht

Allerdings die Accu Berechnung

Over all weiter so!

**Comment by SKB-CGN** [comment]
Ah, verstehe. Danke für den Hinweis!

Konnte ich eben tatsächlich nachstellen und arbeite an einem Fix.
Bis dahin den Verbrauch vielleicht vielleicht nicht nutzen :D

**Comment by SKB-CGN** [comment]
Wenn Du Zeit hast, einfach nochmal drüber installieren und gucken.
Die Einstellungen des Verbrauchs sind allerdings neu einzugeben, da noch verschiedenes dazu kam.

**Comment by Rincewind0** [comment]
Hi,
bin grade auf den Eintrag gestossen, weil ich auch das Problem mit der CPU Auslastung auf meinem Raspi hatte, sobald ich die Verbrauchsberechnung aktiviert habe.
Nach installation der alpha.15 und neuer Eingabe der Einstellungen, ist das Problem bei mir weg.
Danke!

**Comment by SKB-CGN** [comment]
Danke für die Info. Ja, manchmal steckt der Teufel im Detail.

**Comment by TJHooker** [comment]
Super Arbeit die Berechnung klappt und die last auf der CPU gering  morgen mal schauen was er aus den Werten macht die von dem ACCU bekommt ( Laden und entladen )   die berechung davon sollte ich erst mal nicht anpacken richtig ?

**Comment by SKB-CGN** [comment]
Alle Berechnungen kannst Du nutzen. Die Akku Berechnung ging vorher schon - super, wenn die Verbrauchsberechnung nun auch klappt.
