### ISSUE TITLE
Textdrehung wird mit Chrome nicht gespeichert

### ISSUE THREAD

**Issue by Rincewind0** [SKB-CGN/ioBroker.energiefluss-erweitert#44]
**Describe the bug**  
Wenn ich im Arbeitsbereich mit Google Chrome einen Text senkrecht drehe, dann speichere und in die LiveView wechsle, dann ist der Text wieder waagerecht.
Wenn ich das Ganze in Firefox mache, funktioniert das problemlos und der Text wir in der LiveView auch senkrecht dargestellt.

**To Reproduce**  
1. Text im Arbeitsbereich mit Google Chrome drehen.
2. speichern und verlassen
3. In der LiveVie ist der TExt wieder waagerecht

**Versions:**  
 - Adapter version: 0.0.2 alpha15

![Arbeitsbereich](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86548134/be554bcb-e66d-46ae-b782-60805660a285)
![LiveView](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86548134/dbd715d3-ac2c-49bd-adfa-6fc0748d3ada)

**Comment by SKB-CGN** [comment]
Danke für den Hinweis. Habe einmal etwas angepasst.

Bitte nochmal drüber installieren, prüfen und zurückmelden.

Danke :)

**Comment by Rincewind0** [comment]
Huch, jetzt ist irgendwas krumpelig.

Habs nochmal drüber installiert, aber jetzt ist das Zahnrad, um in die Einstellungen zu kommen weg.
Mit Alt+Shift+e komme ich zwar in den Arbeitsbereich aber dort fehlen alle buttons:

![Arbeitsbereich1](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86548134/90567d91-d6e9-4291-ac06-8b2f0e6c7984)

**Comment by SKB-CGN** [comment]
Was sagt die Browserkonsole mit F12?

Und der Punkt Einstellungen?

**Comment by Rincewind0** [comment]
In den Einstellungen ist der Punkt für das Konfigurationssymbol auf "on".
Habs mal ausgeschaltet und wieder eingeschaltet, da ändert sich aber nichts.

Beim Aufruf der LiveView sagt die Browserkonsole:

![Screenshot 1](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86548134/9215be72-713a-4a41-9c04-c409761d9d41)

**Comment by SKB-CGN** [comment]
Bei dir fehlen alle Icons. Auch die der Titel und den Kästchen.
Muss ich mir später einmal ansehen.

Was sagt die Browserkonsole in der Konfiguration?

Entschuldige die Umstände.

**Comment by SKB-CGN** [comment]
Habe den Fehler gefunden und hier zum Testen hochgeladen.

Einfach nochmal drüber installieren und schauen, ob es klappt.

Danke!

**Comment by Rincewind0** [comment]
Kein Problem. Damit muss man rechnen, wenn man sich ne "alpha" Version installiert ;-)

Jetzt funktioniert wieder alles. Die Icons sind wieder alle da.
Auch das Speichern des gedrehten Textes in Chrome funktioniert jetzt!

Hammer Adapter übrigens!
Ich mochte die alte Version schon, aber mit der neuen Art der Konfiguration und den damit verbundenen Möglichkeiten ist das nochmal ein ganz neues Level. Großartig!

**Comment by SKB-CGN** [comment]
Ich nenne meine Versionen Alpha, damit sie 'rechtlich' in Ordnung sind. Eigentlich sollte alles funktionieren, aber wenn Menschen Code schreiben, kann da schonmal ein Fehler passieren.

Freut mich, wenn dir der Adapter gefällt. Dafür ist er gemacht.
