### ISSUE TITLE
Hilfe zu Batterie Laufzeit

### ISSUE THREAD

**Issue by TJHooker** [SKB-CGN/ioBroker.energiefluss-erweitert#45]
**Describe the bug**  

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/9e7e7ac8-ec83-4287-82f4-ad800bf6ea18)

es wird immer nur NaN % angezeigt 

und das obwohl  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/4f52ca0f-159a-45fd-951c-43017c1afdd2)

eingestellt ist  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/b690378b-0f95-4795-a177-970385d995e5)

aber müsste  es hier nicht 
energiefluss-erweitert.x.Calculation  wie bei der Verbrachsberechnung ?

was nur  komisch ist  es erscheint  hier kein Wert hmm  (sieh grüne Schrift es werden aber  werte übertragen 
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/066ce007-20b1-439c-8e94-a8d734c35bcd)

**Comment by TJHooker** [comment]
ach kann das was damit zu tun haben  stand im Protokoll 
<html>
<body>


energiefluss-erweitert.0 | 2023-08-11 10:42:12.594 | error | Cannot read properties of undefined (reading 'elmSources')
-- | -- | -- | --
energiefluss-erweitert.0 | 2023-08-11 10:42:12.592 | error | TypeError: Cannot read properties of undefined (reading 'elmSources') at EnergieflussErweitert.onStateChange (/opt/iobroker/node_modules/iobroker.energiefluss-erweitert/main.js:591:130) at EnergieflussErweitert.emit (node:events:513:28) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5385:53) at process.processImmediate (node:internal/timers:471:21)


</body>
</html>

**Comment by SKB-CGN** [comment]
Korrekt, der Pfad zur Batterie-Laufzeit hat sich geändert.

von:
`battery_remaining`
nach
`battery.xyz`

**Comment by TJHooker** [comment]
und dann das hier aus wählen 

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/e7d798a4-28f8-4679-be9f-596cd1f36e58)
so das er hier den wert bekommt ?  
energiefluss-erweitert.0.calculation.battery.remaining

**Comment by SKB-CGN** [comment]
Genau, du kannst Remaining (Laufzeit) auswählen, für die Zeit oder Target (Linux Zeit) oder TargetDT (kurzes Datum mit Zeit)

**Comment by TJHooker** [comment]
es taucht aber weiterhin kein wert auf  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/990aed7a-a302-41fd-929b-99287a544bc8)

und das scheint er sogar  hier  zu melden 

<html>
<body>


energiefluss-erweitert.0 | 2023-08-11 11:08:10.635 | error | Cannot read properties of null (reading 'val')
-- | -- | -- | --
energiefluss-erweitert.0 | 2023-08-11 11:08:10.633 | error | TypeError: Cannot read properties of null (reading 'val') at EnergieflussErweitert.calculateBatteryRemaining (/opt/iobroker/node_modules/iobroker.energiefluss-erweitert/main.js:713:29)
energiefluss-erweitert.0 | 2023-08-11 11:08:10.631 | error | unhandled promise rejection: Cannot read properties of null (reading 'val')


</body>
</html>

**Comment by SKB-CGN** [comment]
Danke für den Text - Du hast keinen Datenpunkt für die Prozentuale Beladung angegeben.

![2023-08-11 11_19_38-Energiefluss - erweitert _Configuration_](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/60cf58ed-ab98-4358-a109-0964ebdff89d)


Den Fehler werde ich noch abfangen.

**Comment by TJHooker** [comment]
vorschlag  mach hier unter den reitern weiter Reiter  die jeweils  die Berechnungen breiter anzeigen dan sieht man die Dropdown wenigstens  und kannst  die Tips von grade  ergänzen 

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/5468bb49-a32e-461d-b82a-eaec4b0e22c7)

energiefluss-erweitert.0.calculation.battery.remaining



Genau, du kannst Remaining (Laufzeit) auswählen, für die Zeit oder Target (Linux Zeit) oder TargetDT (kurzes Datum mit Zeit)

**Comment by TJHooker** [comment]
leider doch  

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/e0fde586-90c5-4cd4-a323-3d1fb974f8cf)

**Comment by SKB-CGN** [comment]
Ja, das ist der Datenpunkt des Adapters selbst. Hier ist der der Batterie benötigt :)

**Comment by SKB-CGN** [comment]
> vorschlag mach hier unter den reitern weiter Reiter die jeweils die Berechnungen breiter anzeigen dan sieht man die Dropdown wenigstens und kannst die Tips von grade ergänzen
> 
> 

Was soll ich breiter machen?

**Comment by TJHooker** [comment]
ok das bedeutet man benötigt  die Möglichkeit  den ACCU  und seine Prozent  abzufragen  das kann mein ACCU nicht  
schade. 
Hatte es so interpretiert das  du das  berechnest  den durch die eingehende  Ladung   bzw  ausgehende  und der  Info das man die Kapazität  nennt  ist  das Theoretisch  berechenbar ( PS 2048 **wh**  Kapazität )

**Comment by SKB-CGN** [comment]
Ist so nicht kalkulierbar. Außer, man beobachtet den Wert von Ladung 0 bis Ladung 100, was im Falle eines Adapter-Absturzes bzw. Ladeunterbrechungen zu Fehlern führt.

**Comment by TJHooker** [comment]
so im etwa  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/0d306476-b13c-4cbe-b43b-bb4dafea9439)
und dann  halt auf ganze  breite   damit  die Texte  und dropdown nicht abgeschnitten sind  ( ist  nur ein Vorschlag )  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/d7650825-e89e-4b1b-86af-00078f8bf240)

**Comment by SKB-CGN** [comment]
Deine Grafik verstehe ich leider nicht. Was hättest Du gerne größer?

**Comment by TJHooker** [comment]
ok  anders  wenn ich mich rech erinnner  bist  du wegen CSS  doch hingegangen und hast ie alte  APP eingestampft   und eine vorteil von CSS  soll wenn ich mich richtig  erinnere  sein das  es sich Seite Verhältnissen  automatisch anpasst 

nutz die Breite  
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/ac39ed5d-68ab-4f78-930a-0df88dcf24a0)

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60543505/98cbb996-9b0f-4695-9d95-95754ebf2ec8)

**Comment by SKB-CGN** [comment]
Gut, hat ja dann erstmal nichts mehr mit der Batterieladung zu tun :)
Ich schaue mal, ob ich das größer machen kann, damit es dann ggf. besser lesbar ist.

**Comment by TJHooker** [comment]
ok Berechnung des ACCUS geht nur wen er auch ACCU % Liefern kann
