### ISSUE TITLE
Animation + Berechnung für Netzbezug

### ISSUE THREAD

**Issue by paba42** [SKB-CGN/ioBroker.energiefluss-erweitert#48]
Hallo!

Im "alten" Energiefluss-Adapter wurde der Pfad vom Netz zum Verbrauch automatisch generiert, wenn weder PV, noch Batterie Strom geliefert haben, oder zu wenig um den Verbrauch zu decken.
In der neuen Version ist das bei den Berechnungen nicht drin.
Könntest Du den Wert ebenfalls über Berechnung bereitstellen?
Wird es generell die Möglichkeit geben, selbst zusätzliche Berechnungen hinzuzufügen?

Ich weiß, dass ich die Werte im ioBroker berechnen und dann die Quelle nutzen kann, aber Du wirst den Reiter doch nicht für 2 Berechnungen erstellt haben :-)

Danke
-Paul

**Comment by SKB-CGN** [comment]
Aufgrund der zuvielen Möglichkeiten sind die 2 Grundberechnungen vorhanden.
Alles weitere kann und muss sich jeder selbst berechnen.

Die Konfiguration ist so gesehen "dumm" und zeigt nur das an, was Du als Benutzer eingibst: wer fließt wann, in welche Richtung.

Im alten Adapter waren die Dinge vorgegeben und so wusste der Adapter, was verbraucht/eingespeist/geladen wurde.
Es wird aktuell keine anderen Berechnungen geben, außer in einer nächsten Version, wo man Werte von anderen nicht nur subtrahieren sondern auch addieren kann.
