### ISSUE TITLE
Please consider renaming to english title

### ISSUE THREAD

**Issue by mcm1957** [SKB-CGN/ioBroker.energiefluss-erweitert#50]
As IioBroker is an international software and this adapter seem to useable aoutside german speaking contries, please consioder renaming the adapter to an english title.

In addition evaluate if a shorter title is possible as the title is part of all (full) ids and hance tehy get eventually very long and harder to reead due to cutting of at several display fields / columns.

THANKS for evaluation

**Comment by SKB-CGN** [comment]
I was asking @apollon77 about the naming and he confirmed, that the German name is not a problem.
Further, this one is the extended Version of the previously released one 'energiefluss'.
Please accept my apologies, but a renaming is not possible.

**Comment by Apollon77** [comment]
Correct, it is uncommon but not forbidden :-)

**Comment by mcm1957** [comment]
Ok, then lets close.
