### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by ScumbagSteve** [SKB-CGN/ioBroker.energiefluss-erweitert#52]
An option to make the background transparent would be great.
Right now the background color sticks out in the visualization.

<img width="629" alt="image" src="https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/8447146/f96f7508-5034-4807-a52f-866fc0c6609f">

**Comment by SKB-CGN** [comment]
The light mode has transparent background.
If you want to use transparent with darkmode as well, put into CSS styles:
@media (prefers-color-scheme: dark) { 
     :root { 
         --background-color: transparent;
      }
}``

**Comment by ScumbagSteve** [comment]
Great thanks, fixed for me. Maybe consider an option in the menu, so people don't need to look this up in GitHub.

**Comment by SKB-CGN** [comment]
Everything can be changed via CSS. If I write all the things, it might be a long list.
