### ISSUE TITLE
Echt toll, aber ich hätte fragen

### ISSUE THREAD

**Issue by Muppibaer** [SKB-CGN/ioBroker.energiefluss-erweitert#62]
Erstmal gratulation, ein wirklich toller Adapter ,finde ihn echt Super.

Hätte dann 2 Fragen:
Wenn ich habe eine Anzeigefläche von 500px*500px eingerichte, worauf meine Elemente angeordnet sind ,wie bekomme ich diese
nun auf einem grosseren Bildschirm FHD zum Beispiel zentriert.

Dann wüsste ich noch gerne wie ich die background-color bei einzelnen Elementen setzen kann.

**Comment by Muppibaer** [comment]
Erst einmal danke für die schnelle Antwort
Ich habe 2 felder übereinander gelegt wie auf den Bild zu sehen.

![smq5PWyA](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86938481/194e8009-4696-4549-8b6a-299977e006bb)

Das erste in Hintergrund mit den farben gesetzt, dann das 2 darauf gelegt (als Füllbalken). Habe dann die Rahmen- und Füllfarben gesetzt, sowie unter Erweitert bei Element entsprechend Wert füllen eine Füllfarbe gesetzt. Leider wird trotzdem keine Füllfarbe beim 2 Element gesetzt, sondern die Füllfarbe des 1 Elements scheint durch. Deshalb gehe ich davon aus das die Füllfarbe von dem Punkt Erweitert die Standard Füllfarbe komplet aufhebt. Daher meine Frage nach setzen der Background farbe bei Element 2.

![energiefluss-2](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86938481/8f96788c-7840-4f0b-a79e-58373bdcf119)

Ich hoffe man versteht worum es geht.

Dann noch 2 Anmerkungen 
1. Das Energiefluss-erweitert , da wäre Energiefluss-plus aus meiner sicht besser gewesen, aber ist OKAY.
2. Du solltest deinen PayPal link auch hier anlegen. Da noch nicht vorhanden ,habe ich den von dem alten Adapter genommen.

Danke nochmal für den schon jetzt klasse Adapter.

**Comment by SKB-CGN** [comment]
Guter Einwand mit der Farbe. Das schaue ich mir an - denn tatsächlich, wie Du herausgefunden hast, wird die Farbe von Basic einfach nicht mitgenommen - das war so gewollt, macht bei deinem Zweck aber keinen Sinn.

Der Name war am Anfang "extended" bzw. "advanced" - wurde dann aber eingedeutscht in "Erweitert". Plus hätte man auch nehmen können. Jetzt heisst er so ;)

Paypal ist auch hier und in der Adapter Konfig vorhanden:

![2023-09-14 08_13_44-SKB-CGN_ioBroker energiefluss-erweitert_ This ioBroker adapter is next Version o](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/8145b3e1-ba2e-4cbf-932e-938fbcfd83f8)

**Comment by Muppibaer** [comment]
Schon mal ein Danke für deine Bemühungen, und du hast recht mit dem PayPal link . Hatte ich garnicht wahr genommen an der Stelle.

**Comment by Muppibaer** [comment]
Ich noch einmal. Habe erst einmal eine prowisorische Lösung gefunden . Ich erzeuge von 2 Element ein Duplikat das ich hinter dem 2 Element lege, Bei dem Duplikat setze ich dann nur die Standard Füllfarbe und schon geht es.

![Energiefluss-erw2](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/86938481/8670b159-7a9b-4049-8d8a-470af30d07c5)

Mir ist noch aufgefallen, wenn ich Änderungen mache und über Speichern und Verlassen sichere, werden die Änderungen nicht gespeichert. Speicher und beende ich über die einzelnen Buttons , sind die neuen Daten gespeichert.

**Comment by SKB-CGN** [comment]
Habe die Änderung gerade testweise eingebaut. Wenn Du nochmal drüber installierst, sollte die Füllfarbe von Basic den restlichen Bereich ausfüllen. Wenn keine Farbe gesetzt ist, wird transparent (durchsichtig) genutzt.
Auch habe ich noch ein Timeout fürs Speichern gesetzt.

Bitte einmal probieren, ob nun alles passt, wie gedacht. Dank!

PS: Danke für den sehr großen Kaffee ;)

**Comment by Muppibaer** [comment]
Super, haut jetzt beides hin, besten Dank. Denn gropen Kaffee hast Dir redlich verdient.
