### ISSUE TITLE
Vorschlag: Berechnungen in die Datenquellen zu verlegen

### ISSUE THREAD

**Issue by volkerrichert** [SKB-CGN/ioBroker.energiefluss-erweitert#68]
Hi!

ich bin eben von der alpha1 auf die alpha20 gegangen. Da sind mir wohl ein paar updates durch gegangen. Dabei habe ich die neuen Berechnungen mit + & - gesehen. Super!

Aber es könnte besser sein, dass in die Datenquellen zu verlegen. Also einen virtuellen Datenpunkt zu haben, denn sich aus der Summe / Differenz von Punkten bestimmt.

Warum ist das besser? Dann könnte man das auch z.b. bei den Pfaden zur Animationssteuerung nutzen.

**Comment by SKB-CGN** [comment]
Hi,
welche Berechnungen meinst Du? Die des Tabs "Berechnung"?
Die erscheinen als Datenpunkte unterhalb calculation.
![2023-09-27 12_15_32-objects - ioBroker-slave](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/30f28daa-3cc3-4701-84c1-f9cfa1b6346d)


Oder, meinst Du, wenn einzelne Elemente von anderen abgezogen werden?
![2023-09-27 12_15_45-Energiefluss - erweitert _Configuration_](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/58603329/aacfd562-3ab7-4254-8da2-a3e77cb4529e)

**Comment by volkerrichert** [comment]
Das 2. Der oberen Teil habe ich noch nicht gesehen. Spannend

**Comment by SKB-CGN** [comment]
So, nochmal zurück zu deiner Anregung. Wie genau hättest Du die Werte denn dort?

**Comment by SKB-CGN** [comment]
Tatsächlich noch nicht ganz, wenn ich ehrlich bin.

Also, Berechnungen aus den Datenanzeigen raus und in Datenpunkte schreiben, damit sie auch für die Linien und ggf. externe Dinge zur Verfügung stehen?

Dafür müsste ich alles umbauen.

Was sind denn die Features Multiply, Scale?

**Comment by volkerrichert** [comment]
Ja, genau so meinte ich das. Aber ggf. ist das ganz dann wirklich nicht sinnvoll und sollte eher im ioBroker gemacht werden. 

Die "Multiply, Scale" stand nur für irgendwelche Ideen ohne besonderen Hintergrund.

**Comment by SKB-CGN** [comment]
> Ja, genau so meinte ich das. Aber ggf. ist das ganz dann wirklich nicht sinnvoll und sollte eher im ioBroker gemacht werden.


Dem stimme ich zu, da es aus meiner Sicht keinen Nutzen hat, einen "Anzeige-Adapter" als Datenhaltung zu nutzen.

**Comment by SKB-CGN** [comment]
Sollte hier noch Diskussionsbedarf bestehen, bitte mitteilen - sonst würde ich bitten, das Issue zu schließen.

Vielen Dank!

**Comment by SKB-CGN** [comment]
Issue aufgrund fehlender Rückmeldung geschlossen
