### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by corsac82** [SKB-CGN/ioBroker.energiefluss-erweitert#7]
Wie kann ich den Adapter einstellen ? Wenn ich auf Instanzen gehe. Finde ich keine einstell Möglichkeiten.

**Comment by SKB-CGN** [comment]
Was steht denn dort?

**Comment by corsac82** [comment]
Über instalink öffnen. Aber ich finde da nix

**Comment by SKB-CGN** [comment]
Diese Links findest Du in den INstanzen nicht?
![2023-04-29 11_29_54-instances - ioBroker](https://user-images.githubusercontent.com/58603329/235295653-e16446d1-555b-404d-9d92-3a46250dd2a7.png)

**Comment by corsac82** [comment]
Doch aber mehr wie das kommt nicht 
![IMG_2339](https://user-images.githubusercontent.com/83873358/235295714-a273b3f7-c202-49d7-9c2e-caf6fbbaa9c3.png)

**Comment by SKB-CGN** [comment]
Gut, ist ja schonmal was. Läuft dein Web-Adapter auf **integrierte** Websockets oder **socket.io**?
Wenn auf socket.io, bitte eine eigene Web-Adapter Instanz einrichten, die auf **integrierten** Websockets und einem eigenen Port läuft.

**Comment by corsac82** [comment]
So ist er eingestellt 

![IMG_2340](https://user-images.githubusercontent.com/83873358/235295878-e12b3c97-1714-469a-917e-2c596f961acd.png)

**Comment by SKB-CGN** [comment]
Reine Websockets entfernen. Ggf für die VIS anpassen oder eigenen Web-Adapter benutzen.

**Comment by corsac82** [comment]
Habe jetzt alle Einstellungen durch. Und sogar nen neuen web installiert.  Aber weiter wie bis hier geht er nicht. 
![Uploading IMG_2341.png…]()

**Comment by SKB-CGN** [comment]
Kannst Du das mal in einem Browser mit F12 Konsole öffnen?

**Comment by corsac82** [comment]
Ja da kommt das. 

![image](https://user-images.githubusercontent.com/83873358/235296832-49241cfe-fa92-4032-a04a-660bf0fc5070.jpg)

**Comment by SKB-CGN** [comment]
Ah, installier die Version nochmal. 
Das localTest war gestern fehlerhaft.

**Comment by corsac82** [comment]
Neu installiert. Immer noch der gleiche Fehler.

**Comment by SKB-CGN** [comment]
Einen upload energiefluss-erweitert auf der Konsole auch gemacht?

**Comment by corsac82** [comment]
Ja. Habe jetzt sogar noch mal komplett gelöscht. Io neu gestartet. Und noch mal neu installiert. Aber immer noch das gleiche

**Comment by SKB-CGN** [comment]
Wie sieht der Fehler jetzt aus?

**Comment by corsac82** [comment]
Immer noch der gleiche 
![image](https://user-images.githubusercontent.com/83873358/235299706-77e7f9b1-5f50-4804-b5c3-6ffb15f72131.jpg)

**Comment by SKB-CGN** [comment]
Ok, dann drück mal im Browser Strg + F5, dann sollten neue Dateien geladen werden.

**Comment by corsac82** [comment]
![image](https://user-images.githubusercontent.com/83873358/235300126-4c2a0837-9d2f-4ffe-9ce4-2deacf5992ac.jpg)

**Comment by SKB-CGN** [comment]
Habe den Adapter gerade frisch auf meinem Test System von Github installiert. Kein Problem, diesen aufzurufen.

Welche Version steht als installiert?

**Comment by corsac82** [comment]
Das zeigt er mir an.

**Comment by corsac82** [comment]
![IMG_2348](https://user-images.githubusercontent.com/83873358/235300326-6d77cec8-fe52-4c43-8664-65fca7c4bc4e.jpeg)

**Comment by SKB-CGN** [comment]
Kannst Du nur mal zum Testen einen anderen Browser nutzen? Ich denke, Firefox cached die Datei und will sie nicht loslassen :)

**Comment by corsac82** [comment]
Microsoft Edge. Das gleiche 
![image](https://user-images.githubusercontent.com/83873358/235300673-e43f3545-72e9-47ea-8c5d-0c080304bbd6.jpg)

**Comment by corsac82** [comment]
Opera auch das gleiche

![image](https://user-images.githubusercontent.com/83873358/235300754-2c322815-df74-4aa5-982f-8f82565590c5.jpg)

**Comment by SKB-CGN** [comment]
Wie sehen denn da die Konsolen aus?

**Comment by corsac82** [comment]
![image](https://user-images.githubusercontent.com/83873358/235300868-e48b77d0-6cc9-4b3c-95ef-786d5886dd89.jpg)

**Comment by corsac82** [comment]
Oder muss ich den normalen Energiefluss Adapter vorher löschen ?

**Comment by SKB-CGN** [comment]
Ne, ne. Der kann bleiben. Aber, die Datei ist immernoch fehlerhaft.

Bitte nochmal auf die Konsole und:
`iob upload energiefluss-erweitert`

**Comment by corsac82** [comment]
Habe ich gemacht. Ist aber immer noch

![image](https://user-images.githubusercontent.com/83873358/235301292-af5ead1f-f124-4ea0-8332-f3cf0b4ce33d.jpg)

**Comment by SKB-CGN** [comment]
Ok, wie hast Du den Adapter installiert?

**Comment by corsac82** [comment]
So habe ich das gemacht 
![image](https://user-images.githubusercontent.com/83873358/235301954-177235e8-a211-475e-b510-c257d9a38d45.jpg)

**Comment by SKB-CGN** [comment]
Schaut gut aus. Was kommt am Ende, wenn Du installieren gedrückt hast?

**Comment by corsac82** [comment]
![image](https://user-images.githubusercontent.com/83873358/235302051-833282cd-ce96-475f-add6-ec84bbad0786.jpg)

**Comment by SKB-CGN** [comment]
Das ist alles? Da fehlt ja ne Menge. Normal sieht die Liste so aus:

`$ iobroker url https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert --host iobrokerStandby --debug

install SKB-CGN/ioBroker.energiefluss-erweitert#78b379c1ff0e23d77d8cc312132a6bbe6cb047a4

Installing SKB-CGN/ioBroker.energiefluss-erweitert#78b379c1ff0e23d77d8cc312132a6bbe6cb047a4... (System call)

npm WARN skipping integrity check for git dependency ssh://git@github.com/SKB-CGN/ioBroker.energiefluss-erweitert.git

changed 1 package in 3s35 packages are looking for funding run `npm fund` for details

upload [14] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/energiefluss-erweitert.png energiefluss-erweitert.png image/png

upload [13] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [10] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/i18n/fr/translations.json i18n/fr/translations.json application/json

upload [9] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/i18n/it/translations.json i18n/it/translations.json application/json

upload [8] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/i18n/nl/translations.json i18n/nl/translations.json application/json

upload [2] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/index_m.html index_m.html text/html

upload [0] energiefluss-erweitert.admin /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/admin/words.js words.js application/javascript

upload [142] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/configuration.html configuration.html text/html

upload [100] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/ios/58.png img/icons/ios/58.png image/png

upload [90] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/LargeTile.scale-200.png img/icons/windows11/LargeTile.scale-200.png image/png

upload [80] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/SplashScreen.scale-200.png img/icons/windows11/SplashScreen.scale-200.png image/png

upload [70] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-256.png img/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-256.png image/png

upload [60] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-80.png img/icons/windows11/Square44x44Logo.altform-lightunplated_targetsize-80.png image/png

upload [50] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/Square44x44Logo.altform-unplated_targetsize-44.png img/icons/windows11/Square44x44Logo.altform-unplated_targetsize-44.png image/png

upload [40] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/Square44x44Logo.scale-200.png img/icons/windows11/Square44x44Logo.scale-200.png image/png

upload [30] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/Square44x44Logo.targetsize-44.png img/icons/windows11/Square44x44Logo.targetsize-44.png image/png

upload [20] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/StoreLogo.scale-200.png img/icons/windows11/StoreLogo.scale-200.png image/png

upload [19] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/StoreLogo.scale-400.png img/icons/windows11/StoreLogo.scale-400.png image/png

upload [18] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/icons/windows11/Wide310x150Logo.scale-100.png img/icons/windows11/Wide310x150Logo.scale-100.png image/png

upload [13] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/img/jquery.minicolors.png img/jquery.minicolors.png image/png

upload [8] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/js/jquery-3.6.4.min.js js/jquery-3.6.4.min.js application/javascript

upload [3] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/style/font/material.woff2 style/font/material.woff2 font/woff2

upload [1] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/style/loading-spinner.css style/loading-spinner.css text/css

upload [0] energiefluss-erweitert /opt/iobroker/node_modules/iobroker.energiefluss-erweitert/www/style/style.css style/style.css text/css

Update "system.adapter.energiefluss-erweitert.0"

Process exited with code 0`

**Comment by SKB-CGN** [comment]
Müsstest Du mal schauen, warum dein ioBroker da nicht installieren möchte. Welche JS Version ist drauf?

**Comment by corsac82** [comment]
![image](https://user-images.githubusercontent.com/83873358/235302271-75ef5e00-9dc3-4594-9446-508784924f00.jpg)

**Comment by SKB-CGN** [comment]
Mach mal folgendes:
- Instanz löschen (bei Instanzen)
- Adapter löschen (bei Adapter)

Dann nochmal über die Konsole statt über die Webseite installieren.

Hoffen wir, das es dann klappt.

**Comment by corsac82** [comment]
Ok ich versuche mal.

**Comment by corsac82** [comment]
So gemacht. Über Konsole installiert. Aber läuft trotzdem nicht. Die Anzahl der Dateien stimmt mit der Anzahl von dir wie oben überein. Der Fehler ist immer noch testlocal

**Comment by SKB-CGN** [comment]
Ok, wenn die Dateien übereinstimmen, dann nochmals ein:

`iob upload energiefluss erweitert`

**Comment by corsac82** [comment]
Ist gemacht. Immer noch der Fehler. ☹️

**Comment by SKB-CGN** [comment]
Habe nochmal etwas angepasst. Kannst Du nochmal drüber installieren und einen upload machen, bitte?

**Comment by corsac82** [comment]
Ich gucke heute Abend. Bin jetzt gerade unterwegs. Aber erst mal vielen Dank für die Hilfe :)

**Comment by SKB-CGN** [comment]
Habe den Fehler gefunden und die Date ausgetauscht. Mir ist aufgefallen, das dein ioB auf Port 80 läuft - da fällt der Port weg, demnach konnte eine Erkennung nicht laufen, ob es local ausgeführt wird.

Wenn Du nun nochmal installierst, sollte es klappen.

**Comment by corsac82** [comment]
Perfekt klappt jetzt. :). Da wäre ich im Leben nicht drauf gekommen. Vielen Dank für deine Mühe.  👍

**Comment by SKB-CGN** [comment]
Puh. Viel Spaß damit ;)

**Comment by corsac82** [comment]
Danke :)
