### ISSUE TITLE
Verbesserungsvorschlag: Skalieren von Werten erlauben

### ISSUE THREAD

**Issue by incase** [SKB-CGN/ioBroker.energiefluss-erweitert#8]
Unsere diversen Geräte (Inverter, Stromzähler etc.) geben leider Werte auf verschiedenen Skalen aus.

Eine Konvertierung im ioBroker ist zwar machbar (über Scripts), ist aber nur für die Visualisierung nötig. Daher der Vorschlag:
Erlaube Skalierung von Werten (von kW zu MW oder W, also Multiplikation/Division mit/durch 1000).

**Comment by SKB-CGN** [comment]
Du kannst doch zwischen W und kW pro Anzeige wählen. Reicht nicht aus?

**Comment by SKB-CGN** [comment]
Oder, ist dem nicht so?

**Comment by incase** [comment]
Dem ist so. Nur ist sowas trotzdem irgendwie verwirrend:

![Screenshot from 2023-04-30 11-32-51](https://user-images.githubusercontent.com/953468/235346275-14709389-97f0-449d-aa9b-faefd7f8a50e.png)

Produktion und Gesamtverbrauch in kW, Energieflüsse in W. Ist halt nicht schön.

**Comment by incase** [comment]
Oh, jetzt sehe ich, was Du meintest. Unter Erweitert gibt es die Möglichkeit zur Umrechnung. Mal ausprobieren.
