### ISSUE TITLE
jquery Errors since update to v0.0.2-alpha.21

### ISSUE THREAD

**Issue by MiWoBln** [SKB-CGN/ioBroker.energiefluss-erweitert#89]
**Describe the bug**  
After Updateing to the 0.0.2-21 and also to the lastest -22 version, the frontend is not shown anymore and stuck in the loading screen:

![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/83462355/fe8e2d3a-ead4-453c-9507-d0de5dc51614)

The browser console show 2 jquery exceptions:
![image](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/83462355/8ebed0b6-0553-4e8c-993a-ca1033d85a9c)

**Versions:**  
 - Adapter version:  v0.0.2-alpha.21
 - JS-Controller version: 5.0.14
 - Node version: v16.20.1
 - Operating system: Linux

Best Mirko

**Comment by SKB-CGN** [comment]
HI,
please use current available version:
https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert#002-alpha23-2023-10-25

**Comment by MiWoBln** [comment]
Works like a charm. Thanks for the quick response...

Best Mirko
