### ISSUE TITLE
Verbesserungsvorschlag: Runden von Werten ermöglichen

### ISSUE THREAD

**Issue by incase** [SKB-CGN/ioBroker.energiefluss-erweitert#9]
Grob gesagt: Nachkommastellen begrenzen.

Ich denke, das geht mit `toFixed(<decimals>)` in Javascript. In der Regel würde ich je nach Einheit wohl 1-3 Nachkommastellen sehen wollen. Und nicht wie im Augenblick gerade 8.

**Comment by SKB-CGN** [comment]
Ist auch pro Datenanzeige vorhanden. ![Screenshot_20230429_145531_Chrome.jpg](https://user-images.githubusercontent.com/58603329/235303586-151d023c-34ec-47fd-89cf-83997429e69a.jpg)

**Comment by SKB-CGN** [comment]
Oder, ist dem nicht so?

**Comment by incase** [comment]
Hatte ich tatsächlich übersehen. Danke für den Hinweis.

**Comment by SKB-CGN** [comment]
Wunderbar. Vielleicht nochmal die Version einfach drüber installieren. Diese hatte aktuell einen Fehler bei den Nachkommastellen, den ich behoben habe.

**Comment by incase** [comment]
Und bevor ich es vergesse: DANKE! - So wie es jetzt ist, kann ich praktisch alles Abbilden, was ich bei unserem Komplexen Setup abbilden möchte. Super!

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. So soll es sein :)
