### ISSUE TITLE
Schattenfarbe wird nicht gespeichert

### ISSUE THREAD

**Issue by micklafisch** [SKB-CGN/ioBroker.energiefluss-erweitert#90]
**Describe the bug**  
In den Kreis- oder auch Rechteckformen wird die Schattenfarbe nicht gespeichert 

**To Reproduce**  
Element markieren, in den Eigenschaften unter Schattenfarbe über den Colorpicker eine Farbe wählen und danach erneut das Element auswählen - Schattenfarbe ist dann wieder leer. Egal ob der voreingestellte Hexwert drinnen steht oder ob ich wie in allen anderen Feldern den RGB Wert angebe, das Feld wird immer wieder geleert

**Expected behavior**  
speichern der Farbe damit ein Schatten der Form angezeigt wird

**Versions:**  
 - Adapter version: 0.0.2-alpha23

**Comment by SKB-CGN** [comment]
Dies kann ich nicht nachvollziehen.
Element markiert, Schattenfarbe ausgewählt, Configbar geschlossen, Element erneut geöffnet. Schattenfarbe da.

**Comment by micklafisch** [comment]
bei mir leider nicht, weder unter Edge noch im Firefox. Auch ein anderer PC wurde bereits getestet..... ohne Erfolg:

![Schatten](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/44931749/0a51d8cc-8b52-4de8-8724-58bf3fa812dc)

**Comment by SKB-CGN** [comment]
War vorher eine andere Version installiert?

Wenn ja, erneut einen Upload des Adapters durchführen.

**Comment by micklafisch** [comment]
ja, die 0.0.2-alpha21 war vorher drauf. Upload wurde nochmal durchgeführt + im Browser danach Strg+F5 - aber weiterhin wird das Feld nicht gespeichert

**Comment by SKB-CGN** [comment]
Versuch mal, wenn du eine rgb oder rgba Farbe nimmst. Anscheinend hat die HEX Farbe ein Problem.

**Comment by micklafisch** [comment]
Hatte ich beides schon im Eingangspost probiert, geht nicht - auch nach dem Upload nicht

**Comment by SKB-CGN** [comment]
Diese Farbe bitte einmal testen, ohne auf den Farben rumzudrücken:

`rgba(63,177,135,0.54)`

**Comment by micklafisch** [comment]
Mein Fehler war beim testen von RGB und RGBA tatsächlich das "a" anzuhängen.

**Comment by SKB-CGN** [comment]
Gut, dann baue ich für die HEX Farben einen Fix ein. Kommt mit der nächsten Version.

**Comment by micklafisch** [comment]
Danke für den superschnellen Support!

**Comment by SKB-CGN** [comment]
Hallo, dein Fehler wurde in der aktuellen Version berücksichtigt.
Bitte installiere diese Version und prüfe, ob alles erledigt ist.

Falls ja, bitte das Issue schließen.

Vielen Dank!

**Comment by micklafisch** [comment]
Dankeschön, funktioniert einwandfrei
