### ISSUE TITLE
Hintergrund

### ISSUE THREAD

**Issue by stoykengesicht** [SKB-CGN/ioBroker.energiefluss-erweitert#91]
Ist es möglich einen transparenten Hintergrund einzufügen

**Comment by SKB-CGN** [comment]
Ja, ist möglich.

**Comment by stoykengesicht** [comment]
wo muss ich das denn einstellen? oder ist das  zum jetzigen zeitpunkt noch nciht möglich?

**Comment by SKB-CGN** [comment]
Dies kannst du im Tab CSS erledigen.
Kommt hier natürlich drauf an, welcher Hintergrund transparent sein soll.

**Comment by stoykengesicht** [comment]
na toll dafür habe ich dafür zu wenig Ahnung.
Ich wollte eigentlich den ,,Grauen" Hintergrund in transparent haben ( so eine art vector datei) dann kann ich deinen geilen adapter über meinen hintergrund ziehen.

**Comment by SKB-CGN** [comment]
CSS ist keine Wissenschaft ;)

`#svg_display‎ {
background-color: transparent;
}`

Sollte den gewünschten Effekt bringen.

**Comment by stoykengesicht** [comment]
oh sehr geil.. aber ich bekomm den grauen balken unten beim dem zahnrad nicht weg ,wenn ich das in die vis packe, ist der immer noch zu sehen oder mach ich was flasch?
ist doch im iframe http://ipadresse von mir /energiefluss-erweitert/index.html??

**Comment by stoykengesicht** [comment]
aber auch beim direkten kopieren http://ipadresse von mir/energiefluss-erweitert/index.html?instance=0 hab ich unten nen grauen balken

**Comment by SKB-CGN** [comment]
Dann versuch:

#svg_display‎, #config_link  { background-color: transparent; }

**Comment by stoykengesicht** [comment]
habe das nun so umgesetzt um die gewünschte farbe zu bekommen:

body   { 
	background-color: #111111; 
	color: #111111;
}
p    { 
	background-color: #111111;
	color: #111111;
}

aber unten ist halt noch nen grauer streifen den ich nciht weg bekomm bzw der wird mir in der vis auch angezeigt

**Comment by SKB-CGN** [comment]
Dann fehlt dies noch für #config_link

**Comment by stoykengesicht** [comment]
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60317479/665abdca-ead1-4cf8-9664-ec1b39c575fc)


den streifen bekommich nciht geändert.. leider

oder mach ich mit dem einfügen in der vis was falsch?
ich habe den link von der seite in das iframe widget gekloppt

**Comment by SKB-CGN** [comment]
Hast du
`#config_link {
background-color: #111111;
color: #111111;
}`

Auch eingefügt?

**Comment by stoykengesicht** [comment]
oh ne.. moment, teste ich

**Comment by stoykengesicht** [comment]
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60317479/b4863300-9003-4dc2-ad3c-eabdcbdc8b03)

so gehts nicht... leider

**Comment by SKB-CGN** [comment]
Ok, dann mach mal einen Rechtsklick auf die graue Fläche, dann Element untersuchen (kann anders lauten).
Davon dann einen Screenshot (müsste HTML Code sein).
Dann kann ich sehen, wo das Problem liegt.

**Comment by stoykengesicht** [comment]
![grafik](https://github.com/SKB-CGN/ioBroker.energiefluss-erweitert/assets/60317479/5eee7847-d9f1-46b0-b740-6ea37c92738a)
kann den balken nicht wirklich anklicken.. es verfärbt sich auch nur beim drüber hoovern der obere breich

**Comment by stoykengesicht** [comment]
sekunde.. moment mal eben

**Comment by stoykengesicht** [comment]
ha, gefunden.. alles gut.. der fehler liegt nicht in deinem adapter... der verfärbt den balken hell grau wenn man über firefox das dunkle thema gewählt hat.. sehr komisch .. mit hell gehts

**Comment by stoykengesicht** [comment]
habe dir mal was für nen kaffee geschickt.. siehe PP

**Comment by SKB-CGN** [comment]
Vielen Dank!
Wenn das Problem behoben ist, kannst Du das Issue ja schließen.
