### ISSUE TITLE
Symbol lässt sich nicht ändern

### ISSUE THREAD

**Issue by thps1990** [SKB-CGN/ioBroker.energiefluss-erweitert#98]
Hi, 
ersteinmal ein großes Lob an die Entwickler, das ist wirklich eine super Arbeit!

Wenn ich versuche ein Symbol einzufügen, dann kann ich dieses nicht ändern, es bleibt Omega, egal was ich unter "Symbol" eintrage. 
Selbst wenn ich den Wert eines Symbols eintrage, das schon im Standard da ist (wie z.B. "mdi:house-city") wird der Wert immer wieder auf "mdi:omega" zurück gesetzt. 

Viele Grüße

THPS

**Comment by SKB-CGN** [comment]
Der Entwickler bedankt sich 😉

Welche Version verwendest Du?

Kommt beim Eingeben eines Icons eine Auswahlliste? Als Beispiel: 'house' eingeben und schauen, ob die Auswahlliste kommt.

Bitte auch im Browser schauen, ob Fehler in der Konsole F12 erscheinen.

**Comment by thps1990** [comment]
Danke für die Rückmeldung. Ich vermute es war ein Browser-Cache Problem. Nach dem löschen des Cache funktioniert es nun.
