### ISSUE TITLE
Vorschlag: Automatischer refresh der Seite

### ISSUE THREAD

**Issue by exaware** [SKB-CGN/ioBroker.energiefluss-erweitert#99]
Nach einer weile ist die Seite nicht mehr aktuell. Es wird weiterhin animiert aber mit alten Werten. Wenn man dann über den Browser die Seite aktualisiert, werden die Werte und Animation aktualisiert. Ein automatischer refresh der Seite würde das Problem vermeiden.

**Comment by SKB-CGN** [comment]
Sobald sich die Werte ändern, werden sie live angezeigt. Hier ist kein refresh notwendig.
Wenn die Werte sich nicht ändern, liegt ein anderes Problem vor.

**Comment by exaware** [comment]
Also bei mir ist das so wenn der Browser inaktiv ist, also im Hintergrund oder in einem inaktiven Tab läuft.

**Comment by SKB-CGN** [comment]
Dann liegt dies am Browser. Welcher wird verwendet?

**Comment by exaware** [comment]
Google Chrome. Auf PC und auf Android. Meine Frau hat das Problem auch auf ihrem iPhone.

**Comment by SKB-CGN** [comment]
Dann beendet Chrome vielleicht die Socket Verbindung.
Kannst du mit F12 mal die Konsole öffnen, dann den Tab in den Hintergrund schicken und nach einer Zeit wieder in Vordergrund holen?
Erscheinen dort dann Fehler, das die Verbindung nicht mehr besteht?

**Comment by exaware** [comment]
Auf dem PC scheint es tatsächlich nicht zu passieren. Ich habe dann zum Vergleich auf meinem Handy die Seite aufgemacht und da wurde mir noch ein alter Wert animiert. Sobald ich runter geswiped habe wurden die Werte aktualisiert. Die Hintergrundsyncronisation ist aktiviert.

**Comment by SKB-CGN** [comment]
Du hast also das Icon für die Seite direkt auf'm Homescreen in Android.
Das habe ich auch so und sie dann mit der Home-Taste minimiert - 5 Minuten später wieder geöffnet und es werden nach ca. 2 Sekunden die Werte aktualisiert.
Schickt dein Android Chrome vielleicht in den Schlaf?

**Comment by exaware** [comment]
Also für den Chrome kann man nicht einstellen ob dieser im Hintergrund weiterhin ausgeführt werden soll oder nicht.
Ich hab es gerade auch nochmal probiert, ich muss kein 2 Minuten warten, damit es nicht mehr aktualisiert wird.

**Comment by SKB-CGN** [comment]
Das heisst, sobald die App im Hintergrund ist, wird nicht mehr aktualisiert?

**Comment by exaware** [comment]
Erst nach einer Weile, wenn ich es direkt danach erneut öffne, passt es. Ich hab es gerade auch mit dem Brave Browser probiert, gleiches Verhalten. Ich glaube das macht das OS. Beim iPhone geht es doch.

**Comment by SKB-CGN** [comment]
Welches Android bzw. Smartphone ist es?

**Comment by exaware** [comment]
Huawei P20 Pro
Android 12

**Comment by SKB-CGN** [comment]
Du bekommst aber beim erneuten Öffnen auch nicht die Lade-Animation, oder?
Sondern einfach das "gefrorene Bild" von vorher, richtig?

**Comment by exaware** [comment]
Es wird schon animiert aber halt mit dem letzten alten Werten.

**Comment by SKB-CGN** [comment]
Ja, die Animationen werden ein oder ausgeblendet - je nach Wert. Richtig.
Ich meinte, was passiert, wenn Du die Web-App erneut öffnest - kommt dann kurz eine Kreiselanimation?

**Comment by exaware** [comment]
Nein

**Comment by SKB-CGN** [comment]
Ok und die Werte werden auch nach einer Minute oder länger nicht aktualisiert?

**Comment by exaware** [comment]
Genau, es wird alles animiert aber die Werte werden nicht aktualisiert.

**Comment by SKB-CGN** [comment]
Ok und auf dem iPhone geht es, wie ich dich verstanden habe. Am Rechner auch. Also ist es tatsächlich ein (geräte-) spezifisches Problme. Habe gerade nochmal auf einem Android 14 (offiziell) geschaut, dort kann ich die Akkunutzung für Chrome modifizieren.
Kannst Du das nochmal verifizieren?
Hast Du vielleicht noch ein anderes Android zum Testen?

**Comment by exaware** [comment]
Also ich habe es jetzt mal auf einem älteren Samsung Tablet ebenfalls mit Chrome probiert. Damit funktioniert es auch. Da sehe ich auch kurz die Kreiselanimation und die Werte fangen direkt an zu zappeln. Ich denke es ist ein Problem mit Huawei oder mit meinem Gerät.

**Comment by SKB-CGN** [comment]
Hast Du vielleicht das WLAN im Standby aus?
Du könntest mal die Browser Fennec, Opera oder Firefox testen. Nicht, das mit Chrome etwas nicht klappt.

**Comment by exaware** [comment]
WLAN geht nicht in den Standby, das können wir ausschließen. Also wenn ich auf dem Samsung den Bildschirm länger aus lasse dann habe ich hier auch das Problem. Ich denke das die inaktive Zeit hier ausschlaggebend ist. Ich finde es wäre besser, wenn die Seite prüft ob sie noch Verbindung hat und wenn nicht, dann ein refresh durchführen. Oder die Seite sollte ab einer definierten Sitzungsdauer automatisch neu refreshen. Weil aktuell scheint es sehr vom Gerät, vom OS oder vom Browser abhängig zu sein.
Im ioBroker verwende ich Jarvis, dort habe ich die Seite in einen iFrame eingebettet. Das iFrame hlt die Seite immer aktiv und macht alle x Sekunden automatisch ein refresh der Seite. Da habe ich das Problem nicht.

**Comment by SKB-CGN** [comment]
Ich habe nun mal ein wenig hin und her getestet und habe folgendes herausgefunden. Vielleicht kannst Du dies in etwa bestätigen:
- Wenn ich die Web-App öffne und anschaue ist alles ok
- Packe ich sie per Home-Taste in den Hintergrund und hole sie hervor, zeigt sie auch alles an
- Öffne ich die Web-App und lasse sie einfach stehen, das Handy geht schlafen und ich wecke es auf - keine Aktualisierung der Daten

Das Problem, was hier auftritt, hatte ich tatsächlich bisher noch nicht, konnte aber herausfinden, woran es liegt.
Sobald die App die Verbindung verliert, wird versucht, die Verbindung wiederherzustellen. Dies klappt auch, weil der "Loading Circle" erscheint und verschwindet. Was aber dann fehlte, ist ein neuer Request an die Datenpunkte zu senden.

Dies baue ich dann in der nächsten Version mit ein.

Danke für die Hinweise und deine Geduld mit dem Testen :)

**Comment by exaware** [comment]
Ich habe zu danken, dass du so schnell geantwortet hast und das jetzt so schnell der fix kommt. Ich freu mich schon.

**Comment by SKB-CGN** [comment]
Hallo, dein Fehler wurde in der aktuellen Version berücksichtigt.
Bitte installiere diese Version und prüfe, ob alles erledigt ist.

Falls ja, bitte das Issue schließen.

Vielen Dank!

**Comment by exaware** [comment]
Werte werden nun sauber aktualisiert.
Vielen Dank!
